import type { Metadata } from "next";
/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { ArrowRight, BookOpen, Search, ShieldCheck, Sparkles } from "lucide-react";
import { CategoryCard, CommunityNotice, TopicCard } from "@/components/community/CommunityCards";
import CommunityAnalytics from "@/components/community/CommunityAnalytics";
import { getCommunityCategories, getCommunityTopics, getPublishedExamUpdates } from "@/lib/community";
import { siteUrl } from "@/lib/seo";

export const metadata: Metadata = { title: "GCSE & A-Level Exam Community | ScienceDojo", description: "A moderated UK exam community for GCSE and A-Level questions, revision discussion, exam technique, and sourced official updates.", alternates: { canonical: `${siteUrl}/community` }, openGraph: { title: "ScienceDojo Exam Community", description: "Useful, moderated GCSE and A-Level discussion for students.", url: `${siteUrl}/community`, type: "website" } };

export default async function CommunityPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams;
  const [categories, topics, updates] = await Promise.all([getCommunityCategories(), getCommunityTopics({ q: q.trim(), limit: 16 }), getPublishedExamUpdates(3)]);
  const counts = Object.fromEntries(categories.map((category) => [category.slug, topics.filter((topic) => topic.category.slug === category.slug).length]));
  const jsonLd = { "@context": "https://schema.org", "@type": "DiscussionForumPosting", headline: "ScienceDojo GCSE and A-Level Exam Community", url: `${siteUrl}/community`, educationalLevel: ["GCSE", "A-Level"], audience: { "@type": "EducationalAudience", educationalRole: "student" } };
  return <main className="min-h-screen bg-[#f7fbff] text-secondary">
    <CommunityAnalytics />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <section className="relative overflow-hidden bg-gradient-to-br from-[#001a3d] via-[#003f7d] to-[#0066cc] px-4 py-16 text-white md:px-8 md:py-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(0,245,212,.18),transparent_32%)]"/><div className="relative mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.28em] text-cyan-200">ScienceDojo Exam Community</p><h1 className="mt-5 text-4xl font-black tracking-tight md:text-6xl">Ask better questions. Prepare for British exams together.</h1><p className="mt-6 text-lg font-semibold leading-8 text-white/72">Moderated GCSE and A-Level discussions, practical revision guidance, and carefully sourced official updates—with student safety built in.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/community/new" className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-black text-white">Ask a question <ArrowRight size={16}/></Link><Link href="/community/guidelines" className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-6 py-3 text-sm font-black"><ShieldCheck size={16}/>How moderation works</Link></div></div></div></section>
    <section className="mx-auto max-w-7xl space-y-12 px-4 py-10 md:px-8 md:py-14">
      <form className="flex max-w-3xl gap-3 rounded-3xl border border-secondary/10 bg-white p-3 shadow-sm"><Search className="ml-3 self-center text-secondary/30"/><input name="q" defaultValue={q} className="min-w-0 flex-1 bg-transparent px-2 font-bold outline-none" placeholder="Search GCSE and A-Level discussions…"/><button className="rounded-2xl bg-secondary px-5 py-3 text-sm font-black text-white">Search</button></form>
      <CommunityNotice />
      {updates.length > 0 && <section><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-primary">Verified sources</p><h2 className="mt-2 text-3xl font-black">Official exam updates</h2></div><Link href="/community/news" className="text-sm font-black text-primary">View all</Link></div><div className="mt-5 grid gap-4 md:grid-cols-3">{updates.map((update: any) => <Link key={update.id} href={`/community/news/${update.slug}`} className="rounded-3xl border border-secondary/10 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-widest text-primary">{update.source_name}</p><h3 className="mt-3 font-black leading-snug">{update.title}</h3><p className="mt-2 line-clamp-3 text-sm font-semibold leading-6 text-secondary/50">{update.summary}</p></Link>)}</div></section>}
      <section><p className="text-xs font-black uppercase tracking-widest text-primary">Find your space</p><h2 className="mt-2 text-3xl font-black">Exam discussions by subject</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <CategoryCard key={category.id} category={category} topicCount={counts[category.slug]}/>)}</div></section>
      <section><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-primary">{q ? "Search results" : "Recently active"}</p><h2 className="mt-2 text-3xl font-black">Useful student discussions</h2></div></div><div className="mt-6 space-y-4">{topics.map((topic) => <TopicCard key={topic.id} topic={topic}/>)}{topics.length === 0 && <div className="rounded-3xl border border-dashed border-secondary/15 bg-white p-10 text-center font-bold text-secondary/40">No published discussions matched yet.</div>}</div></section>
      <section className="grid gap-4 md:grid-cols-3"><Link href="/ai-practice-studio" className="rounded-3xl bg-secondary p-6 text-white"><Sparkles className="text-cyan-300"/><h3 className="mt-4 text-xl font-black">Practise the topic</h3><p className="mt-2 text-sm font-semibold text-white/60">Generate targeted questions with PracticeDojo.</p></Link><Link href="/focus-dojo" className="rounded-3xl border border-secondary/10 bg-white p-6"><BookOpen className="text-primary"/><h3 className="mt-4 text-xl font-black">Plan a focused session</h3><p className="mt-2 text-sm font-semibold text-secondary/50">Turn advice into a calm revision block.</p></Link><Link href="/free-assessment?source=community" className="rounded-3xl border border-primary/15 bg-primary/5 p-6"><ShieldCheck className="text-primary"/><h3 className="mt-4 text-xl font-black">Need individual support?</h3><p className="mt-2 text-sm font-semibold text-secondary/50">Request a free learning assessment.</p></Link></section>
    </section>
  </main>;
}
