import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { siteUrl } from "@/lib/seo";
async function getUpdate(slug: string) { const supabase = await createClient(); const { data } = await supabase.from("community_exam_updates").select("*").eq("slug", slug).eq("status", "published").maybeSingle(); return data; }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const update = await getUpdate(slug); if (!update) return {}; return { title: `${update.title} | ScienceDojo Exam Updates`, description: update.summary.slice(0, 155), alternates: { canonical: `${siteUrl}/community/news/${slug}` } }; }
export default async function NewsDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const update = await getUpdate(slug); if (!update) notFound(); return <main className="min-h-screen bg-[#f7fbff] px-4 py-12 text-secondary"><article className="mx-auto max-w-3xl"><Link href="/community/news" className="text-sm font-black text-primary">← Official updates</Link><div className="mt-7 rounded-[2rem] border border-secondary/10 bg-white p-7 md:p-10"><p className="text-xs font-black uppercase tracking-widest text-primary">{update.source_name} · {new Date(update.source_published_at).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p><h1 className="mt-4 text-4xl font-black tracking-tight">{update.title}</h1><p className="mt-6 whitespace-pre-wrap font-semibold leading-8 text-secondary/68">{update.summary}</p>{update.editorial_note && <aside className="mt-7 rounded-2xl bg-primary/5 p-5 font-semibold leading-7"><strong>ScienceDojo editorial explanation:</strong><br/>{update.editorial_note}</aside>}<a href={update.source_url} target="_blank" rel="noreferrer" className="mt-7 inline-flex rounded-full bg-secondary px-6 py-3 text-sm font-black text-white">Verify on {update.source_name} ↗</a></div></article></main>; }

