import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, Clock } from "lucide-react";
import { getEligibleAcademyCourses } from "@/lib/academy-courses";
import { getAcademyProgressPercent } from "@/lib/tutor-academy";
import { getTutorAcademyProgress } from "@/lib/tutor-academy-progress";

export default async function AcademyCataloguePage() {
  const courses = await getEligibleAcademyCourses();
  const items = await Promise.all(courses.map(async (course) => ({ course, progress: await getTutorAcademyProgress(course.key) })));
  return <main className="min-h-full bg-[#F7F8FA] px-5 py-10 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-primary/60">ScienceDojo Academy</p><h1 className="mt-2 text-4xl font-black tracking-tight text-secondary">Your courses</h1><p className="mt-3 max-w-2xl text-sm font-semibold leading-7 text-secondary/55">Focused learning experiences selected for your role and stage on ScienceDojo.</p><div className="mt-8 grid gap-5 md:grid-cols-2">{items.map(({ course, progress }) => { const percent = getAcademyProgressPercent(progress, course); return <article key={course.key} className="overflow-hidden rounded-[1.5rem] border border-secondary/10 bg-white shadow-sm"><div className="relative h-48 bg-slate-800">{course.heroImage ? <Image src={course.heroImage} alt="" fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover" /> : null}<div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" /><h2 className="absolute inset-x-5 bottom-5 text-2xl font-black text-white">{course.title}</h2></div><div className="p-5"><p className="text-sm font-medium leading-6 text-secondary/60">{course.description}</p><div className="mt-4 flex gap-4 text-xs font-bold text-secondary/45"><span className="inline-flex gap-1.5"><BookOpen size={14} />{course.lessons.length} lessons</span><span className="inline-flex gap-1.5"><Clock size={14} />{course.estimatedMinutes} min</span></div><div className="mt-5 h-1 bg-slate-100"><div className="h-full bg-primary" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex justify-between text-[10px] font-black uppercase tracking-[0.1em] text-secondary/40"><span>Progress</span><span>{percent}%</span></div><Link href={`/dashboard/academy/${course.key}`} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-full bg-primary px-5 text-xs font-black text-white">{percent ? "Continue" : "Start course"}<ArrowRight size={15} /></Link></div></article>; })}</div>{!items.length ? <div className="mt-8 rounded-2xl bg-white p-8 text-center font-semibold text-secondary/45">No Academy courses are currently assigned to you.</div> : null}</div></main>;
}
