"use server";
import { revalidatePath } from "next/cache";
import { createAdminClient, createClient } from "@/utils/supabase/server";

async function requireAdmin() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error("Unauthorized"); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role !== "admin") throw new Error("Unauthorized"); return { user, admin: await createAdminClient() }; }

export async function moderateCommunityContent(formData: FormData) { const { user, admin } = await requireAdmin(); const kind = String(formData.get("kind")); const id = String(formData.get("id")); const status = String(formData.get("status")); const note = String(formData.get("note") || "").slice(0, 2000) || null; if (!['published','rejected','hidden','locked'].includes(status)) throw new Error("Invalid status"); const table = kind === "reply" ? "community_replies" : "community_topics"; const { data: current } = await admin.from(table).select("status").eq("id", id).single(); const values: Record<string, unknown> = { status }; if (status === "published") values.published_at = new Date().toISOString(); const { error } = await admin.from(table).update(values).eq("id", id); if (error) throw new Error(error.message); await admin.from("community_moderation_log").insert({ moderator_id: user.id, [`${kind === "reply" ? "reply" : "topic"}_id`]: id, action: `set_${status}`, previous_status: current?.status, new_status: status, note }); revalidatePath("/dashboard/admin/community"); revalidatePath("/community", "layout"); }

export async function resolveCommunityReport(formData: FormData) { const { user, admin } = await requireAdmin(); const id = String(formData.get("id")); const status = String(formData.get("status")); if (!['reviewing','resolved','dismissed'].includes(status)) throw new Error("Invalid status"); const resolved = status === "resolved" || status === "dismissed"; await admin.from("community_reports").update({ status, resolved_by: resolved ? user.id : null, resolved_at: resolved ? new Date().toISOString() : null }).eq("id", id); await admin.from("community_moderation_log").insert({ moderator_id: user.id, report_id: id, action: `report_${status}`, new_status: status }); revalidatePath("/dashboard/admin/community"); }

export async function updateContributor(formData: FormData) { const { user, admin } = await requireAdmin(); const userId = String(formData.get("user_id")); const badge = String(formData.get("badge")); if (!['member','tutor','teacher','moderator','staff'].includes(badge)) throw new Error("Invalid badge"); const isVerified = formData.get("is_verified") === "on"; const isTrusted = formData.get("is_trusted") === "on"; const isRestricted = formData.get("is_restricted") === "on"; await admin.from("community_profiles").update({ badge, is_verified: isVerified, is_trusted: isTrusted, is_restricted: isRestricted }).eq("user_id", userId); await admin.from("community_moderation_log").insert({ moderator_id: user.id, action: "update_contributor", note: `${userId}: badge=${badge}, verified=${isVerified}, trusted=${isTrusted}, restricted=${isRestricted}` }); revalidatePath("/dashboard/admin/community"); }

export async function saveCommunityTopic(formData: FormData) { const { user, admin } = await requireAdmin(); const id = String(formData.get("id")); const intent = String(formData.get("intent") || "save"); const title = String(formData.get("title") || "").trim(); const body = String(formData.get("body") || "").trim(); if (title.length < 10 || title.length > 140) throw new Error("Title must be 10–140 characters."); if (body.length < 20 || body.length > 8000) throw new Error("Body must be 20–8000 characters."); const { data: current } = await admin.from("community_topics").select("status").eq("id", id).single(); const values: Record<string, unknown> = { title, body }; if (intent === "publish") { values.status = "published"; values.published_at = new Date().toISOString(); } const { error } = await admin.from("community_topics").update(values).eq("id", id); if (error) throw new Error(error.message); await admin.from("community_moderation_log").insert({ moderator_id: user.id, topic_id: id, action: intent === "publish" ? "edit_publish" : "edit_save", previous_status: current?.status, new_status: intent === "publish" ? "published" : current?.status ?? null }); revalidatePath("/dashboard/admin/community"); revalidatePath("/community", "layout"); }

function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").slice(0, 100); }
export async function createExamUpdate(formData: FormData) { const { user, admin } = await requireAdmin(); const title = String(formData.get("title") || "").trim(); const summary = String(formData.get("summary") || "").trim(); const sourceName = String(formData.get("source_name") || "").trim(); const sourceUrl = String(formData.get("source_url") || "").trim(); const sourceDate = String(formData.get("source_published_at") || ""); const editorialNote = String(formData.get("editorial_note") || "").trim() || null; if (title.length < 10 || summary.length < 20 || !sourceUrl.startsWith("https://") || !sourceDate) throw new Error("Complete all required sourced-update fields."); const { error } = await admin.from("community_exam_updates").insert({ slug: `${slugify(title)}-${crypto.randomUUID().slice(0, 6)}`, title, summary, source_name: sourceName, source_url: sourceUrl, source_published_at: sourceDate, editorial_note: editorialNote, status: "published", published_at: new Date().toISOString(), created_by: user.id, verified_by: user.id }); if (error) throw new Error(error.message); revalidatePath("/dashboard/admin/community"); revalidatePath("/community/news"); }

