import {
  BookOpen,
  CalendarDays,
  ChartColumnIncreasing,
  ChartNoAxesCombined,
  CircleHelp,
  Compass,
  CreditCard,
  ClipboardList,
  Flag,
  GraduationCap,
  House,
  Lightbulb,
  Mail,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  PenLine,
  Search,
  Settings,
  ShieldCheck,
  Siren,
  Star,
  Timer,
  UserRound,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { DashboardNavIconName } from "@/lib/dashboard-navigation";

const icons: Record<DashboardNavIconName, LucideIcon> = {
  overview: ChartColumnIncreasing,
  funnel: ChartNoAxesCombined,
  leads: ClipboardList,
  tutors: GraduationCap,
  users: UserRound,
  team: UsersRound,
  bookings: CalendarDays,
  payouts: Wallet,
  messages: MessageCircle,
  safeguards: ShieldCheck,
  disputes: Siren,
  projects: Lightbulb,
  community: MessagesSquare,
  broadcast: Megaphone,
  communications: Mail,
  academy: BookOpen,
  settings: Settings,
  flags: Flag,
  home: House,
  focus: Timer,
  subscription: CreditCard,
  practice: PenLine,
  guide: BookOpen,
  classes: GraduationCap,
  search: Search,
  missions: Compass,
  profile: UserRound,
  support: CircleHelp,
  success: Star,
};

export default function DashboardNavIcon({ name }: { name: DashboardNavIconName }) {
  const Icon = icons[name];
  return <Icon className="h-[18px] w-[18px]" strokeWidth={1.9} aria-hidden="true" />;
}
