import type { B1Question } from "./german-b1-curriculum.ts";

// New transfer situations rather than a second copy of each grammar check.
export const b1ChapterMastery: B1Question[] = [
  { prompt: "Sie möchten beim Telefonieren sicherer werden. Welcher Plan ist konkret und erreichbar?", answer: "Ich telefoniere einmal pro Woche zehn Minuten und notiere danach drei neue Ausdrücke.", distractors: ["Ich werde irgendwann alles perfekt können.", "Ich vermeide jedes Gespräch und kaufe nur neue Bücher."], explanation: "Der Plan verbindet eine regelmäßige Handlung mit einem überprüfbaren Lernschritt." },
  { prompt: "Sie erzählen von Ihrem ersten Tag in einer neuen Stadt. Welche zeitliche Verbindung passt?", answer: "Als ich ankam, kannte ich niemanden. Danach besuchte ich einen Kurs.", distractors: ["Ob ich ankam, danach niemanden ich kannte.", "Wenn ich morgen ankomme, habe ich gestern niemanden gekannt."], explanation: "Als markiert einen einmaligen vergangenen Moment; danach führt die Geschichte weiter." },
  { prompt: "Ein Treffen wird auf 18 Uhr verschoben. Ihr Kurs beginnt um 18:30. Welche Antwort ist am hilfreichsten?", answer: "Um 18 Uhr kann ich leider nicht, weil mein Kurs bald beginnt. Wäre Freitag um 16 Uhr möglich?", distractors: ["Ich kann nicht. Du bist immer unzuverlässig.", "Ich bestätige 18 Uhr, obwohl ich sicher nicht kommen werde."], explanation: "Eine klare Absage, ein konkreter Grund und eine Alternative ermöglichen eine neue Vereinbarung." },
  { prompt: "Wo oder wohin? Welche Beschreibung unterscheidet Ziel und Position korrekt?", answer: "Ich stelle den Stuhl in den Flur. Jetzt steht er im Flur.", distractors: ["Ich stelle den Stuhl im Flur hinein in dem Flur.", "Jetzt steht der Stuhl in den Flur."], explanation: "Ziel: in den Flur (Akkusativ). Position: im Flur (Dativ)." },
  { prompt: "Sie verstehen eine Arbeitsanweisung nicht genau. Welche Reaktion sichert das Verständnis?", answer: "Ich soll also die Bestellungen bis zwölf prüfen, richtig?", distractors: ["Ich sage nichts und vermute irgendeine Aufgabe.", "Ich bestätige, obwohl ich weder Aufgabe noch Frist kenne."], explanation: "Wiederholung von Aufgabe und Frist ermöglicht eine Korrektur vor Beginn." },
  { prompt: "Sie lernen Deutsch. Ihr Kind soll Sie verstehen. Welche Zweckverbindung passt?", answer: "Ich spreche langsam, damit mein Kind mich versteht.", distractors: ["Ich spreche langsam, um mein Kind mich zu verstehen.", "Ich spreche langsam, damit versteht mein Kind mich."], explanation: "Unterschiedliche Subjekte brauchen hier damit; das Verb steht am Ende." },
  { prompt: "Ihre Beschwerden dauern seit Montag an. Welche Nachricht nennt die nötigen Informationen für eine Terminfrage?", answer: "Seit Montag habe ich Beschwerden. Könnte ich am Freitag einen Untersuchungstermin bekommen?", distractors: ["Ich brauche irgendetwas irgendwann.", "Ich verlange eine Diagnose, ohne meine Beschwerden zu nennen."], explanation: "Dauer und konkrete Terminbitte helfen, das Anliegen zu verstehen." },
  { prompt: "Ihre Unterkunft hat eine Rezeption bis 18 Uhr; Ihr Zug kommt erst um 19 Uhr. Was ist ein sinnvoller nächster Schritt?", answer: "Die Unterkunft über die Verspätung informieren und die Schlüsselübergabe klären.", distractors: ["Annehmen, dass die Rezeption ohne Rückfrage offen bleibt.", "Nur die alte Ankunftszeit bestätigen."], explanation: "Die Verspätung betrifft eine Bedingung der Unterkunft; frühe Rückfrage vermeidet ein Problem." },
  { prompt: "Was bedeutet: Ich lasse den Akku reparieren?", answer: "Eine andere Person repariert den Akku für mich.", distractors: ["Ich repariere ihn zwingend selbst.", "Ich entscheide, dass er niemals repariert wird."], explanation: "Lassen + Infinitiv kann ausdrücken, dass man eine Handlung durch eine andere Person veranlasst." },
  { prompt: "Die Lernapp ist praktisch, Sie nutzen sie aber selten. Welche Verbindung drückt den Gegensatz korrekt aus?", answer: "Obwohl die Lernapp praktisch ist, nutze ich sie selten.", distractors: ["Deshalb die Lernapp praktisch ist, nutze ich sie selten.", "Obwohl die Lernapp ist praktisch, ich nutze sie selten."], explanation: "Obwohl + Verb am Ende; nach dem vorangestellten Nebensatz beginnt der Hauptsatz mit nutze." },
  { prompt: "Unterscheiden Sie Zukunft und Passiv. Welche Aussage kündigt eine eigene zukünftige Handlung an?", answer: "Wir werden die Geräte nächste Woche reparieren.", distractors: ["Die Geräte werden gerade repariert.", "Die Geräte sind repariert."], explanation: "Werden + Infinitiv ist Futur I; werden + Partizip II ist Vorgangspassiv." },
  { prompt: "Zwei Gruppen wünschen unterschiedliche Treffzeiten. Welche Antwort vermittelt beide Perspektiven fair?", answer: "Berufstätige möchten abends kommen, andere lieber nachmittags. Wir könnten einen zusätzlichen Abend testen.", distractors: ["Nur eine Gruppe hat richtige Wünsche; die andere soll schweigen.", "Wir ändern alle Zeiten sofort, ohne Gründe anzuhören."], explanation: "Die Antwort benennt beide Wünsche und eine überprüfbare gemeinsame Möglichkeit." },
  { prompt: "Welche Empfehlung verbindet Bewertung und konkrete Einschränkung?", answer: "Die Ausstellung ist interessant, allerdings sind einige Texte klein gedruckt.", distractors: ["Alle werden die Ausstellung sicher perfekt finden.", "Ich empfehle sie, aber ich sage nicht, warum."], explanation: "Eine hilfreiche Empfehlung nennt einen positiven Punkt und eine belegbare Einschränkung." },
  { prompt: "Sie arbeiten in wechselnden Schichten. Welche Haushaltsregel berücksichtigt Flexibilität und Verbindlichkeit?", answer: "Wir verteilen Aufgaben mit einer Wochenfrist und sagen früh Bescheid, wenn es nicht klappt.", distractors: ["Alle müssen jeden Morgen dieselbe Aufgabe erledigen, auch während ihrer Arbeit.", "Niemand ist mehr für eine Aufgabe zuständig."], explanation: "Die Frist schafft Verbindlichkeit, während die konkrete Zeit flexibel bleibt." },
  { prompt: "Nach einer Präsentation fragt jemand nach einem Beispiel. Was ist die passende Reaktion?", answer: "Vielen Dank für die Frage. In meinem Alltag war das zum Beispiel so: …", distractors: ["Ich lese die gesamte Präsentation noch einmal ohne Bezug zur Frage.", "Ich beende das Gespräch, weil Fragen nicht erlaubt sind."], explanation: "Eine direkte Antwort mit Beispiel zeigt, dass Sie die Frage verstanden haben." },
  { prompt: "Der Raum kostet 40 Euro, das Gesamtbudget ist 60 Euro und eine Küche gibt es nicht. Welcher Plan berücksichtigt alle Bedingungen?", answer: "Wir reservieren den Raum, planen Getränke für höchstens 20 Euro und bringen kalte Speisen freiwillig mit.", distractors: ["Wir geben zusätzlich 60 Euro aus und kochen in der vorhandenen Küche.", "Wir reservieren einen kostenlosen Raum und brauchen keinen Ersatzplan."], explanation: "Der Plan berücksichtigt Restbudget und fehlende Küche; Beiträge bleiben freiwillig." },
];
