import type { A2Question } from "./german-a2-curriculum.ts";

type ReadingTask = { title: string; text: string; questions: A2Question[] };
type AudioTask = { id: string; title: string; segments: { speaker: string; text: string }[]; questions: A2Question[] };
export type A2ExamSet = {
  id: string; reading: ReadingTask[]; audio: AudioTask[];
  notePrompt: string; noteModel: string; formPrompt: string; formModel: string;
  smsPrompt: string; smsModel: string; emailPrompt: string; emailModel: string;
  telcPrompt: string; telcModel: string; personalTopic: string; personalModel: string;
  calendar: string; calendarModel: string;
};

const question = (prompt: string, answer: string, a: string, b: string, explanation: string): A2Question => ({ prompt, answer, distractors: [a, b], explanation });
const anna = "Anna";
const ben = "Eddy (German (Germany))";
const audio = (set: string, index: number, title: string, turns: string[], questions: A2Question[]): AudioTask => ({
  id: `a2-${set}-${index}`, title, segments: turns.map((text, i) => ({ speaker: i % 2 ? ben : anna, text })), questions,
});

// The provider formats are taught separately; these original reduced sets train their task skills.
export const a2ExamSets: A2ExamSet[] = [
  {
    id: "practice",
    reading: [
      { title: "Artikel · global und im Detail", text: "Nora hat ein kleines Lerncafé eröffnet. Früher hat sie in einer Schule gearbeitet. Jetzt hilft sie Erwachsenen, im Alltag Deutsch zu sprechen. Das Café öffnet Dienstag und Donnerstag von 17 bis 20 Uhr. Gäste kaufen ein Getränk, aber die Gespräche kosten nichts extra. Am ersten Abend kamen zwölf Personen. Nora möchte kein zweites Café eröffnen. Sie möchte zuerst mehr Spiele für die Gespräche kaufen.", questions: [question("Wann kann man im Lerncafé sprechen?", "Dienstag und Donnerstag am Abend.", "Jeden Vormittag.", "Nur am Sonntag.", "Die Öffnungszeiten sind Dienstag und Donnerstag 17–20 Uhr."), question("Was plant Nora als Nächstes?", "Mehr Spiele kaufen.", "Ein zweites Café eröffnen.", "Wieder als Ärztin arbeiten.", "Sie möchte zuerst Spiele kaufen und ausdrücklich kein zweites Café eröffnen.")] },
      { title: "Orientierung · Informationstafel", text: "Lernhaus: Erdgeschoss — Empfang, Café. 1. Stock — Sprachkurse, Anmeldung. 2. Stock — Bibliothek, Computerraum. 3. Stock — Sportkurse. Bücher können nur im zweiten Stock ausgeliehen werden. Kursgebühren bezahlen Sie bei der Anmeldung, nicht im Café.", questions: [question("Sie möchten ein Buch ausleihen. Wohin gehen Sie?", "In den 2. Stock.", "Ins Erdgeschoss.", "In den 3. Stock.", "Die Bibliothek und die Ausleihe befinden sich im zweiten Stock."), question("Wo bezahlen Sie einen Sprachkurs?", "Bei der Anmeldung im 1. Stock.", "Im Café.", "Im Sportkurs im 3. Stock.", "Die Tafel nennt Anmeldung im ersten Stock und schließt das Café aus.")] },
      { title: "Persönliche Nachricht · Details", text: "Hallo Mila, unser Ausflug ist am Samstag. Wir treffen uns um 9 Uhr vor dem Bahnhof. Der Zug fährt um 9:20 Uhr. Bitte bring Brot und Wasser mit. Ich kaufe die Fahrkarten für uns beide. Weil das Museum erst um elf öffnet, gehen wir zuerst durch die Stadt. Wenn du nicht mitkommen kannst, sag mir bis Donnerstag Bescheid. Viele Grüße, Ben", questions: [question("Ben kauft die Fahrkarten für beide. Richtig oder falsch?", "Richtig.", "Falsch.", "Der Text enthält keine Information dazu.", "Ben schreibt ausdrücklich, dass er beide Fahrkarten kauft."), question("Wann treffen sich Mila und Ben?", "Um 9 Uhr vor dem Bahnhof.", "Um 9:20 Uhr im Museum.", "Am Donnerstag um 11 Uhr.", "9 Uhr ist der Treffpunkt; 9:20 ist die Zugabfahrt.")] },
      { title: "Anzeigen · passende und fehlende Angebote", text: "A: Café Sonne — Sonntagsfrühstück ab 9 Uhr, vegetarische Speisen, keine Abendöffnung. B: Kino Mitte — Filme täglich ab 18 Uhr; Tickets online. C: Fahrradwerkstatt — Reparaturen Montag bis Freitag. D: Lernclub — kostenloses Deutschsprechen Samstag 14–16 Uhr, Anmeldung nötig.", questions: [question("Mila möchte am Samstag kostenlos Deutsch sprechen. Welche Anzeige passt?", "D: Lernclub.", "A: Café Sonne.", "C: Fahrradwerkstatt.", "Nur D erfüllt Sprache, Preis und Tag."), question("Ben möchte am Sonntag sein Fahrrad reparieren lassen. Was passt?", "X: Keine Anzeige passt.", "C: Fahrradwerkstatt.", "B: Kino Mitte.", "C repariert nur Montag bis Freitag; es gibt kein passendes Sonntagsangebot.")] },
    ],
    audio: [
      audio("practice", 1, "Nachricht · Telefonnotiz", ["Guten Tag, hier ist das Lernhaus. Ihr Beratungstermin ist am Dienstag um sechzehn Uhr zwanzig in Raum neun. Bitte bringen Sie Ihren Ausweis mit. Bei Fragen rufen Sie uns unter null zwei zwei acht, fünf fünf eins, drei null an. Der alte Termin am Montag ist abgesagt. Vielen Dank."], [question("Wann ist der neue Termin?", "Dienstag um 16:20 Uhr.", "Montag um 16:20 Uhr.", "Dienstag um 9 Uhr.", "Die Nachricht nennt Dienstag 16:20 und sagt den Montagstermin ab."), question("Was soll die Person mitbringen?", "Den Ausweis.", "Ein Fahrrad.", "Die Eintrittskarte fürs Kino.", "Die Aufforderung lautet: Ausweis mitbringen.")]),
      audio("practice", 2, "Wochenplan · Informationen zuordnen", ["Ben, was machst du diese Woche?", "Montag gehe ich schwimmen. Dienstag besuche ich meine Schwester. Mittwoch muss ich am Abend arbeiten.", "Und Donnerstag? Gehen wir ins Kino?", "Donnerstag habe ich einen Sprachkurs. Aber Freitag können wir ins Kino gehen.", "Gut. Am Samstag können wir zusammen einkaufen.", "Samstag helfe ich meinem Bruder beim Umzug. Einkaufen geht am Sonntag nicht, weil die Geschäfte geschlossen sind."], [question("Was macht Ben am Donnerstag?", "Er besucht einen Sprachkurs.", "Er geht ins Kino.", "Er hilft beim Umzug.", "Donnerstag ist der Sprachkurs; Freitag ist Kino und Samstag Umzug."), question("An welchem Tag besucht Ben seine Schwester?", "Dienstag.", "Montag.", "Samstag.", "Dienstag ist der Besuch, Montag Schwimmen.")]),
      audio("practice", 3, "Kurzes Gespräch · Entscheidung", ["Möchten Sie ein Ticket für heute oder morgen?", "Für morgen bitte. Gibt es einen direkten Zug?", "Der direkte Zug fährt um acht, aber er ist voll. Um neun gibt es einen Zug mit Umstieg.", "Dann nehme ich den um neun. Ich möchte einen Sitzplatz.", "Das ist möglich. Sie steigen in Köln um.", "Gut, dann kaufe ich das Ticket für morgen um neun."], [question("Welches Ticket kauft der Reisende?", "Morgen um 9 Uhr mit Umstieg.", "Heute um 8 Uhr direkt.", "Morgen um 8 Uhr direkt.", "Der Reisende entscheidet sich für morgen um neun, da der direkte Zug voll ist.")]),
      audio("practice", 4, "Interview · Aussagen prüfen", ["Nora, warum hast du das Lerncafé eröffnet?", "Ich wollte Erwachsenen helfen. Früher habe ich in einer Schule gearbeitet. Jetzt arbeite ich lieber mit kleinen Gruppen.", "Kommen nur Anfänger?", "Nein, viele können schon etwas Deutsch. Sie möchten vor allem sprechen. Grammatik machen wir nur kurz.", "Ist das Café auch am Wochenende offen?", "Noch nicht. Im Moment öffnen wir Dienstag und Donnerstag. Vielleicht ändern wir das später."], [question("Nora arbeitet jetzt lieber mit kleinen Gruppen. Ja oder nein?", "Ja.", "Nein.", "Sie spricht nicht über Gruppen.", "Nora nennt kleine Gruppen als ihre heutige Vorliebe."), question("Das Lerncafé ist schon am Wochenende offen. Ja oder nein?", "Nein.", "Ja.", "Es öffnet nur am Samstag.", "Noch nicht: Im Moment Dienstag und Donnerstag.")]),
    ],
    notePrompt: "Hören Sie die Telefonnotiz. Notieren Sie genau fünf Felder: Tag; Uhrzeit; Raum; mitbringen; Telefonnummer. Erst danach das Transcript öffnen.", noteModel: "Dienstag; 16:20; Raum 9; Ausweis; 0228 55130",
    formPrompt: "Melden Sie eine Freundin an. Angaben: Lea König, geboren am 12. Mai 1998, wohnt in Bonn, möchte A2 am Abend lernen, zahlt per Überweisung. Ergänzen Sie fünf Felder: Nachname; Geburtsdatum; Wohnort; Kurs; Zahlungsart.", formModel: "König; 12.05.1998; Bonn; A2-Abendkurs; Überweisung",
    smsPrompt: "Sie kommen zum Lerntreff zu spät. Schreiben Sie Ben 20–30 Wörter: entschuldigen, Grund nennen, neue Ankunftszeit nennen.", smsModel: "Hallo Ben, es tut mir leid, ich komme später, weil mein Bus Verspätung hat. Ich bin um 18:30 Uhr in der Bibliothek. Bis gleich!",
    emailPrompt: "Schreiben Sie Frau Berger 30–40 Wörter: für die Einladung zum Kursfest bedanken, zusagen, fragen, ob Sie einen Salat mitbringen sollen.", emailModel: "Sehr geehrte Frau Berger, vielen Dank für Ihre Einladung zum Kursfest. Ich komme am Freitag gern. Soll ich einen Salat mitbringen? Bitte sagen Sie mir kurz Bescheid. Ich freue mich auf das Fest. Mit freundlichen Grüßen Mila Nowak",
    telcPrompt: "Ihr Freund Ben lädt Sie zum Ausflug ein. Wählen Sie drei von vier Punkten: bedanken; zusagen/absagen; fragen, was Sie mitbringen sollen; fragen, wann Sie zurückkommen. Schreiben Sie etwa 40 Wörter mit Anrede und Schluss.", telcModel: "Hallo Ben, vielen Dank für die Einladung. Ich komme am Samstag gern mit, weil ich die Stadt noch nicht kenne. Was soll ich mitbringen? Brot und Wasser habe ich zu Hause. Ich freue mich auf unseren Ausflug. Viele Grüße, Mila",
    personalTopic: "Was machen Sie gern am Wochenende? Stichwörter: mit wem, Ort, Aktivität, Häufigkeit.", personalModel: "Am Wochenende treffe ich oft meine Freunde. Wir gehen im Park spazieren oder kochen bei mir. Einmal im Monat besuchen wir ein Museum. Das gefällt mir, weil wir dabei viel sprechen können.",
    calendar: "Planen Sie einen gemeinsamen Einkauf. A: Montag frei 16–18 Uhr, Dienstag Arbeit bis 20 Uhr, Mittwoch frei ab 17 Uhr. B: Montag Arbeit bis 19 Uhr, Dienstag frei, Mittwoch frei 17–19 Uhr. Finden Sie Tag, Uhrzeit und Treffpunkt.", calendarModel: "A: Hast du Montag Zeit? B: Erst nach sieben. A: Dann geht es nicht. Wie wäre Mittwoch um fünf? B: Ja, ich habe bis sieben Zeit. A: Treffen wir uns vor dem Einkaufszentrum? B: Gut, Mittwoch um siebzehn Uhr.",
  },
  {
    id: "mock-1",
    reading: [
      { title: "Artikel · neuer Nachbarschaftsgarten", text: "Seit April gibt es im Hof einen Garten. Die Nachbarn haben dort Gemüse und Blumen gepflanzt. Jana organisiert die Arbeit. Früher hatte sie nur Pflanzen auf ihrem Balkon. Jetzt trifft sie jeden Samstag andere Nachbarn im Garten. Die Teilnahme ist kostenlos, aber alle bringen eigene Handschuhe mit. Jana möchte im nächsten Monat einen kleinen Tisch kaufen. Bei Regen trifft sich die Gruppe im Gemeinschaftsraum.", questions: [question("Was müssen Teilnehmende mitbringen?", "Eigene Handschuhe.", "Eine Eintrittskarte.", "Einen eigenen Tisch.", "Die Teilnahme ist kostenlos; Handschuhe werden selbst mitgebracht."), question("Wo trifft sich die Gruppe bei Regen?", "Im Gemeinschaftsraum.", "Auf Janas Balkon.", "Immer im Garten.", "Der letzte Satz nennt den Gemeinschaftsraum als Regenalternative.")] },
      { title: "Orientierung · Stadtzentrum", text: "Haus Mitte: EG — Empfang und Poststelle; 1. Stock — Bürgerbüro; 2. Stock — Sprachschule; 3. Stock — Gemeinschaftsraum. Die Poststelle nimmt Pakete an. Ausweise werden ausschließlich im Bürgerbüro bearbeitet. Der Gemeinschaftsraum ist für private Treffen buchbar.", questions: [question("Sie möchten ein Paket abschicken. Wohin gehen Sie?", "Ins Erdgeschoss.", "In den 2. Stock.", "In den Gemeinschaftsraum.", "Die Poststelle im EG nimmt Pakete an."), question("Wo werden Ausweise bearbeitet?", "Im Bürgerbüro im 1. Stock.", "In der Sprachschule.", "Am Empfang im 3. Stock.", "Ausweise gehören zum Bürgerbüro im ersten Stock.")] },
      { title: "Nachricht · Reparaturtermin", text: "Guten Tag Frau Nowak, wir können Ihre Waschmaschine am Donnerstag zwischen 10 und 12 Uhr reparieren. Bitte bleiben Sie in dieser Zeit zu Hause. Falls die Zeit nicht passt, rufen Sie bis Dienstag an. Unser Mitarbeiter bringt die nötigen Teile mit. Bitte räumen Sie vor dem Termin den Platz vor der Maschine frei. Bezahlen können Sie nach der Reparatur mit Karte. Barzahlung ist bei diesem Termin nicht möglich. Freundliche Grüße, Reparaturteam", questions: [question("Barzahlung ist möglich. Richtig oder falsch?", "Falsch.", "Richtig.", "Der Text nennt keine Zahlungsart.", "Die Nachricht schließt Barzahlung ausdrücklich aus."), question("Wann soll Mila bei einem Terminproblem anrufen?", "Bis Dienstag.", "Erst Donnerstag um 12 Uhr.", "Nur nach der Reparatur.", "Die Rückmeldefrist ist Dienstag.")] },
      { title: "Anzeigen · alle Bedingungen prüfen", text: "A: Sprachcafé — Montag 18 Uhr, kostenlos. B: Kinderspielgruppe — Samstag 10 Uhr, nur mit erwachsener Begleitung. C: Fahrradservice — Samstag 9–13 Uhr, keine Sonntagstermine. D: Filmclub — Mittwoch 19 Uhr, Eintritt 5 Euro.", questions: [question("Ben möchte Samstagvormittag sein Fahrrad reparieren lassen. Welche Anzeige passt?", "C: Fahrradservice.", "A: Sprachcafé.", "D: Filmclub.", "Nur C bietet Fahrradreparaturen am Samstagvormittag."), question("Mila sucht kostenloses Deutschsprechen am Sonntag. Welche Anzeige passt?", "X: Keine Anzeige passt.", "A: Sprachcafé.", "B: Kinderspielgruppe.", "A hat das richtige Thema und den richtigen Preis, aber den falschen Tag.")] },
    ],
    audio: [
      audio("mock-1", 1, "Telefonnotiz · Werkstatt", ["Guten Tag, hier ist die Werkstatt. Ihr Fahrrad ist fertig. Sie können es am Freitag ab vierzehn Uhr abholen. Die Reparatur kostet achtunddreißig Euro. Wir schließen um achtzehn Uhr. Bei Fragen erreichen Sie uns unter null zwei zwei acht, vier eins null, zwei sechs. Vielen Dank."], [question("Ab wann kann das Fahrrad abgeholt werden?", "Freitag ab 14 Uhr.", "Donnerstag ab 18 Uhr.", "Freitag erst um 18 Uhr.", "14 Uhr ist der Beginn der Abholung, 18 Uhr die Schließzeit."), question("Wie viel kostet die Reparatur?", "38 Euro.", "18 Euro.", "14 Euro.", "Die Aufnahme nennt achtunddreißig Euro.")]),
      audio("mock-1", 2, "Wochenplan · Aktivitäten", ["Mila, hast du diese Woche Zeit?", "Montag besuche ich den Sprachkurs. Dienstag gehe ich zum Arzt.", "Können wir Mittwoch schwimmen gehen?", "Mittwoch arbeite ich spät. Donnerstag gehe ich schwimmen. Da kannst du mitkommen.", "Gut. Und Freitag?", "Freitag hole ich mein Fahrrad ab. Samstag besuche ich meine Eltern."], [question("Wann geht Mila schwimmen?", "Donnerstag.", "Mittwoch.", "Samstag.", "Sie korrigiert den Vorschlag Mittwoch und nennt Donnerstag."), question("Was macht Mila am Samstag?", "Sie besucht ihre Eltern.", "Sie holt ihr Fahrrad ab.", "Sie geht zum Arzt.", "Samstag Eltern, Freitag Fahrrad, Dienstag Arzt.")]),
      audio("mock-1", 3, "Gespräch · Rechnung", ["Möchten Sie zusammen oder getrennt bezahlen?", "Getrennt bitte. Ich hatte die Suppe und das Wasser.", "Die Suppe kostet sechs Euro. Das kleine Wasser war kostenlos dabei.", "Dann bezahle ich sechs Euro mit Karte.", "Gern. Ihre Freundin bezahlt den Salat und den Saft.", "Danke, dann ist meine Rechnung erledigt."], [question("Wie viel bezahlt der Gast?", "6 Euro.", "8 Euro.", "Alle Speisen von beiden Gästen.", "Er bezahlt getrennt nur die Suppe; das kleine Wasser war kostenlos.")]),
      audio("mock-1", 4, "Interview · Janas Garten", ["Jana, hattest du früher schon einen großen Garten?", "Nein, nur einen kleinen Balkon. Jetzt haben wir den Garten im Hof.", "Arbeitest du dort jeden Tag?", "Nein, wir treffen uns samstags. Unter der Woche arbeite ich im Büro.", "Müssen die Nachbarn bezahlen?", "Nein. Sie bringen Handschuhe mit. Nächsten Monat möchte ich einen Tisch kaufen."], [question("Jana hatte früher einen großen Garten. Ja oder nein?", "Nein.", "Ja.", "Sie sagt, dass sie früher im Hof wohnte.", "Früher hatte Jana nur einen kleinen Balkon."), question("Die Gruppe trifft sich samstags. Ja oder nein?", "Ja.", "Nein.", "Nur am Montag.", "Jana nennt samstags ausdrücklich.")]),
    ],
    notePrompt: "Notieren Sie aus der Werkstattnachricht fünf Felder: Abholtag; ab Uhrzeit; Preis; Schließzeit; Telefonnummer.", noteModel: "Freitag; 14 Uhr; 38 Euro; 18 Uhr; 0228 41026",
    formPrompt: "Reservieren Sie für Ben Roth einen Platz: wohnt in Köln, nimmt Samstag am Gartenkurs teil, bringt eigene Handschuhe mit, bezahlt 12 Euro per Karte. Ergänzen Sie Nachname; Wohnort; Kurstag; Material; Zahlungsart.", formModel: "Roth; Köln; Samstag; eigene Handschuhe; Karte",
    smsPrompt: "Sie verpassen den Bus zur Gartenaktion. Schreiben Sie Jana 20–30 Wörter: entschuldigen, Grund nennen, neue Ankunftszeit nennen.", smsModel: "Hallo Jana, entschuldige bitte, ich habe den Bus verpasst. Deshalb komme ich erst um 15:30 Uhr zum Garten. Ich bringe meine Handschuhe mit. Bis gleich!",
    emailPrompt: "Schreiben Sie dem Reparaturteam 30–40 Wörter: für den Termin bedanken, absagen, nach einem Freitagstermin fragen.", emailModel: "Sehr geehrte Damen und Herren, vielen Dank für den Reparaturtermin. Leider kann ich am Donnerstag nicht zu Hause bleiben, weil ich arbeiten muss. Haben Sie am Freitag einen freien Termin? Vielen Dank für Ihre Antwort. Mit freundlichen Grüßen Mila Nowak",
    telcPrompt: "Jana lädt Sie zur Gartenaktion ein. Wählen Sie drei von vier Punkten: bedanken; erklären, wann Sie kommen; sagen, was Sie mitbringen; nach einer Regenalternative fragen. Schreiben Sie etwa 40 Wörter.", telcModel: "Hallo Jana, vielen Dank für die Einladung zur Gartenaktion. Ich komme am Samstag um drei, weil ich vorher arbeiten muss. Ich bringe meine Handschuhe und etwas Wasser mit. Ich freue mich, die Nachbarn kennenzulernen und im Garten zu helfen. Viele Grüße, Mila",
    personalTopic: "Erzählen Sie von Ihrer Wohnung: Zimmer, Lage, Nachbarn und was Ihnen gefällt.", personalModel: "Ich wohne in einer kleinen Wohnung mit zwei Zimmern. Sie liegt nah am Bahnhof. Meine Nachbarn sind freundlich. Mir gefällt der Balkon am besten, weil ich dort Blumen habe und am Abend sitzen kann.",
    calendar: "Vereinbaren Sie einen Besuch in der Werkstatt. A: Freitag frei 14–16 Uhr, Samstag Arbeit 9–13 Uhr. B: Freitag frei ab 15 Uhr, Samstag keine Zeit. Werkstatt: Freitag bis 18 Uhr offen. Finden Sie eine gemeinsame Zeit und einen Treffpunkt.", calendarModel: "A: Können wir Freitag um zwei gehen? B: Ich kann erst ab drei. A: Um drei passt mir auch. Die Werkstatt ist bis sechs offen. B: Dann treffen wir uns um fünfzehn Uhr vor der Werkstatt.",
  },
  {
    id: "mock-2",
    reading: [
      { title: "Artikel · Bibliothek am Abend", text: "Die Bibliothek öffnet seit September donnerstags bis 21 Uhr. Lea, die Leiterin, möchte damit Menschen helfen, die tagsüber arbeiten. Die Ausleihe bleibt kostenlos. Beratung gibt es aber nur bis 19 Uhr. Danach können Gäste selbst Bücher auswählen und am Automaten ausleihen. Ein Sprachcafé findet jeden zweiten Donnerstag um 18 Uhr statt. Eine Anmeldung dafür ist nötig. Lea möchte im Winter zusätzlich einen Schreibtreff anbieten.", questions: [question("Warum gibt es die längere Öffnung?", "Damit berufstätige Menschen abends kommen können.", "Weil die Ausleihe jetzt kostenpflichtig ist.", "Weil alle nur nachts arbeiten.", "Die Leiterin nennt Menschen, die tagsüber arbeiten."), question("Was ist nach 19 Uhr noch möglich?", "Bücher am Automaten ausleihen.", "Persönliche Beratung bis 21 Uhr.", "Ohne Anmeldung immer am Sprachcafé teilnehmen.", "Beratung endet um 19 Uhr; die automatische Ausleihe bleibt möglich.")] },
      { title: "Orientierung · Bahnhof", text: "Bahnhof: Halle — Information und Fahrkarten; Untergeschoss — Toiletten und Schließfächer; Gleis 1 — Züge nach Köln; Gleis 2 — Züge nach Berlin; Gleis 4 — Ersatzzüge nach München. Fahrräder stehen draußen neben dem Eingang. Gepäck kann in den Schließfächern aufbewahrt werden.", questions: [question("Sie möchten Ihr Gepäck einschließen. Wohin gehen Sie?", "Ins Untergeschoss.", "Zu Gleis 2.", "Zur Fahrradstelle draußen.", "Schließfächer befinden sich im Untergeschoss."), question("Wo bekommen Sie Informationen zu Fahrkarten?", "In der Halle.", "Am Fahrradplatz.", "Nur in den Toiletten.", "Information und Fahrkarten sind in der Halle.")] },
      { title: "Nachricht · Besuch planen", text: "Hallo Mila, ich freue mich auf deinen Besuch am Sonntag. Bitte komm erst um 15 Uhr, denn ich muss vormittags arbeiten. Wir können zusammen kochen. Du brauchst nichts zu essen mitzubringen; ich habe schon eingekauft. Bring bitte das Buch zurück, das ich dir geliehen habe. Meine neue Wohnung ist in der Parkstraße 8, nicht mehr in der Gartenstraße. Ruf kurz an, wenn du an der Haltestelle bist. Ich hole dich dort ab. Liebe Grüße, Lea", questions: [question("Mila soll Essen mitbringen. Richtig oder falsch?", "Falsch.", "Richtig.", "Die Nachricht sagt nichts über Essen.", "Lea hat schon eingekauft; Mila braucht kein Essen mitzubringen."), question("Was soll Mila mitbringen?", "Das geliehene Buch.", "Ein neues Fahrrad.", "Die Fahrkarten für beide.", "Lea bittet um Rückgabe des geliehenen Buchs.")] },
      { title: "Anzeigen · geeignete Angebote", text: "A: Bibliothek — Donnerstag bis 21 Uhr, kostenlose Ausleihe. B: Schreibkurs — Dienstagvormittag, 45 Euro. C: Sportgruppe — Sonntag 10 Uhr, kostenlos, Anmeldung nötig. D: Hotel Park — Zimmer ab 70 Euro, keine Haustiere.", questions: [question("Ben arbeitet tagsüber und möchte Donnerstagabend kostenlos Bücher ausleihen. Was passt?", "A: Bibliothek.", "B: Schreibkurs.", "C: Sportgruppe.", "A erfüllt Zeit, Tätigkeit und Preis."), question("Mila sucht ein Hotelzimmer mit ihrer Katze. Was passt?", "X: Keine Anzeige passt.", "D: Hotel Park.", "A: Bibliothek.", "Das einzige Hotel schließt Haustiere aus.")] },
    ],
    audio: [
      audio("mock-2", 1, "Telefonnotiz · Sprachschule", ["Guten Tag, hier ist Frau Berger. Ihr Beratungsgespräch ist am Mittwoch um neun Uhr vierzig in Raum sechs. Bitte bringen Sie Ihr Kursheft mit. Meine Telefonnummer ist null zwei zwei acht, sieben drei null, eins fünf. Der Kurs beginnt erst nächste Woche. Morgen ist nur die Beratung. Auf Wiederhören."], [question("Wann findet die Beratung statt?", "Mittwoch um 9:40 Uhr.", "Nächste Woche um 6 Uhr.", "Dienstag um 9:40 Uhr.", "Die Nachricht nennt Mittwoch 9:40; der Kurs beginnt erst nächste Woche."), question("Was muss Mila mitbringen?", "Ihr Kursheft.", "Eine Hotelbuchung.", "Einen Koffer.", "Frau Berger bittet ausdrücklich um das Kursheft.")]),
      audio("mock-2", 2, "Wochenplan · freie Zeit", ["Lea, wann können wir lernen?", "Montag arbeite ich lange. Dienstag besuche ich den Schreibkurs.", "Mittwoch habe ich Zeit. Du auch?", "Mittwoch gehe ich zur Beratung. Donnerstag bin ich am Abend in der Bibliothek.", "Dann komme ich Donnerstag auch. Was machst du Freitag?", "Freitag koche ich mit Freunden. Sonntag gehe ich zur Sportgruppe."], [question("Wann möchten beide in der Bibliothek lernen?", "Donnerstagabend.", "Dienstagvormittag.", "Sonntag um 10 Uhr.", "Beide einigen sich auf Donnerstag in der Bibliothek."), question("Was macht Lea am Freitag?", "Sie kocht mit Freunden.", "Sie geht zur Beratung.", "Sie besucht den Schreibkurs.", "Freitag ist Kochen, Mittwoch Beratung, Dienstag Schreibkurs.")]),
      audio("mock-2", 3, "Gespräch · Zimmerbuchung", ["Guten Tag, haben Sie für Sonntag noch ein Zimmer?", "Ja, ein Einzelzimmer für siebzig Euro. Möchten Sie Frühstück?", "Nein, danke. Ich reise mit meiner Katze.", "Das tut mir leid, Haustiere sind bei uns nicht erlaubt.", "Dann kann ich das Zimmer nicht buchen. Wissen Sie ein anderes Hotel?", "Fragen Sie beim Hotel an der Brücke. Dort sind Haustiere nach Absprache möglich."], [question("Warum wird das Zimmer nicht gebucht?", "Weil die Katze nicht mitkommen darf.", "Weil Frühstück verpflichtend ist.", "Weil es kein freies Zimmer gibt.", "Ein Zimmer ist frei, aber Haustiere sind nicht erlaubt.")]),
      audio("mock-2", 4, "Interview · Leas Bibliothek", ["Lea, ist die Ausleihe jetzt teurer?", "Nein, sie bleibt kostenlos. Wir haben nur die Öffnungszeiten geändert.", "Gibt es bis neun Beratung?", "Nein, nur bis sieben. Danach nutzen die Gäste den Automaten.", "Und das Sprachcafé?", "Das ist jeden zweiten Donnerstag. Dafür muss man sich anmelden. Im Winter möchten wir auch einen Schreibtreff anbieten."], [question("Die Ausleihe bleibt kostenlos. Ja oder nein?", "Ja.", "Nein.", "Nur am Sonntag.", "Lea bestätigt die kostenlose Ausleihe."), question("Beratung ist bis 21 Uhr möglich. Ja oder nein?", "Nein.", "Ja.", "Nur im Winter.", "Beratung endet um sieben; danach gibt es die Selbstbedienung.")]),
    ],
    notePrompt: "Notieren Sie aus der Sprachschulnachricht fünf Felder: Tag; Uhrzeit; Raum; mitbringen; Telefonnummer.", noteModel: "Mittwoch; 9:40; Raum 6; Kursheft; 0228 73015",
    formPrompt: "Melden Sie einen Gast an: Nora Klein, wohnt in Bonn, möchte am Sonntag zur Sportgruppe, E-Mail nora@example.com, bringt eine Freundin mit. Ergänzen Sie Nachname; Wohnort; Tag; E-Mail; Zahl der Personen.", formModel: "Klein; Bonn; Sonntag; nora@example.com; 2 Personen",
    smsPrompt: "Sie kommen zu Leas Besuch zu spät. Schreiben Sie 20–30 Wörter: entschuldigen, Grund nennen, neue Ankunftszeit nennen.", smsModel: "Hallo Lea, es tut mir leid, mein Zug hat Verspätung. Ich komme erst um 15:30 Uhr an der Haltestelle an. Kannst du mich dann abholen?",
    emailPrompt: "Schreiben Sie dem Hotel 30–40 Wörter: nach einem Zimmer für Sonntag fragen, Ihre Katze nennen, nach dem Preis fragen.", emailModel: "Sehr geehrte Damen und Herren, ich suche für Sonntag ein Einzelzimmer für eine Nacht. Ich möchte meine Katze mitbringen. Ist das bei Ihnen möglich? Wie viel kostet das Zimmer? Vielen Dank für Ihre Antwort. Mit freundlichen Grüßen Mila Nowak",
    telcPrompt: "Lea lädt Sie am Sonntag ein. Wählen Sie drei von vier Punkten: bedanken; Ankunft bestätigen; Buchrückgabe bestätigen; nach einer Busverbindung fragen. Schreiben Sie etwa 40 Wörter.", telcModel: "Hallo Lea, danke für deine Einladung. Ich komme am Sonntag um 15 Uhr zur Haltestelle und rufe dich dann an. Dein Buch bringe ich natürlich mit. Es hat mir sehr gut gefallen. Ich freue mich auf das gemeinsame Kochen. Liebe Grüße, Mila",
    personalTopic: "Wie lernen Sie Deutsch? Stichwörter: Kurs, zu Hause, andere Menschen, Ziel.", personalModel: "Ich besuche einen Abendkurs. Zu Hause höre ich kurze Nachrichten und schreibe neue Wörter in mein Heft. Donnerstags spreche ich in der Bibliothek mit anderen. Mein Ziel ist, im Alltag sicherer zu werden.",
    calendar: "Planen Sie einen Lerntreff. A: Dienstag frei 9–11 Uhr, Donnerstag frei ab 18 Uhr. B: Dienstag Schreibkurs 9–12 Uhr, Donnerstag frei 18–20 Uhr. Bibliothek Donnerstag bis 21 Uhr offen. Vereinbaren Sie Tag, Zeit, Ort und Material.", calendarModel: "A: Können wir Dienstag lernen? B: Da habe ich einen Kurs. Wie wäre Donnerstag um sechs? A: Gut, die Bibliothek ist offen. B: Ich bringe mein Heft mit. A: Dann treffen wir uns Donnerstag um achtzehn Uhr am Eingang.",
  },
];

export const a2ExamRecordings = a2ExamSets.flatMap((set) => set.audio);
