/** Original supplementary practice for the 18 shared B2 chapters. */
export type B2WorkbookUnit = {
  genre: string;
  text: string;
  question: string;
  answer: string;
  distractors: [string, string];
  explanation: string;
  listeningTask: string;
  listeningModel: string;
  pronunciationFocus: string;
  pronunciationLine: string;
  canDo: string;
  nextStep: string;
};

export const germanB2WorkbookUnits: B2WorkbookUnit[] = [
  {
    genre: "Hinweis einer Sprachschule",
    text: "Ab Oktober bietet das Sprachzentrum einen offenen B2-Lernabend an. Teilnehmende bringen jede Woche einen kurzen Text oder einen Hörbeitrag mit und erklären, welche Aussage ihnen unklar blieb. Die Lehrkraft gibt keine fertige Übersetzung vor, sondern zeigt, wie man Schlüsselwörter, Satzverbindungen und den Zusammenhang prüft. Wer einen Text bereits gut versteht, übernimmt eine andere Aufgabe: eine Position zusammenfassen und begründet hinterfragen. Der Lernabend ersetzt keinen Kurs. Er soll sichtbar machen, welche Strategie beim selbstständigen Lernen hilft und wann Unterstützung nötig ist.",
    question: "Warum bearbeiten die Teilnehmenden nicht alle dieselbe Aufgabe?",
    answer: "Weil sie je nach Lernstand unterschiedliche Strategien erproben sollen.",
    distractors: ["Weil der Lernabend ohne Lehrkraft stattfindet.", "Weil nur fortgeschrittene Teilnehmende Texte mitbringen dürfen."],
    explanation: "Der Hinweis unterscheidet zwischen Klärung offener Stellen und dem Zusammenfassen beziehungsweise Hinterfragen bereits verstandener Texte.",
    listeningTask: "Notieren Sie aus der Ansage den Anlass, die vier Aufgaben der Standortbestimmung und den Grund, warum sie nicht benotet wird.",
    listeningModel: "Die Kursleiterin kündigt eine unbenotete Standortbestimmung mit Lesen, Hören, Schreiben und einem Gespräch an. Sie möchte Stärken und Lernbedarf erkennen.",
    pronunciationFocus: "Sinnabschnitte und Satzakzent bei einer begründeten Aussage",
    pronunciationLine: "Obwohl der Kurs anspruchsvoll ist, möchte ich ihn besuchen; trotzdem plane ich genügend Übungszeit ein.",
    canDo: "Ich kann ein B2-Lernziel begründen und passende Strategien auswählen.",
    nextStep: "Wenn Sie noch unsicher sind: Formulieren Sie ein Ziel, zwei konkrete Übungen und einen Termin zur Überprüfung.",
  },
  {
    genre: "Forumseintrag",
    text: "Als ich in eine neue Stadt zog, wollte ich möglichst schnell Kontakte knüpfen. Zunächst meldete ich mich in mehreren Gruppen an, doch die vielen Nachrichten führten selten zu einem Treffen. Erst in einer ehrenamtlichen Initiative lernte ich Menschen kennen, auf die ich mich verlassen konnte. Wir arbeiteten regelmäßig an derselben Aufgabe und mussten auch unterschiedliche Meinungen aushalten. Trotzdem möchte ich Online-Gruppen nicht abwerten: Ohne sie hätte ich die Initiative gar nicht gefunden. Entscheidend war für mich der Übergang vom ersten Kontakt zu einer gemeinsamen Erfahrung.",
    question: "Welche Rolle spielten die Online-Gruppen für die schreibende Person?",
    answer: "Sie ermöglichten den ersten Kontakt, aus dem erst später eine verlässliche Beziehung wurde.",
    distractors: ["Sie ersetzten dauerhaft jede persönliche Begegnung.", "Sie verhinderten die Teilnahme an der Initiative."],
    explanation: "Der Beitrag würdigt die Gruppen als Zugang, unterscheidet ihn aber vom Aufbau von Vertrauen durch gemeinsame Arbeit.",
    listeningTask: "Halten Sie fest, wo Mara neue Menschen traf, welcher Kontakt dauerhaft wurde und wie sie die Rolle der Online-Gruppen bewertet.",
    listeningModel: "Mara besuchte Veranstaltungen und fand besonders im Chor regelmäßige Begegnungen. Online-Gruppen halfen beim Einstieg; Vertrauen entstand mit der Zeit.",
    pronunciationFocus: "Kontrast zwischen zunächst und erst",
    pronunciationLine: "Online-Gruppen waren zunächst hilfreich; erst durch regelmäßige Treffen entstand Vertrauen.",
    canDo: "Ich kann Beziehungen differenziert beschreiben und einen Gegensatz angemessen ausdrücken.",
    nextStep: "Wenn Sie noch unsicher sind: Erzählen Sie eine persönliche Erfahrung mit zunächst, jedoch und schließlich.",
  },
  {
    genre: "Kolumne einer Stadtteilzeitung",
    text: "Ein Kalender mit festen Terminen verspricht Ordnung. Gleichzeitig berichten viele Menschen, dass gerade die freien Stunden durch zusätzliche Aufgaben gefüllt werden. Ein Nachbarschaftsprojekt testete deshalb einen Abend ohne Programm: Der Raum war geöffnet, aber niemand musste an einer Aktivität teilnehmen. Einige fanden die fehlende Planung zunächst befremdlich; andere nutzten die Zeit für spontane Gespräche. Nach vier Wochen entschied das Team, einen Teil der Treffen weiterhin offen zu lassen. Der Versuch beweist nicht, dass Planung schadet. Er zeigt jedoch, dass Begegnungen manchmal Raum brauchen, der keinem festen Zweck dient.",
    question: "Welche Schlussfolgerung zieht die Kolumne aus dem Versuch?",
    answer: "Offene Zeit kann Begegnungen fördern, ohne geplante Angebote grundsätzlich abzuwerten.",
    distractors: ["Alle festen Termine sollten abgeschafft werden.", "Spontane Gespräche fanden trotz des offenen Raums nicht statt."],
    explanation: "Der Text schränkt die Aussage ausdrücklich ein und empfiehlt nur, einen Teil der Treffen offen zu lassen.",
    listeningTask: "Notieren Sie, was Nils durch die Vier-Tage-Woche gewann, welches Problem zunächst entstand und warum seine Kollegin ein anderes Modell bevorzugt.",
    listeningModel: "Nils gewann Zeit für seine Familie. Zunächst drängte er fünf Tage Arbeit in vier; erst eine neue Aufgabenverteilung half. Seine Kollegin findet vier lange Tage wegen der Kinderbetreuung zu anstrengend.",
    pronunciationFocus: "Vergleich und Einschränkung hörbar markieren",
    pronunciationLine: "Je voller der Kalender wird, desto wichtiger sind freie Zeiten; allerdings braucht nicht jeder Mensch denselben Rhythmus.",
    canDo: "Ich kann Lebensweisen vergleichen und eine vorsichtige Schlussfolgerung formulieren.",
    nextStep: "Wenn Sie noch unsicher sind: Beschreiben Sie zwei Alltagsmodelle mit je … desto und einer Einschränkung.",
  },
  {
    genre: "Protokollauszug einer Bürgerversammlung",
    text: "Der Stadtrat prüft, ob ein leer stehendes Gebäude als Treffpunkt genutzt werden kann. In der Versammlung begrüßten mehrere Vereine die Idee, weil ihnen bezahlbare Räume fehlen. Anwohnende fragten dagegen nach Lärm, Barrierefreiheit und den laufenden Kosten. Die Verwaltung versprach keine sofortige Eröffnung. Zuerst soll eine sechsmonatige Testphase mit wenigen Angeboten stattfinden. Währenddessen werden Besucherzahlen und Beschwerden erfasst. Erst danach soll entschieden werden, ob ein dauerhafter Umbau sinnvoll ist. Eine Sprecherin bat darum, auch Menschen einzuladen, die bisher selten an solchen Treffen teilnehmen.",
    question: "Warum ist die Testphase für die Entscheidung wichtig?",
    answer: "Sie liefert Erfahrungen und Daten zu Nutzung und möglichen Problemen.",
    distractors: ["Sie ersetzt die Entscheidung über einen dauerhaften Umbau bereits.", "Sie dient ausschließlich dazu, Vereinen zusätzliche Räume zu versprechen."],
    explanation: "Der Text trennt Vorschlag, Test und spätere Entscheidung und nennt Besucherzahlen sowie Beschwerden als Grundlage.",
    listeningTask: "Notieren Sie die zwei geplanten Nutzungen des alten Bahnhofs, eine Verkehrsfrage und die beiden vorgeschlagenen Tageszeiten für Vereinsangebote.",
    listeningModel: "Oben sind Wohnungen, unten Vereinsräume geplant. Die Busverbindungen werden geprüft. Manche Vereine brauchen Abendräume, andere Angebote am Nachmittag.",
    pronunciationFocus: "Passivformen und betonte Zeitfolge",
    pronunciationLine: "Zuerst wird das Erdgeschoss geöffnet; erst danach wird über den vollständigen Umbau entschieden.",
    canDo: "Ich kann Vorschläge, Einwände und offene Fragen in einer Debatte zusammenfassen.",
    nextStep: "Wenn Sie noch unsicher sind: Ordnen Sie in drei Sätzen Bedarf, Risiko und nächsten Prüfschritt.",
  },
  {
    genre: "Ratgeberantwort",
    text: "Eine Leserin fragt, ob sie wegen ihrer Arbeit auf jede Pause verzichten müsse. Unsere Antwort kann ihre konkrete Situation nicht beurteilen. Hilfreich wäre jedoch, mit der Teamleitung über kurze, planbare Unterbrechungen zu sprechen. Eine Pause von wenigen Minuten löst keine dauerhafte Überlastung; sie kann aber helfen, die nächste Aufgabe konzentrierter zu beginnen. Wenn regelmäßige Pausen nicht möglich sind, sollte auch die Verteilung der Arbeit geprüft werden. Wer gesundheitliche Beschwerden hat, braucht eine persönliche fachliche Einschätzung statt allgemeiner Tipps aus einer Zeitschrift.",
    question: "Welche Grenze der Empfehlung wird ausdrücklich genannt?",
    answer: "Kurze Pausen ersetzen weder eine Prüfung der Arbeitsbelastung noch fachlichen Rat bei Beschwerden.",
    distractors: ["Pausen sind bei jeder Tätigkeit schädlich.", "Nur die Leserin selbst ist für die gesamte Aufgabenverteilung verantwortlich."],
    explanation: "Die Antwort unterscheidet eine kleine Gewohnheit von strukturellen Arbeitsbedingungen und individueller Gesundheitsberatung.",
    listeningTask: "Notieren Sie die Empfehlung der Beraterin, eine Bedingung für ihre Umsetzung und eine Grenze des Ratschlags.",
    listeningModel: "Die Beraterin empfiehlt kurze bewusste Pausen, sofern die Arbeitsabläufe sie erlauben. Bei dauerhafter Überlastung muss die Aufgabenverteilung betrachtet werden.",
    pronunciationFocus: "Höfliche Empfehlung statt Befehl",
    pronunciationLine: "Es wäre sinnvoll, eine kurze Pause einzuplanen, sofern die Arbeitssituation das zulässt.",
    canDo: "Ich kann vorsichtig beraten und zwischen allgemeinem Tipp und individueller Situation unterscheiden.",
    nextStep: "Wenn Sie noch unsicher sind: Formulieren Sie einen Rat mit könnte, einer Bedingung und einer Einschränkung.",
  },
  {
    genre: "Kursbeschreibung",
    text: "Die Lernwerkstatt richtet sich an Erwachsene mit sehr unterschiedlichen Vorkenntnissen. Ein gemeinsamer Einstieg erklärt das digitale Anmeldeverfahren; danach wählen die Teilnehmenden ein persönliches Ziel. Wer eine Bewerbung vorbereiten möchte, arbeitet mit anderen Materialien als jemand, der Nachrichten aus seiner Gemeinde besser verstehen will. Die Treffen finden abwechselnd am Nachmittag und am Abend statt. So können auch Berufstätige teilnehmen, ohne regelmäßig frei nehmen zu müssen. Nach vier Wochen bespricht jede Person mit einer Lernbegleitung, welche Aufgabe sie bereits selbstständig lösen kann und wobei sie noch Unterstützung benötigt.",
    question: "Woran orientiert sich die Auswahl der Materialien?",
    answer: "Am persönlichen Ziel und an den Vorkenntnissen der einzelnen Teilnehmenden.",
    distractors: ["Ausschließlich am Alter der Teilnehmenden.", "An einer einzigen verpflichtenden Prüfung für alle."],
    explanation: "Der gemeinsame Einstieg wird von individuell gewählten Zielen und Materialien unterschieden.",
    listeningTask: "Halten Sie Dauer, Lernformen, Einstiegshilfe und die erwartete Vorbereitung vor der Anmeldung fest.",
    listeningModel: "Die Weiterbildung dauert zwölf Wochen, bietet Präsenz- und Onlinephasen sowie eine Einführung. Interessierte sollen vorher ein konkretes Lernziel überlegen.",
    pronunciationFocus: "Zwecksatz und Nebeninformation gliedern",
    pronunciationLine: "Viele besuchen einen Kurs, um sich weiterzuentwickeln, ohne ihre Arbeit aufzugeben.",
    canDo: "Ich kann Bildungsangebote vergleichen und einen passenden Lernweg begründen.",
    nextStep: "Wenn Sie noch unsicher sind: Vergleichen Sie zwei Angebote nach Zugang, Zeit und Lernziel.",
  },
  {
    genre: "Auszug aus einer Stellenanzeige",
    text: "Ein Kulturzentrum sucht eine Person für die Organisation von Veranstaltungen. Neben Erfahrung mit digitaler Planung sind klare schriftliche Absprachen wichtig. Die Stelle umfasst auch Abendtermine, die frühzeitig im Team verteilt werden. Bewerbende sollen in einem kurzen Schreiben ein konkretes Beispiel für Zusammenarbeit nennen. Ein Lebenslauf ohne Bezug zur ausgeschriebenen Aufgabe genügt nicht. Das Zentrum weist darauf hin, dass fehlende Erfahrung in einem Bereich durch nachweisbare Lernbereitschaft ausgeglichen werden kann. Fragen zu Arbeitszeit und Aufgaben dürfen vor der Bewerbung gestellt werden.",
    question: "Welche Bewerbung würde zur Anzeige am besten passen?",
    answer: "Ein Schreiben mit einem konkreten Teambeispiel und Bezug zu den Aufgaben.",
    distractors: ["Ein unveränderter Lebenslauf ohne Anschreiben oder Beispiel.", "Eine Bewerbung, die die Abendtermine als nicht vorhanden behandelt."],
    explanation: "Die Anzeige verlangt ein konkretes Beispiel und einen erkennbaren Bezug zur Stelle.",
    listeningTask: "Notieren Sie die gewünschte Änderung am Dienstag, das Angebot für Donnerstag und die zwei Schritte, die Frau Berger danach verlangt.",
    listeningModel: "Die Person möchte am Dienstag erst um zehn beginnen und am Donnerstag länger bleiben. Sie soll eine E-Mail schicken und das Team über ihre Erreichbarkeit informieren.",
    pronunciationFocus: "Höfliche Bitte mit fallender Satzmelodie",
    pronunciationLine: "Könnten Sie mir bitte bestätigen, wann der aktualisierte Dienstplan vorliegt?",
    canDo: "Ich kann berufliche Anforderungen erkennen und ein Anliegen höflich formulieren.",
    nextStep: "Wenn Sie noch unsicher sind: Markieren Sie in einer Anzeige Aufgabe, Bedingung und nachweisbares Beispiel.",
  },
  {
    genre: "Verbraucherkommentar",
    text: "Der neue Wasserkocher kostet weniger als vergleichbare Geräte. Nach sechs Monaten berichtet eine Käuferin jedoch, dass ein kleines Ersatzteil nicht erhältlich sei. Ein anderer Kunde lobt den niedrigen Stromverbrauch, hat aber noch keine Erfahrung mit einer Reparatur. Das Geschäft verweist auf die Garantie und will künftig Ersatzteile länger anbieten. Aus diesen Stimmen lässt sich keine allgemeine Aussage über alle Geräte ableiten. Für eine Entscheidung sollten Interessierte Anschaffungspreis, laufende Kosten, Reparierbarkeit und die Zuverlässigkeit der Bewertungen getrennt prüfen.",
    question: "Warum reicht der niedrige Preis laut Kommentar nicht für eine Kaufentscheidung?",
    answer: "Weil auch laufende Kosten, Reparatur und die Aussagekraft der Bewertungen wichtig sind.",
    distractors: ["Weil das Gerät nachweislich bei allen Kunden ausfällt.", "Weil Stromverbrauch grundsätzlich keine Rolle spielt."],
    explanation: "Der Kommentar vergleicht mehrere Kriterien und warnt vor einer Verallgemeinerung einzelner Erfahrungen.",
    listeningTask: "Vergleichen Sie die zwei Fahrrad-Abos nach Monatspreis und Reparaturbedingungen. Notieren Sie außerdem die Frage zur Kündigung.",
    listeningModel: "Das erste Abo ist monatlich günstiger, kann bei Schäden aber hohe Gebühren auslösen. Das zweite enthält kleinere Reparaturen. Auch die Kündigungsfrist sollte geprüft werden.",
    pronunciationFocus: "Aufzählung mit klarem Schlussakzent",
    pronunciationLine: "Ich prüfe den Preis, die laufenden Kosten und vor allem die Reparierbarkeit.",
    canDo: "Ich kann Informationen zu einem Kauf kritisch gewichten und eine Entscheidung begründen.",
    nextStep: "Wenn Sie noch unsicher sind: Nennen Sie drei Kriterien und erklären Sie, welches für Sie entscheidend ist.",
  },
  {
    genre: "Reiseinformation",
    text: "Wegen Bauarbeiten fährt der Regionalzug am Wochenende nur bis Neustadt. Reisende nach Lindenfeld steigen dort in einen Ersatzbus um. Die planmäßige Ankunft verschiebt sich um etwa 25 Minuten; bei starkem Verkehr kann es länger dauern. Fahrräder können im Ersatzbus nur mitgenommen werden, wenn Platz vorhanden ist. Wer einen Anschlusszug erreichen muss, sollte die Verbindung am Reisetag noch einmal prüfen. Das Verkehrsunternehmen bittet darum, für wichtige Termine eine frühere Abfahrt in Betracht zu ziehen, und veröffentlicht Änderungen in seiner App.",
    question: "Welcher Hinweis ist für eine Person mit festem Anschlusstermin besonders wichtig?",
    answer: "Sie sollte die aktuelle Verbindung prüfen und gegebenenfalls früher abfahren.",
    distractors: ["Sie kann sich auf die ursprüngliche Ankunftszeit verlassen.", "Sie muss ihr Fahrrad unabhängig vom verfügbaren Platz mitnehmen."],
    explanation: "Die Ankunft ist nur ungefähr angegeben; zusätzlicher Verkehr kann die Fahrt weiter verzögern.",
    listeningTask: "Notieren Sie Endbahnhof des Zugs, Abfahrtsort des Ersatzbusses, zusätzliche Reisezeit und die Alternative für den Anschluss nach Bremerhaven.",
    listeningModel: "Der Zug endet in Verden. Der Ersatzbus fährt vor dem Haupteingang ab und braucht etwa 35 Minuten länger. Für Bremerhaven gibt es eine Route über Hannover.",
    pronunciationFocus: "Bedingung und Folge trennen",
    pronunciationLine: "Falls der Anschluss knapp wird, prüfe ich eine frühere Verbindung und informiere meine Mitreisenden.",
    canDo: "Ich kann Reisehinweise auswerten und Alternativen unter Bedingungen empfehlen.",
    nextStep: "Wenn Sie noch unsicher sind: Fassen Sie Änderung, Risiko und Alternative in drei Sätzen zusammen.",
  },
  {
    genre: "Kommentar zu digitalem Lernen",
    text: "Eine Schule testet ein digitales Werkzeug für das Schreiben. Einige Lernende erhalten schneller Rückmeldungen; andere übernehmen Vorschläge, ohne sie zu verstehen. Die Lehrkräfte vergleichen deshalb nicht nur fertige Texte, sondern lassen die Schülerinnen und Schüler erklären, welche Änderung sie selbst vorgenommen haben. Zusätzlich prüft die Schule, ob alle zu Hause Zugang zu einem geeigneten Gerät haben. Der Versuch wird erst am Ende des Halbjahres ausgewertet. Bis dahin wäre sowohl ein pauschales Verbot als auch eine dauerhafte Einführung voreilig.",
    question: "Warum bewertet die Schule nicht allein die fertigen Texte?",
    answer: "Weil sie verstehen möchte, ob Lernende die vorgeschlagenen Änderungen selbst nachvollziehen können.",
    distractors: ["Weil schriftliche Texte im Versuch überhaupt nicht vorkommen.", "Weil alle Lernenden bereits dieselben digitalen Möglichkeiten haben."],
    explanation: "Der Kommentar betont Lernprozess und Zugang als zwei Bedingungen der Auswertung.",
    listeningTask: "Notieren Sie einen Nutzen digitaler Werkzeuge, zwei Bedenken und die Bedingung für eine dauerhafte Entscheidung.",
    listeningModel: "Digitale Werkzeuge können helfen; Quellenprüfung, Datenschutz und fairer Zugang müssen jedoch vor einer dauerhaften Einführung geklärt werden.",
    pronunciationFocus: "Gegensatz durch Akzent sichtbar machen",
    pronunciationLine: "Einerseits erleichtert das Werkzeug die Arbeit; andererseits müssen wir seine Vorschläge prüfen.",
    canDo: "Ich kann Chancen und Risiken digitaler Angebote abwägen und eine bedingte Position vertreten.",
    nextStep: "Wenn Sie noch unsicher sind: Begründen Sie eine Position mit einerseits, andererseits und sofern.",
  },
  {
    genre: "Korrektur einer Lokalredaktion",
    text: "In unserem gestrigen Bericht stand, das neue Kulturhaus werde im Frühjahr eröffnet. Diese Formulierung war zu eindeutig. Die Stadtverwaltung hat bislang nur angekündigt, im Frühjahr über eine mögliche Testöffnung zu entscheiden. Auch die genannten Kosten sind Schätzungen, keine bewilligten Ausgaben. Wir haben die Überschrift geändert und die ursprüngliche Fassung dokumentiert. Für die Verwechslung von Entscheidung und Planung entschuldigen wir uns. Leserinnen und Leser finden die Stellungnahme der Stadt sowie den Beschlussentwurf über die verlinkten Originalquellen.",
    question: "Welchen Fehler korrigiert die Redaktion vor allem?",
    answer: "Sie hatte eine noch offene Entscheidung als feststehende Eröffnung dargestellt.",
    distractors: ["Sie hatte eine bereits erfolgte Eröffnung übersehen.", "Sie hatte alle Originalquellen vollständig gelöscht."],
    explanation: "Die Korrektur trennt Ankündigung, künftige Entscheidung und tatsächliche Eröffnung.",
    listeningTask: "Halten Sie Schließzeit, Ort der Rückgabe und die Einschränkung für neue Bestellungen fest. Markieren Sie zwei Formen der indirekten Rede.",
    listeningModel: "Die Bibliothek bleibt vom dritten bis zum siebzehnten Mai geschlossen. Rückgaben sind im Ausweichraum möglich, neue Bestellungen nur eingeschränkt; die Meldung nutzt etwa bleibe und könnten.",
    pronunciationFocus: "Distanz zur Quelle durch Sprechpause markieren",
    pronunciationLine: "Die Redaktion berichtet, das Haus werde eröffnet; die Stadt sagt jedoch, eine Entscheidung stehe noch aus.",
    canDo: "Ich kann Behauptung, Quelle und gesicherten Sachstand voneinander unterscheiden.",
    nextStep: "Wenn Sie noch unsicher sind: Vergleichen Sie eine Überschrift mit der Originalquelle und formulieren Sie eine präzise Korrektur.",
  },
  {
    genre: "Auszug aus einem kommunalen Projektbericht",
    text: "Eine Gemeinde möchte öffentliche Gebäude energiesparender nutzen. Drei Schulen wurden bereits untersucht. Für zwei Häuser lohnt sich nach erster Einschätzung eine bessere Dämmung; beim dritten wäre zunächst die Heizungssteuerung zu prüfen. Die Verwaltung weist darauf hin, dass Einsparungen nur geschätzt sind und vom tatsächlichen Betrieb abhängen. Ein schneller Austausch aller Anlagen könnte deshalb Geld binden, ohne die Ursachen des hohen Verbrauchs zu klären. Vor einer Ausschreibung sollen Messdaten über mehrere Monate gesammelt und mit den Nutzenden besprochen werden.",
    question: "Warum wird nicht sofort jede Anlage ausgetauscht?",
    answer: "Weil zuerst Ursachen und belastbare Verbrauchsdaten ermittelt werden sollen.",
    distractors: ["Weil die Gemeinde grundsätzlich keine Energie sparen möchte.", "Weil bei allen Gebäuden bereits dieselbe Ursache feststeht."],
    explanation: "Der Bericht unterscheidet Schätzungen und gemessene Daten sowie unterschiedliche Maßnahmen für verschiedene Gebäude.",
    listeningTask: "Vergleichen Sie Fahrradwerkstatt, Baumpflanzung und Tauschregal nach Voraussetzung. Notieren Sie die zwei Kriterien jenseits des Preises.",
    listeningModel: "Die Werkstatt kann bald beginnen, für Bäume fehlt eine Genehmigung und das Tauschregal braucht dauerhafte Betreuung. Personal und langfristige Wirkung sind ebenfalls wichtig.",
    pronunciationFocus: "Ursache und Folge klar verbinden",
    pronunciationLine: "Erst wenn die Verbrauchsdaten vorliegen, lässt sich die wirksamste Maßnahme bestimmen.",
    canDo: "Ich kann Umweltmaßnahmen anhand von Belegen und Unsicherheiten bewerten.",
    nextStep: "Wenn Sie noch unsicher sind: Trennen Sie in einer Empfehlung Beobachtung, Vermutung und nächsten Prüfschritt.",
  },
  {
    genre: "Rezension einer Ausstellung",
    text: "Die Ausstellung zeigt Fotografien aus einem Stadtteil, der sich in den vergangenen Jahrzehnten stark verändert hat. Besonders überzeugend sind die kurzen Berichte älterer Bewohnerinnen und Bewohner: Sie widersprechen der Vorstellung, früher sei alles einfacher gewesen. Einige Bilder bleiben jedoch ohne genaue Datierung, sodass Besucher die Veränderungen schwer einordnen können. Ein Zeitstrahl hätte geholfen. Trotz dieser Schwäche regt die Ausstellung zum Gespräch darüber an, wessen Erinnerungen in der Stadtgeschichte sichtbar werden. Wer sich für persönliche Perspektiven interessiert, wird hier mehr finden als eine reine Chronik.",
    question: "Wie lautet das Urteil der Rezension?",
    answer: "Die Ausstellung ist anregend, obwohl Informationen zur zeitlichen Einordnung fehlen.",
    distractors: ["Die Ausstellung ist wegen der Fotografien vollständig wertlos.", "Die Rezension lobt ausschließlich die genaue Datierung aller Bilder."],
    explanation: "Die Rezension nennt eine konkrete Stärke und eine konkrete Schwäche, bevor sie ein eingeschränkt positives Urteil formuliert.",
    listeningTask: "Notieren Sie zwei Stärken des Films, die ausgelassene Frage und das insgesamt formulierte Urteil.",
    listeningModel: "Offene Interviews und sorgfältige Bilder sind Stärken. Die Finanzierung bleibt zu knapp erklärt. Trotzdem empfiehlt die Kritikerin den Film wegen des Blicks hinter die Bühne.",
    pronunciationFocus: "Bewertung und Vorbehalt unterschiedlich betonen",
    pronunciationLine: "Die Stimmen sind beeindruckend; allerdings fehlen bei einigen Bildern genaue Daten.",
    canDo: "Ich kann ein Kulturangebot ausgewogen besprechen und mein Urteil begründen.",
    nextStep: "Wenn Sie noch unsicher sind: Schreiben Sie eine Stärke, eine Schwäche und eine Empfehlung für eine bestimmte Zielgruppe.",
  },
  {
    genre: "Zwei Stimmen aus einer Stadtteildebatte",
    text: "Eine Initiative fordert längere Öffnungszeiten der Bibliothek. Berufstätige könnten dann auch am Sonntag lernen. Die Beschäftigtenvertretung erinnert daran, dass zusätzliche Stunden Personal und verlässliche Dienstpläne erfordern. Beide Seiten erkennen den Wert eines öffentlichen Lernorts an. Sie streiten nicht darüber, ob die Bibliothek wichtig ist, sondern darüber, unter welchen Bedingungen sie länger geöffnet sein kann. Ein Vorschlag sieht eine freiwillige dreimonatige Testphase vor. Anschließend sollen Besucherzahlen, Kosten und Rückmeldungen der Mitarbeitenden ausgewertet werden.",
    question: "Welcher gemeinsame Ausgangspunkt verbindet die beiden Positionen?",
    answer: "Beide halten die Bibliothek für einen wichtigen öffentlichen Lernort.",
    distractors: ["Beide verlangen eine dauerhafte Sonntagsöffnung ohne Prüfung.", "Beide lehnen jede Veränderung der Öffnungszeiten ab."],
    explanation: "Der Text benennt den gemeinsamen Wert und zeigt erst danach die unterschiedlichen Bedingungen.",
    listeningTask: "Notieren Sie die grundsätzliche Haltung der Geschäftsleute, ihr Problem während der Bauzeit und den vorgeschlagenen Bauablauf.",
    listeningModel: "Die Geschäftsleute unterstützen mehr Grün, wollen aber erreichbare Läden. Sie schlagen einen Umbau in zwei Abschnitten mit offenem Zugang vor.",
    pronunciationFocus: "Zugeständnis vor dem eigenen Einwand",
    pronunciationLine: "Ihr Wunsch nach mehr Lernzeit ist berechtigt; dennoch müssen wir die Arbeitsbedingungen berücksichtigen.",
    canDo: "Ich kann unterschiedliche gesellschaftliche Positionen fair vermitteln.",
    nextStep: "Wenn Sie noch unsicher sind: Fassen Sie zuerst die andere Position korrekt zusammen und nennen Sie dann Ihren Einwand.",
  },
  {
    genre: "Leserbrief",
    text: "Sehr geehrte Redaktion, die Stadt plant neue Sitzplätze auf dem Marktplatz. Das Vorhaben könnte Begegnungen fördern, doch die bisherige Darstellung übergeht Menschen, die den Platz beruflich nutzen. Lieferdienste benötigen kurze Ladezeiten, und Marktstände brauchen morgens freien Zugang. Ich schlage daher vor, die Anordnung zunächst für drei Monate zu testen und die Betroffenen nach konkreten Erfahrungen zu fragen. Mein Einwand richtet sich nicht gegen zusätzliche Sitzplätze. Er betrifft die Annahme, dass dieselbe Lösung zu jeder Tageszeit für alle passt. Mit freundlichen Grüßen, A. Yilmaz",
    question: "Wie vermeidet der Leserbrief einen falschen Gegensatz?",
    answer: "Er unterstützt das Ziel grundsätzlich, verlangt aber einen Test unter verschiedenen Nutzungsbedingungen.",
    distractors: ["Er lehnt Sitzplätze ohne Begründung vollständig ab.", "Er behauptet, Lieferdienste sollten allein über den Platz entscheiden."],
    explanation: "Der Brief trennt Ziel und konkrete Umsetzung und schlägt eine überprüfbare Alternative vor.",
    listeningTask: "Halten Sie den Wunsch nach Sonntagslernen, den Einwand zu Beschäftigten und den Kompromissvorschlag mit Auswertung fest.",
    listeningModel: "Der Sprecher versteht den Lernbedarf, fordert aber die Beteiligung der Beschäftigten. Ein betreuter Lernraum könnte drei Monate getestet werden.",
    pronunciationFocus: "Einwand freundlich einleiten",
    pronunciationLine: "Ich verstehe Ihren Punkt; gleichzeitig sollten wir die Folgen für andere Gruppen prüfen.",
    canDo: "Ich kann eine Position vertreten, einen Einwand anerkennen und einen Kompromiss anbieten.",
    nextStep: "Wenn Sie noch unsicher sind: Formulieren Sie ein Argument mit Zugeständnis, Begründung und Lösungsvorschlag.",
  },
  {
    genre: "Antwort eines Kundendienstes",
    text: "Sehr geehrte Frau Kaya, vielen Dank für Ihre Nachricht vom 12. Mai. Sie haben beschrieben, dass der Veranstaltungsort nach Ihrer Buchung geändert wurde und die neue Adresse für Sie schwer erreichbar ist. Wir bedauern, dass Sie diese Information erst kurz vor dem Termin erhalten haben. Sie können an einem Ersatztermin am bisherigen Ort teilnehmen oder eine Erstattung beantragen. Bitte teilen Sie uns bis Freitag mit, welche Lösung Sie bevorzugen. Falls keine der beiden Möglichkeiten passt, prüfen wir Ihren Fall gern individuell. Mit freundlichen Grüßen, das Serviceteam",
    question: "Welche Eigenschaft macht die Antwort besonders hilfreich?",
    answer: "Sie greift das konkrete Problem auf und nennt zwei umsetzbare Lösungen mit Frist.",
    distractors: ["Sie bestreitet die Änderung des Veranstaltungsorts.", "Sie fordert eine Entscheidung, ohne Optionen zu erklären."],
    explanation: "Die Antwort bestätigt Anlass und Folge, übernimmt Verantwortung und macht das weitere Vorgehen klar.",
    listeningTask: "Notieren Sie die beiden angebotenen Lösungen, die Antwortfrist und eine Veränderung, die das Team für künftige Mitteilungen ankündigt.",
    listeningModel: "Das Team bietet einen Ersatztermin am ursprünglichen Ort oder Erstattung. Die Kundin soll bis Mittwoch antworten; Änderungen sollen künftig früher mitgeteilt werden.",
    pronunciationFocus: "Sachliche Bitte und Rückfrage",
    pronunciationLine: "Könnten Sie mir bitte mitteilen, welche Alternative Sie anbieten können?",
    canDo: "Ich kann eine formelle Nachricht klar gliedern und eine konkrete Lösung erbitten.",
    nextStep: "Wenn Sie noch unsicher sind: Ordnen Sie Anlass, Folge, Bitte und Frist in vier kurzen Abschnitten.",
  },
  {
    genre: "Tagesordnung einer Projektgruppe",
    text: "Die Projektgruppe plant ein öffentliches Lernangebot. Für die Sitzung sind drei Punkte vorgesehen: Erstens soll die Zielgruppe genauer beschrieben werden. Zweitens werden zwei mögliche Orte nach Erreichbarkeit und Kosten verglichen. Drittens muss entschieden werden, wer die Einladung vorbereitet. Die Leitung bittet darum, zu jedem Punkt eine begründete Empfehlung und mindestens eine offene Frage mitzubringen. Eine lange Präsentation ist nicht nötig. Am Ende der Sitzung sollen Zuständigkeiten, ein Testtermin und Kriterien für die Auswertung feststehen.",
    question: "Was soll am Ende der Sitzung konkret vorliegen?",
    answer: "Eine Entscheidung zu Aufgaben, Testtermin und Auswertungskriterien.",
    distractors: ["Ein vollständig ausgearbeiteter Vortrag jeder teilnehmenden Person.", "Nur eine Liste von Ideen ohne Zuständigkeiten."],
    explanation: "Die Tagesordnung unterscheidet Vorbereitung, Diskussion und verbindliches Ergebnis.",
    listeningTask: "Notieren Sie den vorgeschlagenen Termin, den Kosteneinwand und den angebotenen Kompromiss. Halten Sie auch die offene Rückfrage fest.",
    listeningModel: "Ein Termin am frühen Abend soll Berufstätigen helfen. Wegen der Raumkosten wird ein zweiwöchentlicher Rhythmus vorgeschlagen; die Gruppe soll sagen, ob er passt.",
    pronunciationFocus: "Gliederungssignale und kurze Pausen",
    pronunciationLine: "Zunächst stelle ich zwei Möglichkeiten vor. Anschließend vergleiche ich sie. Zum Schluss begründe ich meine Empfehlung.",
    canDo: "Ich kann einen Kurzvortrag strukturieren und in einer Gruppe Entscheidungen aushandeln.",
    nextStep: "Wenn Sie noch unsicher sind: Sprechen Sie 90 Sekunden mit Einleitung, zwei Kriterien und einem klaren Schluss.",
  },
  {
    genre: "Kurznotiz für einen Entscheidungsausschuss",
    text: "Für das geplante Begegnungszentrum liegen ein Verwaltungsbericht, Rückmeldungen von Vereinen und Aussagen aus der Nachbarschaft vor. Die Quellen stimmen darin überein, dass bezahlbare Räume fehlen. Uneinigkeit besteht bei Kosten und zusätzlichem Verkehr; dazu fehlen noch belastbare Daten. Die Kurznotiz empfiehlt deshalb, zunächst nur das Erdgeschoss zu öffnen. Für sechs Monate sollen Nutzung, tatsächliche Ausgaben und Beschwerden dokumentiert werden. Danach kann der Ausschuss entscheiden, ob ein größerer Umbau gerechtfertigt ist. Die Empfehlung ist bewusst vorläufig, weil die Quellen unterschiedliche Interessen und Wissensstände abbilden.",
    question: "Warum ist die Empfehlung ausdrücklich vorläufig?",
    answer: "Weil wichtige Daten fehlen und die vorhandenen Quellen unterschiedliche Perspektiven vertreten.",
    distractors: ["Weil alle Beteiligten das Projekt bereits endgültig abgelehnt haben.", "Weil die Ausgaben schon vollständig bekannt sind."],
    explanation: "Die Notiz verbindet einen gemeinsamen Befund mit ungeklärten Kosten und Folgen.",
    listeningTask: "Notieren Sie den Bedarf der Vereine, die Verkehrssorge und zwei Maßnahmen, mit denen während der Testphase nachgesteuert werden soll.",
    listeningModel: "Vereine brauchen Räume auch am Abend, Anwohnende fürchten Verkehr. Große Veranstaltungen sollen angekündigt und begrenzt, Rückmeldungen monatlich gesammelt werden.",
    pronunciationFocus: "Vorläufige Empfehlung statt Gewissheit",
    pronunciationLine: "Auf Grundlage der bisherigen Angaben würde ich zunächst eine begrenzte Testphase empfehlen.",
    canDo: "Ich kann mehrere Quellen zusammenführen und eine begründete, vorsichtige Empfehlung geben.",
    nextStep: "Wenn Sie noch unsicher sind: Trennen Sie gesicherte Befunde, offene Fragen und Ihre vorläufige Empfehlung.",
  },
];
