/** Lexical depth for each B2 chapter: topic terms, function, word family and register. */
export type B2Lexicon = {
  terms: Array<[string, string]>;
  functionPhrase: string;
  discussionPhrase: string;
  wordFamily: [string, string, string];
  register: [string, string, string];
};

export const germanB2Lexicon: B2Lexicon[] = [
  { terms: [["die Standortbestimmung", "Einschätzung des aktuellen Lernstands"], ["die Rückmeldung", "Information über Stärken und Verbesserungsmöglichkeiten"], ["die Lernstrategie", "bewusste Methode zum Lernen"], ["die Selbstkorrektur", "eigenständige Verbesserung"], ["der Fortschritt", "sichtbare Entwicklung"]], functionPhrase: "Mein nächstes Ziel besteht darin, …", discussionPhrase: "Dabei möchte ich besonders darauf achten, dass …", wordFamily: ["lernen", "das Lernen", "lernförderlich"], register: ["etwas hinkriegen", "etwas schaffen", "eine Aufgabe bewältigen"] },
  { terms: [["die Verlässlichkeit", "Eigenschaft, auf jemanden zählen zu können"], ["die Verbundenheit", "Gefühl gegenseitiger Nähe"], ["die Erwartung", "Vorstellung davon, was geschehen soll"], ["das Vertrauen", "Zuversicht gegenüber einer Person"], ["die Begegnung", "persönliches Zusammentreffen"]], functionPhrase: "Für eine gelungene Beziehung ist entscheidend, dass …", discussionPhrase: "Ich kann diese Sicht nachvollziehen; zugleich …", wordFamily: ["vertrauen", "das Vertrauen", "vertrauenswürdig"], register: ["mit jemandem klarkommen", "sich gut verstehen", "eine tragfähige Beziehung pflegen"] },
  { terms: [["die Erreichbarkeit", "Möglichkeit, kontaktiert zu werden"], ["die Vereinbarkeit", "Möglichkeit, Anforderungen zu verbinden"], ["die Gewohnheit", "regelmäßig wiederholtes Verhalten"], ["die Belastung", "körperlicher oder psychischer Druck"], ["die Priorität", "besonders wichtiges Ziel"]], functionPhrase: "Je …, desto …", discussionPhrase: "Ein Vorteil liegt darin, dass …; dem steht entgegen, dass …", wordFamily: ["verändern", "die Veränderung", "veränderlich"], register: ["keine Zeit haben", "zeitlich eingeschränkt sein", "über begrenzte zeitliche Ressourcen verfügen"] },
  { terms: [["der Wohnraum", "Fläche zum Wohnen"], ["die Nachverdichtung", "Bauen innerhalb eines bestehenden Stadtgebiets"], ["die Verdrängung", "Wegzug wegen steigender Kosten"], ["die Barrierefreiheit", "Zugänglichkeit ohne bauliche Hindernisse"], ["die Infrastruktur", "Verkehrswege und öffentliche Einrichtungen"]], functionPhrase: "Aus Sicht der Anwohnenden wäre wichtig, dass …", discussionPhrase: "Diese Maßnahme könnte zwar …, allerdings …", wordFamily: ["wohnen", "die Wohnung", "wohnlich"], register: ["eine Wohnung kriegen", "eine Wohnung finden", "Wohnraum erhalten"] },
  { terms: [["die Vorsorge", "Maßnahmen zur Vorbeugung"], ["die Überlastung", "zu hohe Beanspruchung"], ["die Erholung", "Wiedergewinnung von Kraft"], ["die Gewohnheitsänderung", "bewusste Veränderung einer Routine"], ["die Beratung", "fachliche Unterstützung"]], functionPhrase: "Es wäre sinnvoll, zunächst …", discussionPhrase: "Unter diesen Umständen wäre zu bedenken, dass …", wordFamily: ["entlasten", "die Entlastung", "entlastend"], register: ["fertig sein", "erschöpft sein", "stark beansprucht sein"] },
  { terms: [["die Weiterbildung", "Lernen nach der ersten Ausbildung"], ["die Vorkenntnisse", "bereits erworbenes Wissen"], ["die Lernbegleitung", "Unterstützung beim Lernprozess"], ["die Teilhabe", "Möglichkeit zur aktiven Teilnahme"], ["das Lernziel", "angestrebtes Ergebnis"]], functionPhrase: "Um dieses Ziel zu erreichen, …", discussionPhrase: "Im Vergleich dazu bietet … den Vorteil, dass …", wordFamily: ["bilden", "die Bildung", "gebildet"], register: ["etwas lernen", "Kenntnisse erwerben", "Kompetenzen ausbauen"] },
  { terms: [["die Kernzeit", "Zeitraum gemeinsamer Anwesenheit"], ["die Vertretung", "Übernahme einer Aufgabe durch eine andere Person"], ["die Frist", "Termin, bis zu dem etwas erledigt sein muss"], ["die Zuständigkeit", "Verantwortung für eine Aufgabe"], ["die Erreichbarkeit", "Möglichkeit, dienstlich kontaktiert zu werden"]], functionPhrase: "Wäre es möglich, dass …?", discussionPhrase: "Ich verstehe die betrieblichen Anforderungen; dennoch …", wordFamily: ["beschäftigen", "die Beschäftigung", "beschäftigt"], register: ["Schick mir den Plan", "Bitte senden Sie mir den Plan", "Ich wäre Ihnen für die Zusendung des Plans dankbar"] },
  { terms: [["die Anschaffung", "Kauf eines länger nutzbaren Gegenstands"], ["die Folgekosten", "später entstehende Ausgaben"], ["die Reparierbarkeit", "Möglichkeit einer Instandsetzung"], ["das Werbeversprechen", "in Werbung zugesicherter Vorteil"], ["die Verbraucherberatung", "unabhängige Hilfe bei Kaufentscheidungen"]], functionPhrase: "Bei der Entscheidung sollte berücksichtigt werden, dass …", discussionPhrase: "Auf den ersten Blick scheint …; bei genauerem Hinsehen …", wordFamily: ["verbrauchen", "der Verbrauch", "verbrauchsarm"], register: ["billig", "günstig", "kostengünstig"] },
  { terms: [["die Ersatzverbindung", "alternative Reisemöglichkeit"], ["die Verspätung", "spätere Ankunft als geplant"], ["der Anschluss", "weiterführende Verbindung"], ["die Auswirkung", "Folge für Menschen oder Umgebung"], ["der Aufenthalt", "Zeit an einem besuchten Ort"]], functionPhrase: "Ob diese Lösung geeignet ist, hängt davon ab, …", discussionPhrase: "Für Reisende spricht …, während Anwohnende …", wordFamily: ["reisen", "die Reise", "reisefreundlich"], register: ["zu spät kommen", "sich verspäten", "mit Verzögerung eintreffen"] },
  { terms: [["der Datenschutz", "Schutz persönlicher Informationen"], ["die Bildschirmzeit", "Zeit vor einem Bildschirm"], ["der Algorithmus", "Verfahren zur Verarbeitung von Daten"], ["die Datensicherheit", "Schutz gespeicherter Informationen"], ["die digitale Abhängigkeit", "schwer kontrollierbare Nutzung digitaler Angebote"]], functionPhrase: "Einerseits …, andererseits …", discussionPhrase: "Dabei darf jedoch nicht außer Acht gelassen werden, dass …", wordFamily: ["entscheiden", "die Entscheidung", "entscheidend"], register: ["etwas online stellen", "etwas veröffentlichen", "Informationen digital bereitstellen"] },
  { terms: [["die Behauptung", "Aussage ohne gesicherten Beleg"], ["die Quelle", "Ursprung einer Information"], ["die Bestätigung", "Nachweis einer Aussage"], ["die Einordnung", "Erklärung eines Zusammenhangs"], ["die Recherche", "gezielte Suche und Prüfung"]], functionPhrase: "Nach Angaben der Quelle …", discussionPhrase: "Die vorliegenden Belege deuten darauf hin, dass …", wordFamily: ["berichten", "der Bericht", "berichtenswert"], register: ["das stimmt nicht", "die Aussage ist unzutreffend", "die Behauptung lässt sich nicht belegen"] },
  { terms: [["die Maßnahme", "konkreter Schritt zur Veränderung"], ["die Einsparung", "Verringerung eines Verbrauchs"], ["die Finanzierung", "Bereitstellung von Geld"], ["die Emission", "Ausstoß von Stoffen"], ["die Ressource", "verfügbares Material oder Mittel"]], functionPhrase: "Die Maßnahme ließe sich umsetzen, indem …", discussionPhrase: "Langfristig wäre außerdem zu prüfen, ob …", wordFamily: ["sparen", "die Einsparung", "sparsam"], register: ["weniger verbrauchen", "Verbrauch senken", "Ressourcen schonen"] },
  { terms: [["die Inszenierung", "künstlerische Gestaltung einer Darstellung"], ["die Rezension", "begründete Bewertung eines Werks"], ["die Kuratorin", "verantwortliche Person einer Ausstellung"], ["der Eindruck", "subjektive Wahrnehmung"], ["die Perspektive", "Blickwinkel auf ein Thema"]], functionPhrase: "Besonders überzeugend finde ich, dass …", discussionPhrase: "Weniger gelungen erscheint mir hingegen …", wordFamily: ["gestalten", "die Gestaltung", "gestalterisch"], register: ["toll", "gelungen", "bemerkenswert"] },
  { terms: [["die Teilhabe", "Möglichkeit, mitzugestalten"], ["der Interessenkonflikt", "Gegensatz unterschiedlicher Ziele"], ["der Kompromiss", "Lösung mit gegenseitigem Entgegenkommen"], ["die Zugänglichkeit", "Möglichkeit, einen Ort zu nutzen"], ["die Beteiligung", "aktive Mitwirkung"]], functionPhrase: "Aus der Perspektive von … stellt sich die Frage, ob …", discussionPhrase: "Beide Anliegen sind berechtigt; ein möglicher Ausgleich wäre …", wordFamily: ["beteiligen", "die Beteiligung", "beteiligt"], register: ["mitreden", "sich beteiligen", "an Entscheidungen mitwirken"] },
  { terms: [["die These", "zu begründende Aussage"], ["der Einwand", "Gegenargument"], ["die Erwiderung", "begründete Antwort auf einen Einwand"], ["die Abwägung", "Vergleich von Vor- und Nachteilen"], ["die Schlussfolgerung", "Ergebnis aus Gründen und Belegen"]], functionPhrase: "Ich vertrete die Auffassung, dass …", discussionPhrase: "Dieser Einwand ist nachvollziehbar; dennoch …", wordFamily: ["begründen", "die Begründung", "begründet"], register: ["ich finde", "meiner Meinung nach", "meines Erachtens"] },
  { terms: [["der Anlass", "Grund einer Nachricht"], ["die Erstattung", "Rückzahlung eines Betrags"], ["die Rückmeldung", "Antwort auf ein Anliegen"], ["der Betreff", "kurze Themenzeile einer Nachricht"], ["die Frist", "letzter Termin für eine Handlung"]], functionPhrase: "Ich nehme Bezug auf …", discussionPhrase: "Ich bitte Sie daher um … und wäre Ihnen für eine Rückmeldung dankbar.", wordFamily: ["erstatten", "die Erstattung", "erstattungsfähig"], register: ["Ich will mein Geld zurück", "Ich bitte um eine Rückzahlung", "Ich ersuche um Erstattung der Gebühr"] },
  { terms: [["der Kurzvortrag", "kurze strukturierte Präsentation"], ["die Rückfrage", "Frage zur Klärung"], ["die Gliederung", "Ordnung der Hauptpunkte"], ["die Aushandlung", "gemeinsame Suche nach einer Lösung"], ["die Zusammenfassung", "knappe Wiedergabe wichtiger Punkte"]], functionPhrase: "Zunächst möchte ich …, anschließend …", discussionPhrase: "Wenn ich Sie richtig verstehe, meinen Sie …", wordFamily: ["präsentieren", "die Präsentation", "präsentierbar"], register: ["Was meinst du?", "Wie sehen Sie das?", "Dürfte ich Sie um Ihre Einschätzung bitten?"] },
  { terms: [["die Entscheidungsvorlage", "Text als Grundlage einer Entscheidung"], ["das Messkriterium", "Merkmal zur Prüfung eines Ergebnisses"], ["die Auswertung", "systematische Prüfung von Ergebnissen"], ["die Testphase", "begrenzter Erprobungszeitraum"], ["die Synthese", "Verbindung mehrerer Informationen"]], functionPhrase: "Insgesamt sprechen die vorliegenden Informationen dafür, …", discussionPhrase: "Vor einer endgültigen Entscheidung sollte außerdem … überprüft werden.", wordFamily: ["auswerten", "die Auswertung", "auswertbar"], register: ["nachsehen", "prüfen", "systematisch auswerten"] },
];
