/** Original sound-and-intonation practice in everyday communicative contexts. */
export const germanA1Pronunciation = [
  { focus: "Buchstaben und Zahlen deutlich unterscheiden", tip: "Hören Sie die deutschen Buchstabennamen und wiederholen Sie die Zahlen in denselben Gruppen. Buchstabieren Sie danach einen erfundenen Namen.", lines: ["A. E. I. O. U. V. W. Z. N. M.", "Vierzehn. Vierzig. Fünfzehn. Fünfzig. N-O-R-A. Ist das richtig?"] },
  { focus: "Die Melodie von Fragen und Antworten", tip: "Vergleichen Sie eine W-Frage mit einer Ja-Nein-Frage. Kopieren Sie die Melodie, ohne jedes Wort gleich stark zu betonen.", lines: ["Wie heißen Sie? Ich heiße Nora. Woher kommen Sie? Ich komme aus Portugal.", "Wohnen Sie in Bremen? Ja, ich wohne in Bremen. Und Sie?"] },
  { focus: "Kurze und lange Vokale", tip: "Hören Sie Stadt und Staat: Der Vokal ist unterschiedlich lang. Staat bedeutet hier country or state; Stadt bedeutet city. Wiederholen Sie danach die Sätze.", lines: ["Stadt. Staat. Stadt. Staat. Mein Bruder wohnt in der Stadt.", "Das ist meine Schwester. Das sind meine Eltern. Sie wohnen in Köln."] },
  { focus: "Betonung bei trennbaren Verben", tip: "Bei aufstehen hören Sie die Betonung auf auf. Wiederholen Sie erst das ganze Wort, dann den Satz mit der getrennten Form.", lines: ["Aufstehen. Einkaufen. Aufräumen. Ich stehe um sieben Uhr auf.", "Wann beginnt der Kurs? Um halb sieben. Also um sechs Uhr dreißig."] },
  { focus: "Umlaute im Wohnungswortschatz", tip: "Hören Sie die gerundeten Vokale in Möbel und Küche. Wiederholen Sie zuerst die Wörter und dann den Satz.", lines: ["Möbel. Küche. Tür. Schön. Die Küche ist schön.", "Wo steht die Lampe? Auf dem Tisch. Und der Stuhl? Neben der Tür."] },
  { focus: "Höfliche Bitten als ganze Wortgruppen", tip: "Sprechen Sie einen Kaffee, bitte als eine freundliche Gruppe. Lassen Sie nach der Bestellung eine kurze natürliche Pause.", lines: ["Einen Kaffee, bitte. Eine Suppe und ein Wasser, bitte.", "Was kostet das zusammen? Acht Euro fünfzig. Kann ich mit Karte bezahlen?"] },
  { focus: "ei und ie unterscheiden", tip: "Vergleichen Sie ei und ie: Bei ei hören Sie einen gleitenden Laut; ie ist meist ein langes i. Wiederholen Sie die Frage mit derselben Melodie.", lines: ["Klein. Preis. Weiß. Wie. Diese. Sie. Wie viel kostet diese Jacke?", "Diese Jacke kostet dreißig Euro. Haben Sie sie auch in Weiß?"] },
  { focus: "ch in einfachen Alltagswörtern", tip: "Hören Sie ich, nicht und rechts. Wiederholen Sie die Wörter und die Wegbeschreibung. Achten Sie auf die Reihenfolge, nicht auf einen perfekten Akzent.", lines: ["Ich. Nicht. Rechts. Ich suche die Post. Ist sie hier in der Nähe?", "Gehen Sie geradeaus und dann rechts. Also geradeaus und dann rechts, richtig?"] },
  { focus: "Zahlen und Gleise in Ansagen", tip: "Hören Sie zuerst ohne Transcript und notieren Sie Uhrzeit und Gleis. Prüfen Sie anschließend die Zahlen.", lines: ["Der Zug fährt um vierzehn Uhr zwanzig von Gleis vier ab.", "Vierzehn Uhr zwanzig. Gleis vier. Heute hat der Zug fünfzehn Minuten Verspätung."] },
  { focus: "Satzrhythmus mit können", tip: "Betonen Sie die entscheidende Zeitangabe. Hören Sie den Unterschied zwischen der Zusage und der Absage.", lines: ["Ich kann am Dienstag kommen. Am Freitag kann ich nicht kommen.", "Können Sie am Donnerstag arbeiten? Ja, am Donnerstag habe ich Zeit."] },
  { focus: "Einladungen und Rückfragen natürlich sprechen", tip: "Sprechen Sie die Einladung freundlich und die Rückfrage neugierig. Wiederholen Sie die Antwort, dann ändern Sie Tag und Uhrzeit.", lines: ["Hast du am Samstag Zeit? Kommst du mit in den Park?", "Ja, gern. Wann treffen wir uns? Um drei Uhr. Am Eingang zum Park."] },
  { focus: "Wortakzent bei Beschwerden", tip: "Hören Sie Kopfschmerzen als ein zusammenhängendes Wort. Sprechen Sie die Bitte deutlich. Dies ist eine Sprachübung, keine medizinische Beratung.", lines: ["Kopfschmerzen. Halsschmerzen. Fieber. Ich habe Kopfschmerzen.", "Haben Sie heute einen Termin für mich? Ja, um zehn Uhr. Vielen Dank."] },
  { focus: "Zwei unterschiedliche Wetterpläne betonen", tip: "Betonen Sie Samstag und Sonntag sowie sonnig und Regen. So versteht die andere Person den Unterschied zwischen Plan und Ersatzplan.", lines: ["Am Samstag ist es sonnig. Am Sonntag regnet es.", "Am Samstag gehen wir in den Park. Bei Regen gehen wir ins Café. Passt dir zehn Uhr?"] },
  { focus: "Eine Änderung klar bestätigen", tip: "Hören Sie nicht Dienstag, sondern Donnerstag. Wiederholen Sie danach nur die neue Zeit. Die entscheidende Information bekommt mehr Betonung.", lines: ["Ihr Termin ist nicht am Dienstag, sondern am Donnerstag. Um vierzehn Uhr.", "Donnerstag um vierzehn Uhr. Ja, das passt. Soll ich meinen Ausweis mitbringen?"] },
  { focus: "Natürliches Tempo und wichtige Informationen", tip: "Hören Sie diese Wiederholung in natürlicherem Tempo. Notieren Sie zuerst die neue Ankunftszeit, dann die vereinbarte Terminzeit. Wiederholen Sie die Antwort verständlich, nicht möglichst schnell.", lines: ["Mein Zug hat Verspätung. Ich bin erst um elf Uhr fünfundzwanzig in der Sprachschule.", "Können Sie um elf Uhr dreißig kommen? Ja, das passt. Vielen Dank."] },
].map((item, index) => ({
  chapter: index + 1, ...item,
  outputPath: `/audio/german-a1/a1-sounds-${String(index + 1).padStart(2, "0")}.m4a`,
  transcript: `Anna: ${item.lines[0]}\nEddy: ${item.lines[1]}`,
}));

export const germanA1PronunciationManifest = germanA1Pronunciation.map(item => ({
  lessonId: `a1-sounds-${item.chapter}`, slug: `a1-sounds-${item.chapter}`,
  outputPath: item.outputPath, transcript: item.transcript,
}));
