import type { B1Question } from "./german-b1-curriculum.ts";

export type B1GrammarLab = {
  focus: string[];
  bookUnits: string;
  rules: [string, string, string][];
  questions: B1Question[];
  repair: string;
  model: string;
  transfer: string;
};
const q = (prompt: string, answer: string, wrong1: string, wrong2: string, explanation: string): B1Question => ({ prompt, answer, distractors: [wrong1, wrong2], explanation });

// Original examples and tasks. Book unit numbers are optional study references, not copied exercises.
export const b1GrammarLabs: B1GrammarLab[] = [
  {
    focus: ["Negation", "Objektpronomen", "Satzklammer"], bookUnits: "16, 24, 52",
    rules: [["kein + Nomen", "Ich habe noch keinen Lernpartner.", "Keinen steht vor dem maskulinen Akkusativobjekt."], ["nicht mehr / noch nicht", "Ich wohne nicht mehr in Bonn. Die Prüfung habe ich noch nicht gebucht.", "Nicht mehr: früher ja, jetzt nein. Noch nicht: bisher nein, später vielleicht."], ["Satzklammer", "Heute möchte ich dem Kursleiter eine Frage stellen.", "Das finite Modalverb steht auf Position zwei; stellen schließt die Klammer."]],
    questions: [q("Ich habe ___ Wörterbuch dabei. Ergänzen Sie die Verneinung.", "kein", "nicht", "keinen", "Wörterbuch ist neutral: kein Wörterbuch. Nicht verneint hier nicht das Nomen mit unbestimmtem Artikel."), q("Früher arbeitete ich nachts, jetzt tagsüber: Ich arbeite ___ nachts.", "nicht mehr", "noch nicht", "nichts", "Nicht mehr bezeichnet eine beendete Gewohnheit."), q("Ich schicke der Lehrerin meine Aufnahme. Welches Pronomen ersetzt der Lehrerin?", "ihr", "sie", "ihren", "Schicken: jemandem etwas schicken. Die Empfängerin steht im Dativ: ihr."), q("Beginnen Sie mit Heute: Welche Wortstellung ist richtig?", "Heute muss ich meine Aufnahme verbessern.", "Heute ich muss meine Aufnahme verbessern.", "Heute muss verbessern ich meine Aufnahme.", "Heute besetzt Position eins, muss Position zwei; verbessern steht am Ende.")],
    repair: "Korrigieren Sie: 1. Ich habe nicht Lernpartner. 2. Heute ich möchte besser sprechen.", model: "Ich habe keinen Lernpartner. Heute möchte ich besser sprechen. Deshalb suche ich jemanden aus meinem Kurs. Ich möchte mit dieser Person jeden Freitag zehn Minuten telefonieren und neue Ausdrücke ausprobieren.", transfer: "Beschreiben Sie Ihr Lernziel mit einem Modalverb. Schreiben Sie außerdem, was Sie noch nicht können und was Sie nicht mehr brauchen.",
  },
  {
    focus: ["Präteritum", "Plusquamperfekt", "als/wenn", "trennbare Verben"], bookUnits: "54, 55, 57, 77",
    rules: [["einmal / wiederholt", "Als ich Ben kennenlernte, war ich neu im Verein. Wenn wir uns trafen, kochten wir zusammen.", "Als: einmaliger vergangener Rahmen. Wenn: wiederholte Treffen."], ["vorher abgeschlossen", "Ich hatte die Nachricht gelesen, bevor Ben anrief.", "Hatte + Partizip II zeigt die frühere Handlung."], ["trennbar / untrennbar", "Ben rief mich an. Ich habe ihn später besucht.", "Anrufen wird getrennt; besuchen hat kein ge- im Partizip."]],
    questions: [q("Ein einziges erstes Treffen: ___ ich Ben kennenlernte, war ich neu im Verein.", "Als", "Wenn", "Ob", "Einmaliger Rahmen in der Vergangenheit: als."), q("Jeden Samstag früher: ___ wir uns trafen, brachte Ben Brot mit.", "Wenn", "Als", "Nachdem gestern", "Die Treffen wiederholen sich: wenn."), q("Zuerst las ich die Nachricht, dann rief Ben an. Was war vorher passiert?", "Ich hatte die Nachricht gelesen.", "Ich werde die Nachricht lesen.", "Ich hatte die Nachricht lesen.", "Plusquamperfekt: hatte + gelesen, nicht Infinitiv."), q("Perfekt von besuchen: Ich ___ Ben am Sonntag ___.", "habe / besucht", "bin / gebesucht", "habe / gebesucht", "Besuchen bildet das Perfekt mit haben; das untrennbare be- verhindert ge-.")],
    repair: "Korrigieren Sie: 1. Wenn ich Ben zum ersten Mal traf, war ich nervös. 2. Er hat mich gestern angerufen hat.", model: "Als ich Ben zum ersten Mal traf, war ich nervös. Er hat mich gestern angerufen. Vor unserem ersten Treffen hatte ich ihm eine Nachricht geschrieben. Wenn wir uns später trafen, gingen wir oft zusammen spazieren.", transfer: "Erzählen Sie von einer ersten Begegnung. Ergänzen Sie etwas, das vorher passiert war, und eine später wiederholte Aktivität.",
  },
  {
    focus: ["Reflexivpronomen", "temporale Präpositionen", "bevor/während"], bookUnits: "56, 78, 83",
    rules: [["mich / mir", "Ich wasche mich. Ich wasche mir die Hände.", "Mit einem zusätzlichen Akkusativobjekt wie die Hände steht hier das Reflexivpronomen im Dativ."], ["seit / vor / in", "Seit einer Woche lerne ich früher. Vor einer Woche änderte ich meinen Plan. In einer Woche prüfe ich ihn.", "Seit: Dauer bis jetzt; vor: vergangener Abstand; in: zukünftiger Abstand."], ["gleichzeitig / vorher", "Während der Zug fährt, lese ich. Bevor ich losfahre, packe ich meine Tasche.", "Beide Verbindungen leiten einen Nebensatz mit Verb am Ende ein."]],
    questions: [q("Ich nehme ___ jeden Morgen zehn Minuten Zeit.", "mir", "mich", "mein", "Sich Zeit nehmen: Zeit ist das Akkusativobjekt, mir der Dativ."), q("Ich bereite ___ auf den Termin vor.", "mich", "mir", "meinen", "Sich auf etwas vorbereiten verlangt hier das Reflexivpronomen im Akkusativ."), q("Der neue Plan begann letzte Woche und gilt heute: ___ einer Woche plane ich meine Pausen.", "Seit", "Vor", "In", "Seit verbindet einen Beginn in der Vergangenheit mit einer Dauer bis jetzt."), q("Welche Verbindung drückt Gleichzeitigkeit aus?", "Während ich auf den Bus warte, lese ich.", "Bevor ich auf den Bus warte, lese ich danach.", "Nachdem ich auf den Bus warte, lese ich vorher.", "Während zeigt, dass Warten und Lesen gleichzeitig stattfinden.")],
    repair: "Korrigieren Sie: 1. Ich nehme mich eine Pause. 2. Seit drei Tagen habe ich morgen einen Termin.", model: "Ich nehme mir eine Pause. In drei Tagen habe ich einen Termin. Seit einer Woche schreibe ich alle Aufgaben in meinen Kalender. Bevor ich morgens das Haus verlasse, kontrolliere ich die Uhrzeit und die Adresse.", transfer: "Beschreiben Sie Ihre Tagesplanung mit sich Zeit nehmen, seit und bevor. Nennen Sie einen Termin in der Zukunft.",
  },
  {
    focus: ["Positions- und Richtungsverben", "Wechselpräpositionen", "Relativpronomen"], bookUnits: "35, 36, 67, 75, 76",
    rules: [["wo / wohin", "Der Schrank steht neben der Tür. Wir stellen ihn neben die Tür.", "Ort: Dativ; Ziel einer Ortsveränderung: Akkusativ. Bewegung allein entscheidet den Fall nicht."], ["Genus und Fall", "Das ist der Nachbar, dem ich den Schlüssel gebe.", "Der Nachbar bestimmt maskulin Singular; geben verlangt für den Empfänger Dativ: dem."], ["Präposition im Relativsatz", "Das ist die Wohnung, in der ich wohne.", "In der ersetzt in der Wohnung; der Fall kommt aus dem Relativsatz."]],
    questions: [q("Wohin stellen wir das Regal? Wir stellen es ___ Wand.", "an die", "an der", "an den", "Die Wand ist feminin; das Ziel nach an verlangt Akkusativ: an die Wand."), q("Wo hängt das Bild? Es hängt ___ Wand.", "an der", "an die", "an dem", "Der Ort nach an verlangt Dativ feminin: an der Wand."), q("Das ist der Vermieter, ___ ich gestern geschrieben habe.", "dem", "den", "der", "Jemandem schreiben: Dativ. Genus maskulin aus Vermieter: dem."), q("Das ist die Wohnung, ___ wir besichtigt haben.", "die", "der", "dem", "Besichtigen verlangt ein Akkusativobjekt; feminin Singular: die.")],
    repair: "Korrigieren Sie: 1. Ich stelle die Lampe auf dem Tisch. 2. Der Nachbar, den ich helfe, wohnt oben.", model: "Ich stelle die Lampe auf den Tisch. Der Nachbar, dem ich helfe, wohnt oben. Später steht die Lampe neben dem Fenster. Das ist der Platz, an dem ich abends gern lese und meine Nachrichten schreibe.", transfer: "Beschreiben Sie einen Gegenstand zuerst beim Umstellen und danach an seinem neuen Ort. Ergänzen Sie einen Relativsatz über eine Person.",
  },
  {
    focus: ["n-Deklination", "indirekte Fragen", "Modalverben im Präteritum"], bookUnits: "30, 69, 72",
    rules: [["schwache maskuline Nomen", "Der Kollege hilft mir. Ich frage den Kollegen.", "Kollege erhält außerhalb des Nominativs Singular -n. Nicht alle maskulinen Nomen folgen diesem Muster."], ["indirekt fragen", "Können Sie mir sagen, ob der Betrieb Praktika anbietet?", "Ja/Nein-Frage: ob; finite Verbform am Ende."], ["frühere Möglichkeit", "Im letzten Job konnte ich selbstständig arbeiten.", "Konnte bezeichnet vergangene Möglichkeit; könnte ist Konjunktiv II."]],
    questions: [q("Ich spreche mit einem neuen ___ über die Stelle.", "Kollegen", "Kollege", "Kolleges", "Mit + Dativ; Kollege gehört zur n-Deklination: einem Kollegen."), q("Die Personalchefin begrüßt den ___.", "Praktikanten", "Praktikant", "Praktikants", "Praktikant erhält im Akkusativ Singular -en."), q("Welche indirekte Frage ist korrekt?", "Wissen Sie, wann die Schicht beginnt?", "Wissen Sie, wann beginnt die Schicht?", "Wissen Sie, ob wann die Schicht beginnt?", "Das Fragewort bleibt erhalten; beginnt steht am Ende."), q("Beschreiben Sie eine Fähigkeit in Ihrem früheren Job: Ich ___ damals die Kasse bedienen.", "konnte", "könnte", "können", "Damals verlangt hier vergangene Fähigkeit: konnte.")],
    repair: "Korrigieren Sie: 1. Ich habe den Praktikant gefragt. 2. Können Sie sagen, wann beginnt die Arbeit?", model: "Ich habe den Praktikanten gefragt. Können Sie sagen, wann die Arbeit beginnt? In meinem letzten Betrieb konnte ich früh anfangen. Jetzt möchte ich mit dem Kollegen besprechen, ob eine spätere Schicht für mich möglich ist.", transfer: "Stellen Sie eine höfliche indirekte Frage zu einer Stelle. Beschreiben Sie eine frühere Fähigkeit und einen Kontakt mit einem Kollegen.",
  },
  {
    focus: ["Infinitiv mit und ohne zu", "um … zu/damit"], bookUnits: "73, 74, 79",
    rules: [["mit zu", "Ich versuche, jeden Tag zu üben. Ich plane, früher aufzustehen.", "Zu steht bei trennbaren Verben zwischen Präfix und Stamm: aufzustehen."], ["ohne zu", "Ich kann abends lernen. Ich lasse den Text korrigieren.", "Modalverben und lassen stehen mit Infinitiv ohne zu."], ["Ziel und Subjekt", "Ich übe, um flüssiger zu sprechen. Ich spreche langsam, damit mein Partner mich versteht.", "Um … zu: gleicher Handelnder. Damit erlaubt ein anderes Subjekt und hat ein finites Verb."]],
    questions: [q("Ich habe vor, morgen früher ___.", "aufzustehen", "zu aufstehen", "aufstehen zu", "Trennbares aufstehen: zu steht zwischen auf- und stehen."), q("Ich möchte jeden Abend Deutsch ___.", "lernen", "zu lernen", "gelernt", "Nach möchten steht der Infinitiv ohne zu."), q("Ich erkläre die Aufgabe langsam, ___ mein Partner sie versteht.", "damit", "um", "zu", "Unterschiedliche Subjekte ich und mein Partner: damit + finites Verb."), q("Ich besuche den Kurs, ___ sicherer ___ sprechen.", "um / zu", "damit / zu", "weil / zu", "Der Handelnde ist in beiden Teilen ich; das Ziel kann mit um … zu stehen.")],
    repair: "Korrigieren Sie: 1. Ich möchte zu lernen. 2. Ich spreche langsam, um mein Partner mich versteht.", model: "Ich möchte lernen. Ich spreche langsam, damit mein Partner mich versteht. Außerdem versuche ich, jeden Tag einen kurzen Text zu lesen. Ich plane, am Samstag früher aufzustehen, um vor dem Frühstück zehn Minuten zu üben.", transfer: "Beschreiben Sie einen Lernplan mit versuchen, einem Modalverb und einem Ziel. Ergänzen Sie einen damit-Satz mit einem anderen Subjekt.",
  },
  {
    focus: ["Verben mit Präpositionen", "Personen und Sachen", "reflexive Ergänzungen"], bookUnits: "56, 58, 59",
    rules: [["feste Ergänzung", "Ich warte auf den Rückruf. Ich nehme an einem Kurs teil.", "Verb, Präposition und Fall gemeinsam lernen: warten auf + Akkusativ; teilnehmen an + Dativ."], ["Person", "Auf wen warten Sie? Auf die Ärztin.", "Bei Personen bleibt die Präposition vor wen/wem stehen."], ["Sache", "Worauf warten Sie? Auf das Ergebnis. Ich warte darauf.", "Bei Sachen: wo(r)- in der Frage und da(r)- in der Antwort."]],
    questions: [q("Ich nehme ___ einem Rückentraining teil.", "an", "auf", "für", "Teilnehmen an + Dativ: an einem Rückentraining."), q("Die Praxis fragt: Auf wen warten Sie? Welche Antwort passt?", "Auf die Ärztin.", "Auf das Ergebnis.", "Darauf, dass der Brief kommt.", "Wen fragt nach einer Person. Das Ergebnis und der kommende Brief sind Sachen/Inhalte."), q("Ich warte auf das Testergebnis. Wodurch kann man auf das Testergebnis ersetzen?", "darauf", "darüber", "daran", "Die Ergänzung mit auf wird bei einer Sache durch darauf ersetzt."), q("Ich erinnere ___ an den vereinbarten Termin.", "mich", "mir", "mein", "Sich erinnern an + Akkusativ; hier mich.")],
    repair: "Korrigieren Sie: 1. Ich nehme auf dem Kurs teil. 2. Worauf warten Sie? Auf meine Ärztin.", model: "Ich nehme an dem Kurs teil. Auf wen warten Sie? Auf meine Ärztin. Auf das Ergebnis warte ich ebenfalls, aber dazu frage ich: Worauf warten Sie? Ich erinnere mich außerdem an den Termin am Dienstag.", transfer: "Schreiben Sie je eine Frage zu einer Person und zu einer Sache. Antworten Sie mit dem passenden Ausdruck und nennen Sie einen Kurs, an dem Sie teilnehmen.",
  },
  {
    focus: ["Plusquamperfekt", "temporale Nebensätze", "indirekte Fragen"], bookUnits: "55, 72, 78",
    rules: [["Vorvergangenheit", "Nachdem wir die Tickets gebucht hatten, suchten wir eine Unterkunft.", "Buchen war zuerst abgeschlossen; suchen ist die spätere vergangene Handlung."], ["bevor", "Bevor wir abreisten, überprüften wir die Adresse.", "Bevor ordnet zwei Handlungen; ein Plusquamperfekt ist nicht in jedem bevor-Satz nötig."], ["Information erfragen", "Ich möchte wissen, von welchem Gleis der Zug abfährt.", "Die Präposition gehört zum Fragewort; das finite Verb steht am Ende."]],
    questions: [q("Zuerst kam der Zug an, dann stiegen wir aus: Nachdem der Zug ___, stiegen wir aus.", "angekommen war", "angekommen hatte", "ankommen war", "Ankommen bildet Perfekt und Plusquamperfekt mit sein: angekommen war."), q("Wir hatten die Zimmer schon ___, als die Reise abgesagt wurde.", "bezahlt", "gebezahlt", "bezahlen", "Untrennbares be-: bezahlt, kein ge-."), q("Welche Frage passt in eine höfliche Nachricht?", "Können Sie mir sagen, wo ich umsteigen muss?", "Können Sie mir sagen, wo muss ich umsteigen?", "Können Sie mir sagen, wo ich muss zu umsteigen?", "In der indirekten Frage steht muss hinter dem Infinitiv am Ende."), q("Welche Aussage ist logisch eindeutig?", "Bevor wir losfuhren, prüften wir die Buchung.", "Nachdem wir losfuhren, prüften wir vorher die Buchung.", "Wir prüften die Buchung, obwohl damit wir losfuhren.", "Bevor markiert die Prüfung als früheren Schritt.")],
    repair: "Korrigieren Sie: 1. Nachdem wir angekommen hatten, riefen wir zu Hause an. 2. Ich frage, wo fährt der Bus ab.", model: "Nachdem wir angekommen waren, riefen wir zu Hause an. Ich frage, wo der Bus abfährt. Wir hatten die Adresse schon notiert, bevor wir die Unterkunft suchten. Trotzdem mussten wir am Bahnhof noch einmal nach dem richtigen Weg fragen.", transfer: "Erzählen Sie eine Reise in drei Schritten. Verwenden Sie ein Plusquamperfekt und ergänzen Sie eine indirekte Frage zur Weiterfahrt.",
  },
  {
    focus: ["Adjektivdeklination", "Vergleiche", "lassen"], bookUnits: "40, 41, 42, 43, 66, 84",
    rules: [["Artikel zeigt Merkmale", "Der günstige Tarif passt. Ein günstiger Tarif passt. Mit einem günstigen Tarif spare ich.", "Im Dativ nach einem erhält das Adjektiv -en; ohne bestimmtes Artikelsignal übernimmt es mehr Endungen."], ["ohne Artikel", "Wir bieten kostenlose Beratung und günstige Preise.", "Ohne Artikel tragen Adjektive die passende Kasusendung."], ["lassen + Infinitiv", "Ich lasse den Reißverschluss reparieren.", "Ich organisiere die Reparatur; eine andere Person führt sie aus. Kein zu."]],
    questions: [q("Ich suche einen ___ Rucksack.", "stabilen", "stabiler", "stabile", "Einen + Akkusativ maskulin: stabilen."), q("Der Anbieter wirbt mit ___ Beratung. Kein Artikel steht vor Beratung.", "kostenloser", "kostenlosen", "kostenlose", "Mit + Dativ feminin; ohne Artikel zeigt -er den Fall: kostenloser Beratung."), q("Der neue Tarif ist günstiger ___ der alte.", "als", "wie", "denn", "Ungleichheit im Komparativ: günstiger als."), q("Welche Aussage bedeutet, dass jemand anders die Reparatur übernimmt?", "Ich lasse den Rucksack reparieren.", "Ich repariere den Rucksack selbst.", "Ich lasse den Rucksack zu reparieren.", "Lassen + Objekt + Infinitiv ohne zu bezeichnet hier eine veranlasste Handlung.")],
    repair: "Korrigieren Sie: 1. Ich suche einen günstiger Vertrag. 2. Ich lasse mein Handy zu reparieren.", model: "Ich suche einen günstigen Vertrag. Ich lasse mein Handy reparieren. Bei einem neuen Gerät würde ich auf einen stabilen Akku achten. Für mich ist kostenlose Beratung wichtiger als eine besonders bunte Verpackung oder ein kleines Geschenk.", transfer: "Vergleichen Sie zwei Angebote. Verwenden Sie ein Adjektiv nach einem Artikel, eins ohne Artikel und lassen für eine Dienstleistung.",
  },
  {
    focus: ["Pronominaladverbien", "ob/dass", "Gegensatz"], bookUnits: "58, 59, 72",
    rules: [["Inhalt ersetzen", "Ich denke darüber nach, ob die Nachricht stimmt.", "Nachdenken über + Akkusativ; darüber verweist auf den folgenden Inhalt."], ["offene Frage / Aussage", "Ich weiß nicht, ob es stimmt. Die Redaktion schreibt, dass es stimmt.", "Ob: noch offene Ja/Nein-Frage. Dass: mitgeteilter Inhalt."], ["obwohl / trotzdem", "Obwohl der Beitrag alt ist, wird er geteilt. Er ist alt. Trotzdem wird er geteilt.", "Obwohl: Verb am Ende. Trotzdem: Hauptsatz mit Verb auf Position zwei."]],
    questions: [q("Ich interessiere mich für die Quelle. Ich interessiere mich ___.", "dafür", "darauf", "davon", "Für eine Sache: für → dafür."), q("Ich bin nicht sicher, ___ das Foto aktuell ist.", "ob", "dass", "weil", "Nicht sicher, ob: eine offene Ja/Nein-Frage."), q("Welche Wortstellung nach Trotzdem ist richtig?", "Trotzdem teile ich den Beitrag nicht.", "Trotzdem ich teile den Beitrag nicht.", "Trotzdem den Beitrag nicht ich teile.", "Trotzdem steht auf Position eins; teile folgt direkt."), q("Bei einer Person: ___ sprichst du über den Artikel?", "Mit wem", "Womit", "Damit", "Sprechen mit einer Person: mit wem. Womit fragt nach einer Sache/einem Mittel.")],
    repair: "Korrigieren Sie: 1. Ich weiß nicht, dass diese Nachricht stimmt oder nicht. 2. Trotzdem ich prüfe die Quelle.", model: "Ich weiß nicht, ob diese Nachricht stimmt. Trotzdem prüfe ich die Quelle. Ich interessiere mich dafür, wer den Text veröffentlicht hat. Obwohl die Überschrift überzeugend klingt, suche ich zunächst nach einem zweiten Bericht und einem aktuellen Datum.", transfer: "Erklären Sie, wie Sie eine Nachricht prüfen. Nutzen Sie ob, ein Pronominaladverb und einen Gegensatz.",
  },
  {
    focus: ["Passiv Präsens/Präteritum", "Passiv mit Modalverb", "Futur I"], bookUnits: "62, 63, 64, 65",
    rules: [["Vorgang statt Handelnder", "Die Behälter werden geleert. Gestern wurden sie gereinigt.", "Werden/wurden + Partizip II bildet Vorgangspassiv in Gegenwart/Vergangenheit."], ["Modalpassiv", "Die Flaschen müssen getrennt gesammelt werden.", "Modalverb + Partizip II + werden: beide infiniten Formen am Ende."], ["Zukunft unterscheiden", "Die Gruppe wird morgen aufräumen.", "Werden + Infinitiv ist Futur; werden + Partizip II ist Passiv. Präsens mit Zeitangabe kann ebenfalls Zukunft ausdrücken."]],
    questions: [q("Gestern ___ die Sammelstelle geschlossen. Beschreiben Sie den Vorgang im Präteritum.", "wurde", "wird", "werden", "Gestern und Vorgangspassiv im Präteritum: wurde geschlossen."), q("Welche Aussage ist Passiv?", "Die alten Geräte werden geprüft.", "Die Gruppe wird die Geräte prüfen.", "Die Gruppe prüft die Geräte.", "Werden + geprüft ist Passiv; wird + prüfen ist Futur."), q("Welche Satzklammer ist korrekt?", "Die Batterien müssen getrennt entsorgt werden.", "Die Batterien müssen werden getrennt entsorgt.", "Die Batterien müssen getrennt entsorgen werden.", "Modalpassiv endet mit Partizip II + werden: entsorgt werden."), q("Welcher Satz kündigt eine zukünftige Handlung mit Futur I an?", "Wir werden die Abfälle morgen sortieren.", "Die Abfälle werden sortiert.", "Die Abfälle wurden sortiert.", "Werden + Infinitiv sortieren zeigt hier Futur I.")],
    repair: "Korrigieren Sie: 1. Gestern wird der Hof gereinigt. 2. Glas muss getrennt sammeln werden.", model: "Gestern wurde der Hof gereinigt. Glas muss getrennt gesammelt werden. Heute werden die Behälter geleert. Unsere Gruppe wird am Samstag den Garten aufräumen. Danach prüfen wir, welche Geräte noch repariert werden können und welche Teile ersetzt werden müssen.", transfer: "Schreiben Sie über eine Umweltaktion: eine vergangene Maßnahme, eine aktuelle Regel und einen zukünftigen Plan. Markieren Sie die unterschiedlichen Formen von werden.",
  },
  {
    focus: ["Doppelkonnektoren", "substantivierte Adjektive", "Relativsatz mit Präposition"], bookUnits: "70, 71, 76, 80",
    rules: [["beides / keines / Alternative", "Wir brauchen sowohl Helfer als auch Material. Es gibt weder Strom noch Wasser. Entweder gehen wir hinein oder wir bleiben draußen.", "Die Paare behalten ihre Bedeutung; verbinden Sie grammatisch parallele Teile."], ["Adjektiv als Nomen", "Die Freiwilligen helfen. Ein Freiwilliger übernimmt den Empfang.", "Großschreibung und Adjektivendung bleiben wichtig: bestimmter/unbestimmter Artikel ändern die Endung."], ["Präposition im Relativsatz", "Das ist die Person, mit der wir die Aktion planen.", "Mit verlangt Dativ; Person ist feminin, also der."]],
    questions: [q("Zwei Dinge fehlen: Wir haben ___ Werkzeug ___ einen Raum.", "weder / noch", "sowohl / als auch", "entweder / aber", "Weder … noch verneint beide verbundenen Teile."), q("Zwei Aufgaben gehören dazu: Die Gruppe organisiert ___ Essen ___ Getränke.", "sowohl / als auch", "weder / sondern", "entweder / noch", "Sowohl … als auch verbindet zwei zutreffende Aufgaben."), q("Heute hilft ein ___ am Empfang.", "Freiwilliger", "Freiwilligen", "freiwilliger", "Ein substantiviertes Adjektiv wird großgeschrieben; Nominativ maskulin nach ein: Freiwilliger."), q("Das ist die Koordinatorin, mit ___ wir gesprochen haben.", "der", "die", "dem", "Mit + Dativ; feminin Singular: der.")],
    repair: "Korrigieren Sie: 1. Wir haben weder Geld oder Werkzeug. 2. Ein Freiwilligen übernimmt den Empfang.", model: "Wir haben weder Geld noch Werkzeug. Ein Freiwilliger übernimmt den Empfang. Deshalb fragen wir die Nachbarschaft sowohl nach Material als auch nach Unterstützung. Das ist die Gruppe, mit der wir am Sonntag die Aufgaben und die Arbeitszeiten besprechen möchten.", transfer: "Planen Sie eine Nachbarschaftsaktion mit zwei passenden Doppelkonnektoren. Nennen Sie die Aufgabe einer freiwilligen Person und bilden Sie einen Relativsatz mit mit.",
  },
  {
    focus: ["Genitiv und Genitivpräpositionen", "Partizip I als Adjektiv", "Vergleich"], bookUnits: "68, 82, 84, 85",
    rules: [["Genitiv", "Während der Führung betrachten wir die Geschichte des Museums.", "Während + Genitiv; maskuline/neutrale Nomen erhalten oft -s/-es."], ["trotz", "Trotz des Regens findet der Rundgang statt.", "Trotz nennt einen Gegengrund; im schriftlichen Standardtraining steht hier Genitiv."], ["Partizip I", "Die wartenden Besucher stehen vor der Tür.", "Warten + d + Adjektivendung beschreibt eine aktive, gleichzeitige Tätigkeit."]],
    questions: [q("Wir treffen uns vor dem Eingang ___ Museums.", "des", "dem", "den", "Zugehörigkeit: der Eingang des Museums, Genitiv neutral."), q("___ des schlechten Wetters findet die Führung draußen statt.", "Trotz", "Wegen", "Seit", "Ein Gegengrund, der den Rundgang nicht verhindert: trotz. Wegen würde den Grund nennen."), q("Die Personen warten jetzt vor dem Museum. Welche Bezeichnung passt?", "die wartenden Besucher", "die gewarteten Besucher", "die wartende Besucher", "Partizip I beschreibt die aktive Tätigkeit warten; nach die im Plural: wartenden."), q("Das Museum ist genauso interessant ___ die Ausstellung im Rathaus.", "wie", "als", "desto", "Gleichheit mit genauso: wie. Komparativ: als.")],
    repair: "Korrigieren Sie: 1. Während die Führung fotografieren wir nicht. 2. Die wartende Besucher lesen das Programm.", model: "Während der Führung fotografieren wir nicht. Die wartenden Besucher lesen das Programm. Trotz des Regens bleiben einige Gäste im Hof. Die Geschichte des Museums interessiert mich besonders, weil die alten Fotos zeigen, wie sich die Stadt verändert hat.", transfer: "Beschreiben Sie einen Kulturbesuch mit während + Nomen, trotz und einem Partizip-I-Adjektiv. Nennen Sie etwas, das Ihnen besonders gefällt.",
  },
  {
    focus: ["Konjunktiv II", "hypothetische Bedingungen", "lassen"], bookUnits: "60, 61, 66",
    rules: [["Wunsch und Bedingung", "Wenn ich mehr Zeit hätte, würde ich öfter kochen.", "Hätte/wäre sind häufige Formen; würde + Infinitiv eignet sich für viele andere Verben."], ["Rat / höfliche Bitte", "Du solltest eine Pause machen. Könntest du den Plan ändern?", "Solltest: Rat. Könntest: höfliche Bitte oder Möglichkeit."], ["Handlung veranlassen", "Wir lassen den Plan von der Gruppe prüfen.", "Lassen + Infinitiv ohne zu; die Gruppe führt die Prüfung aus."]],
    questions: [q("Wenn ich mehr Platz ___, würde ich einen größeren Tisch kaufen.", "hätte", "hatte", "habe gestern", "Eine hypothetische gegenwärtige Bedingung verlangt hier hätte."), q("Welche höfliche Bitte ist korrekt?", "Könntest du mir deinen Vorschlag erklären?", "Konntest du mir morgen deinen Vorschlag erklärt?", "Könntest du mir deinen Vorschlag zu erklären?", "Könntest + Infinitiv ohne zu ist eine höfliche Bitte."), q("Ein Rat: Du ___ zuerst mit deiner Mitbewohnerin sprechen.", "solltest", "sollte", "sollen", "Du solltest: Konjunktiv II mit der Endung -st."), q("Welche Form drückt einen Wunsch aus?", "Ich wäre gern früher zu Hause.", "Ich war gern morgen zu Hause.", "Ich würde gern gewesen zu Hause.", "Wäre ist Konjunktiv II von sein; die anderen Formen passen nicht.")],
    repair: "Korrigieren Sie: 1. Wenn ich mehr Zeit hatte, würde ich jetzt helfen. 2. Wir lassen den Plan zu prüfen.", model: "Wenn ich mehr Zeit hätte, würde ich jetzt helfen. Wir lassen den Plan prüfen. Ich wäre gern bei der Besprechung dabei. Könnten wir sie auf Donnerstag verschieben? Dann könnte ich zuhören und wir würden gemeinsam einen passenden Kompromiss finden.", transfer: "Schlagen Sie für einen Konflikt einen höflichen Kompromiss vor. Nennen Sie einen Wunsch und eine hypothetische Bedingung.",
  },
  {
    focus: ["je … desto", "vorangestellter Nebensatz", "Argumentation"], bookUnits: "45, 46, 81",
    rules: [["gemeinsame Veränderung", "Je häufiger ich übe, desto sicherer spreche ich.", "Je-Teil: Verb am Ende; desto + Komparativ besetzt gemeinsam die erste Position des Hauptsatzes."], ["Nebensatz zuerst", "Obwohl ich nervös bin, halte ich die Präsentation.", "Nach dem vorangestellten Nebensatz folgt direkt das Hauptsatzverb, dann das Subjekt."], ["Grund oder Folge", "Ich übe, denn ich möchte sicherer sprechen. Ich übe oft. Deshalb spreche ich sicherer.", "Denn verbindet zwei Hauptsätze; deshalb steht innerhalb des zweiten Hauptsatzes."]],
    questions: [q("Je besser ich mich vorbereite, ___ ruhiger beginne ich.", "desto", "weil", "obwohl", "Je … desto verbindet zwei miteinander veränderliche Größen."), q("Welche Wortstellung ist korrekt?", "Je länger ich übe, desto flüssiger spreche ich.", "Je länger ich übe, desto flüssiger ich spreche.", "Je länger ich übe, desto ich spreche flüssiger.", "Desto flüssiger ist das erste Satzglied; danach kommt spreche, dann ich."), q("Welche Fortsetzung passt? Obwohl ich nervös bin, …", "erkläre ich meine Meinung.", "ich erkläre meine Meinung.", "meine Meinung ich erkläre.", "Nach dem vorangestellten Nebensatz folgt das finite Hauptsatzverb."), q("Welche Begründung mit denn ist korrekt?", "Ich übe laut, denn ich möchte verständlich sprechen.", "Ich übe laut, denn ich verständlich sprechen möchte.", "Ich übe laut, denn möchte ich verständlich sprechen.", "Denn steht zwischen Hauptsätzen und verändert deren Verbzweitstellung nicht.")],
    repair: "Korrigieren Sie: 1. Je mehr ich übe, desto sicherer ich spreche. 2. Obwohl ich nervös bin, ich erkläre meine Meinung.", model: "Je mehr ich übe, desto sicherer spreche ich. Obwohl ich nervös bin, erkläre ich meine Meinung. Ich nenne zuerst meinen Standpunkt, dann einen Grund und ein Beispiel. Zum Schluss fasse ich zusammen, welche Lösung für mich am besten funktioniert.", transfer: "Formulieren Sie eine kurze Meinung zu einem Alltagsthema. Verwenden Sie je … desto, einen Grund und einen Gegensatz.",
  },
  {
    focus: ["gemischte Zeiten", "Zweck", "Passiv", "Höflichkeit"], bookUnits: "55, 60–65, 76, 79, 80, 84",
    rules: [["vorher / später", "Nachdem wir den Raum gebucht hatten, wurden die Gäste eingeladen.", "Plusquamperfekt für die frühere Buchung; Präteritum Passiv für die folgende Einladung."], ["Zweck mit anderem Subjekt", "Wir schreiben groß, damit alle Gäste die Hinweise lesen können.", "Damit + finite Verbform; mit Modalverb steht können nach lesen."], ["Bitte und Alternative", "Könnten Sie entweder den Empfang oder die Getränke übernehmen?", "Höflicher Konjunktiv II; entweder … oder stellt zwei Möglichkeiten gegenüber."]],
    questions: [q("Nachdem wir die Zusagen ___, verteilten wir die Aufgaben.", "erhalten hatten", "erhalten waren", "erhalten haben morgen", "Erhalten bildet die Vorvergangenheit mit haben: erhalten hatten."), q("Die Gäste sollen informiert werden: Welche Form ist korrekt?", "Die Gäste müssen rechtzeitig informiert werden.", "Die Gäste müssen rechtzeitig informieren werden.", "Die Gäste müssen rechtzeitig werden informiert.", "Modalpassiv: müssen + informiert + werden."), q("Wir geben eine Adresse an, ___ die Gäste den Raum finden.", "damit", "um", "zu", "Anderes Subjekt: wir geben an, die Gäste finden; damit."), q("Nach einem Artikel im Akkusativ: Wir suchen einen ___ Raum.", "ruhigen", "ruhiger", "ruhige", "Einen + maskuliner Akkusativ: ruhigen Raum.")],
    repair: "Korrigieren Sie: 1. Die Gäste müssen eingeladen werden sind. 2. Wir erklären den Weg, um alle Gäste den Raum finden.", model: "Die Gäste müssen eingeladen werden. Wir erklären den Weg, damit alle Gäste den Raum finden. Nachdem wir einen ruhigen Raum gebucht hatten, verteilten wir die Aufgaben. Könnten Sie den Empfang übernehmen? Ich würde entweder die Getränke besorgen oder die Einladungen verschicken.", transfer: "Schreiben Sie einen kurzen Organisationsplan: Was war vorher erledigt? Was muss noch gemacht werden? Nennen Sie einen Zweck und bitten Sie höflich um Hilfe.",
  },
];
