export type B1Question = {
  prompt: string;
  answer: string;
  distractors: [string, string];
  explanation: string;
};
export type B1Chapter = {
  title: string;
  outcome: string;
  domain: "personal" | "public" | "educational" | "occupational";
  function: string;
  vocabulary: [string, string, string][];
  grammar: string[];
  grammarExplanation: string;
  grammarExample: string;
  grammarCheck: B1Question;
  connectors: [string, string][];
  reading: string;
  readingCheck: B1Question;
  listening: string;
  listeningCheck: B1Question;
  writing: string;
  writingModel: string;
  speaking: string;
  speakingModel: string;
  interaction: string;
  redemittel: [string, string][];
  everyday: string;
  mission: string;
};

// Original ScienceDojo teaching texts; official examination materials are linked separately.
export const germanB1Chapters: B1Chapter[] = [
  {
    title: "Willkommen auf B1 · Ihre Brücke von A2", domain: "educational",
    outcome: "Erfahrungen, Lernziele und Gründe in verbundenen Sätzen beschreiben.", function: "describe experiences and set learning goals",
    vocabulary: [["ursprünglich", "originally", "Ich komme ursprünglich aus Chile."], ["die Erfahrung, -en", "experience", "Ich habe Erfahrung im Verkauf."], ["das Ziel, -e", "goal", "Mein Ziel ist ein Gespräch ohne Hilfe."], ["sich verbessern", "to improve", "Ich möchte mich im Schreiben verbessern."], ["die Voraussetzung, -en", "prerequisite", "A2 ist eine Voraussetzung für diesen Kurs."], ["regelmäßig", "regularly", "Ich übe regelmäßig mit einer Partnerin."]],
    grammar: ["Präsens", "Perfekt", "Präteritum: sein/haben/Modalverben", "Akkusativ/Dativ", "Modalverben", "Nebensatz: weil/dass", "Hauptsatz: denn/deshalb"],
    grammarExplanation: "Präsens beschreibt Gegenwart: Ich lerne. Perfekt erzählt mündlich Vergangenes: Ich habe gelernt; ich bin umgezogen. Sein, haben und Modalverben stehen oft im Präteritum: war, hatte, konnte. Akkusativ: Ich besuche den Kurs. Dativ: Ich helfe dem Nachbarn. Modalverb + Infinitiv: Ich möchte besser sprechen. Weil und dass stellen das finite Verb ans Ende. Denn verbindet Hauptsätze; nach deshalb steht das Verb auf Position zwei.",
    grammarExample: "A2: Ich lerne Deutsch. Ich brauche Deutsch im Beruf. B1: Ich lerne Deutsch, weil ich es im Beruf brauche. Deshalb übe ich jeden Tag.",
    grammarCheck: { prompt: "Verbinden Sie: Ich besuche einen Kurs. Ich möchte im Beruf sicherer sprechen.", answer: "Ich besuche einen Kurs, weil ich im Beruf sicherer sprechen möchte.", distractors: ["Ich besuche einen Kurs, weil ich möchte im Beruf sicherer sprechen.", "Ich besuche einen Kurs, deshalb ich im Beruf sicherer sprechen möchte."], explanation: "Im weil-Satz steht das finite Modalverb möchte am Ende; der Infinitiv sprechen steht davor." },
    connectors: [["weil", "Grund; Verb am Ende"], ["deshalb", "Folge; Verb auf Position zwei"], ["denn", "Grund; Hauptsatzwortstellung"]],
    reading: "Im Lernforum stellt sich Ana vor: Ich komme ursprünglich aus Chile und lebe seit zwei Jahren in Leipzig. In meiner Heimat habe ich in einem Geschäft gearbeitet. Jetzt besuche ich einen Deutschkurs, weil ich eine Ausbildung beginnen möchte. Im Alltag kann ich vieles allein erledigen. Längere Telefonate sind aber noch schwierig, besonders wenn jemand schnell spricht. Deshalb möchte ich jede Woche mit einer Lernpartnerin telefonieren. Außerdem schreibe ich kurze Nachrichten und lasse sie im Kurs besprechen. Früher habe ich Wortlisten gelernt, ohne eigene Sätze zu bilden. Jetzt möchte ich neue Wörter in kleinen Geschichten verwenden. Am Ende des Monats will ich meine erste Aufnahme mit einer neuen vergleichen. So kann ich feststellen, was schon besser funktioniert und was ich noch üben muss.",
    readingCheck: { prompt: "Wie möchte Ana ihren Fortschritt überprüfen?", answer: "Sie möchte zwei eigene Aufnahmen vergleichen.", distractors: ["Sie möchte nur mehr Wortlisten auswendig lernen.", "Sie möchte jeden Tag eine Prüfung buchen."], explanation: "Ana vergleicht ihre erste Aufnahme mit einer neuen am Monatsende." },
    listening: "Willkommen in unserem B1-Kurs. Sie müssen noch nicht fehlerfrei sprechen. Wichtig ist, dass Sie Gedanken verbinden und nachfragen, wenn etwas unklar ist. Heute machen wir kurze Aufgaben zum Lesen, Hören und zur Grammatik. Danach schreiben Sie eine Nachricht und nehmen eine Vorstellung auf. Notieren Sie, wobei Sie Hilfe brauchen. Wer Schwierigkeiten mit der Vergangenheit hat, wiederholt die Beispiele zu Perfekt und Präteritum. Wer schon sicher erzählt, ergänzt Gründe und Gegensätze. Bringen Sie nächste Woche einen persönlichen Lernplan mit. Wählen Sie zwei kleine Ziele, die zu Ihrem Alltag passen, statt zehn große Ziele gleichzeitig zu beginnen.",
    listeningCheck: { prompt: "Was soll der persönliche Lernplan enthalten?", answer: "Zwei kleine Ziele, die zum Alltag passen.", distractors: ["Zehn große Ziele auf einmal.", "Nur eine Liste der Prüfungstermine."], explanation: "Die Kursleitung empfiehlt zwei kleine, alltagstaugliche Ziele." },
    writing: "Stellen Sie sich einer Lernpartnerin vor: Herkunft und heutiger Alltag, eine Erfahrung, ein Lernziel und Ihr konkreter Übungsplan. Schreiben Sie etwa 80 Wörter.",
    writingModel: "Hallo Lea, ich komme ursprünglich aus Chile und lebe seit zwei Jahren in Leipzig. Früher habe ich im Verkauf gearbeitet. Jetzt möchte ich eine Ausbildung beginnen, deshalb lerne ich Deutsch. Im Alltag verstehe ich vieles, aber Telefonate fallen mir noch schwer. Ich möchte jede Woche zehn Minuten mit dir telefonieren und danach drei neue Ausdrücke aufschreiben. Außerdem nehme ich am Monatsende eine kurze Vorstellung auf. So kann ich meinen Fortschritt sehen. Wann hast du Zeit für unser erstes Gespräch? Viele Grüße, Ana",
    speaking: "Stellen Sie sich vor. Erzählen Sie von einer früheren Tätigkeit, erklären Sie Ihren Weg zum Deutschlernen und nennen Sie einen realistischen Plan.", speakingModel: "Ich komme ursprünglich aus Chile, wohne aber jetzt in Leipzig. Früher habe ich in einem Geschäft gearbeitet. Ich lerne Deutsch, weil ich eine Ausbildung machen möchte. Beim Telefonieren bin ich noch unsicher. Deshalb übe ich einmal pro Woche mit einer Partnerin. Wenn ich etwas nicht verstehe, frage ich nach.",
    interaction: "Vereinbaren Sie mit einer Lernpartnerin Zeit, Dauer und Thema eines wöchentlichen Gesprächs. Ihre Partnerin kann nur abends; Sie möchten morgens üben. Finden Sie eine Lösung.",
    redemittel: [["Ich komme ursprünglich aus …", "Herkunft und Lebensweg"], ["Mein Ziel ist, … zu …", "Lernziel"], ["Könnten Sie das bitte anders erklären?", "Verständnis sichern"]],
    everyday: "Bitten Sie in einem Gespräch um Wiederholung: Könnten Sie das langsamer sagen? Wiederholen Sie die wichtige Information mit eigenen Worten.", mission: "Erstellen Sie Ihr Startprofil: Lesen, Hören, Grammatik, Schreiben und Sprechen jeweils sicher / mit Hilfe / noch schwierig. Wählen Sie für die kommende Woche zwei passende Übungen aus diesem Kapitel.",
  },
  {
    title: "Menschen, Beziehungen und Lebensgeschichten", domain: "personal", outcome: "Von einer Begegnung zusammenhängend erzählen und Personen beschreiben.", function: "tell a life story",
    vocabulary: [["zuverlässig", "reliable", "Mara hält ihre Versprechen und ist zuverlässig."], ["die Begegnung, -en", "encounter", "Die Begegnung war wichtig für mich."], ["sich kennenlernen", "to get to know each other", "Wir haben uns im Kurs kennengelernt."], ["sich erinnern an + Akkusativ", "to remember", "Ich erinnere mich an den ersten Tag."], ["die Freundschaft, -en", "friendship", "Unsere Freundschaft besteht seit Jahren."], ["umziehen", "to move home", "Wir sind nach Köln umgezogen."]],
    grammar: ["Perfekt/Präteritum", "Plusquamperfekt", "als/wenn", "nachdem"], grammarExplanation: "Perfekt ist typisch für mündliche Erzählungen. War und hatte sind auch mündlich üblich. Als beschreibt ein einmaliges Ereignis in der Vergangenheit; wenn beschreibt Wiederholungen oder Bedingungen. Plusquamperfekt: hatte/war + Partizip II beschreibt, was vor einem anderen vergangenen Ereignis passiert war. Nachdem ich umgezogen war, lernte ich Mara kennen.", grammarExample: "Als ich nach Köln zog, kannte ich niemanden. Nachdem ich einen Kurs begonnen hatte, lernte ich Mara kennen.",
    grammarCheck: { prompt: "Einmaliges Ereignis in der Vergangenheit: ___ ich Mara zum ersten Mal traf, war ich nervös.", answer: "Als", distractors: ["Wenn", "Ob"], explanation: "Zum ersten Mal bezeichnet hier einen einmaligen vergangenen Moment: als." }, connectors: [["als", "einmalige Vergangenheit"], ["nachdem", "zeitliche Reihenfolge"], ["anschließend", "nächster Schritt"]],
    reading: "Als Jonas nach Köln zog, kannte er dort niemanden. Er hatte eine neue Stelle gefunden und freute sich auf die Arbeit, aber die Abende waren oft langweilig. Eines Tages meldete er sich zu einem Kochkurs an. Dort traf er Mara, die ebenfalls erst seit kurzer Zeit in der Stadt wohnte. Zuerst sprachen sie nur über die Rezepte. Anschließend gingen sie mit anderen Teilnehmern noch etwas trinken. Mara schlug vor, am Wochenende zusammen den Markt zu besuchen. Jonas war überrascht, wie schnell daraus eine Freundschaft entstand. Heute treffen sie sich regelmäßig und helfen einander im Alltag. Jonas sagt, dass gemeinsame Interessen den Anfang leichter machen. Trotzdem braucht eine Freundschaft Zeit: Man muss zuhören, zuverlässig sein und sich auch melden, wenn gerade kein gemeinsames Treffen geplant ist.",
    readingCheck: { prompt: "Warum meldete Jonas sich zum Kochkurs an?", answer: "Nach seinem Umzug wollte er Kontakt zu Menschen finden.", distractors: ["Er wollte Mara bei einem Vorstellungsgespräch treffen.", "Seine Firma verlangte einen Kochabschluss."], explanation: "Jonas kannte niemanden und fand seine Abende langweilig; im Kochkurs entstanden Kontakte." },
    listening: "Ich erinnere mich noch gut an meinen ersten Arbeitstag. Ich war sehr aufgeregt, weil ich vorher nur in kleinen Geschäften gearbeitet hatte. Mein Kollege Ben zeigte mir die Räume und erklärte mir die Aufgaben. Als ich später eine Kundin nicht verstand, half er mir ruhig weiter. Nach der Arbeit fragte ich ihn, wie ich neue Ausdrücke lernen könnte. Er empfahl mir, jeden Tag drei typische Sätze aufzuschreiben. Seitdem sprechen wir in der Pause oft miteinander. Ich finde ihn besonders zuverlässig, denn er hört zu und hält seine Versprechen. Für mich war diese Begegnung der Beginn einer guten Freundschaft.",
    listeningCheck: { prompt: "Was empfahl Ben zum Lernen?", answer: "Jeden Tag drei typische Sätze aufschreiben.", distractors: ["Jeden Tag drei Geschäfte besuchen.", "In der Pause nicht mehr Deutsch sprechen."], explanation: "Ben empfiehlt konkrete Sätze aus dem Alltag." }, writing: "Schreiben Sie einer Freundin über eine wichtige Begegnung: Situation, Person, Ablauf und warum die Begegnung für Sie wichtig war. Etwa 80–100 Wörter.",
    writingModel: "Hallo Mia, als ich nach Köln zog, kannte ich dort niemanden. Deshalb habe ich einen Kochkurs besucht. Dort lernte ich Mara kennen. Sie war freundlich und fragte mich nach meiner neuen Arbeit. Nach dem Kurs gingen wir zusammen ins Café und merkten, dass wir beide gern wandern. Seitdem treffen wir uns regelmäßig am Wochenende. Als ich krank war, brachte sie mir sogar Essen vorbei. Diese Begegnung war für mich wichtig, weil ich mich danach in der neuen Stadt weniger allein fühlte. Hast du auch einmal so eine Freundschaft erlebt? Liebe Grüße, Jonas",
    speaking: "Erzählen Sie von einer Person, die Ihnen geholfen hat: erstes Treffen, zwei Eigenschaften und ein konkretes Erlebnis.", speakingModel: "Als ich neu in Köln war, lernte ich Mara im Kochkurs kennen. Sie ist offen und zuverlässig. Einmal war ich krank und sie brachte mir Essen. Deshalb ist unsere Freundschaft für mich besonders wichtig. Wir müssen nicht immer dasselbe denken, aber wir hören einander zu.", interaction: "Sie möchten eine neue Person in Ihren Freundeskreis einladen. Planen Sie ein Treffen; berücksichtigen Sie Interessen, Kosten und eine Person, die niemanden kennt.", redemittel: [["Als ich …, habe ich …", "Erlebnis beginnen"], ["An ihr/ihm schätze ich besonders …", "Eigenschaft würdigen"], ["Danach haben wir …", "Erzählung fortsetzen"]], everyday: "Beschreiben Sie eine Person anhand einer Handlung statt nur mit Adjektiven: Sie ist zuverlässig, denn sie kommt immer pünktlich.", mission: "Fragen Sie eine Person nach einer wichtigen Begegnung. Fassen Sie ihre Geschichte in fünf verbundenen Sätzen zusammen und prüfen Sie die zeitliche Reihenfolge.",
  },
  {
    title: "Alltag, Gewohnheiten und Zeit", domain: "personal", outcome: "Termine organisieren, Gewohnheiten erklären und Prioritäten aushandeln.", function: "organize time and negotiate appointments",
    vocabulary: [["sich beeilen", "to hurry", "Morgens muss ich mich oft beeilen."], ["sich vorbereiten auf + Akkusativ", "to prepare for", "Ich bereite mich auf den Termin vor."], ["verschieben", "to postpone", "Wir müssen das Treffen verschieben."], ["die Priorität, -en", "priority", "Heute hat der Bericht Priorität."], ["sich erholen", "to recover", "Am Wochenende erhole ich mich."], ["rechtzeitig", "in time", "Bitte sagen Sie rechtzeitig Bescheid."]],
    grammar: ["Reflexive Verben", "seit/vor/in", "bevor/während", "Nebensatzwortstellung"], grammarExplanation: "Reflexive Verben: ich beeile mich, du beeilst dich, er beeilt sich. Mit einem Akkusativobjekt steht häufig Dativ: Ich wasche mir die Hände. Seit + Dativ nennt einen Zeitraum bis jetzt; vor + Dativ einen vergangenen Zeitpunkt; in + Dativ einen zukünftigen Zeitpunkt. Bevor und während leiten Nebensätze mit Verb am Ende ein.", grammarExample: "Bevor ich zur Arbeit gehe, bereite ich mich auf den Tag vor. Seit einem Monat plane ich feste Pausen.",
    grammarCheck: { prompt: "Welche Aussage beschreibt einen Zeitraum bis heute?", answer: "Seit einem Monat plane ich meine Woche.", distractors: ["Vor einem Monat plane ich heute meine Woche.", "In einem Monat habe ich gestern meine Woche geplant."], explanation: "Seit + Zeitraum verbindet den Beginn in der Vergangenheit mit der Gegenwart." }, connectors: [["bevor", "frühere Handlung"], ["während", "gleichzeitige Handlung"], ["zuerst", "Beginn einer Reihenfolge"]],
    reading: "Nina arbeitet vormittags und besucht abends einen Deutschkurs. Früher erledigte sie die Hausaufgaben kurz vor Kursbeginn. Oft musste sie sich beeilen und vergaß wichtige Aufgaben. Seit einem Monat plant sie sonntags ihre Woche. Sie schreibt feste Termine in einen Kalender und lässt jeden Tag eine halbe Stunde frei. Diese Zeit braucht sie, wenn etwas länger dauert als erwartet. Bevor sie eine neue Einladung annimmt, schaut sie in den Kalender. Trotzdem möchte sie nicht jede Minute planen. Am Samstag trifft sie spontan Freunde oder erholt sich zu Hause. Ihr wichtigster Tipp lautet: Nicht alles ist gleich dringend. Wenn eine Aufgabe wirklich Priorität hat, schaltet sie ihr Handy aus. Für kleine Aufgaben sammelt sie Ideen auf einer Liste und erledigt sie zusammen.",
    readingCheck: { prompt: "Warum lässt Nina täglich eine halbe Stunde frei?", answer: "Damit sie Zeit für unerwartete Verzögerungen hat.", distractors: ["Weil ihr Kurs nur eine halbe Stunde dauert.", "Damit sie alle festen Termine absagen kann."], explanation: "Sie nutzt diese Zeit, wenn etwas länger dauert als erwartet." },
    listening: "Hallo Nina, hier ist Paul. Unser Treffen morgen um fünf muss ich leider verschieben. Ich habe um halb fünf noch einen Termin bei der Arbeit, der ungefähr eine Stunde dauert. Könnten wir uns um sechs am Bahnhof treffen? Wenn das für dich zu spät ist, habe ich am Freitag ab vier Zeit. Bitte antworte heute Abend, damit ich den Tisch im Restaurant ändern kann. Wir müssen übrigens nicht sofort essen gehen. Ich würde vorher gern mit dir einen kurzen Spaziergang machen. Sag mir auch, ob du die Unterlagen für unser gemeinsames Projekt schon ausgedruckt hast. Ich bringe meinen Kalender mit, damit wir die nächsten Termine planen können.",
    listeningCheck: { prompt: "Was soll Nina heute Abend tun?", answer: "Auf Pauls neuen Terminvorschlag antworten.", distractors: ["Um fünf am Bahnhof warten.", "Am Freitag den Tisch für heute reservieren."], explanation: "Paul braucht die Antwort heute Abend, um die Reservierung zu ändern." }, writing: "Antworten Sie Paul. Wählen Sie einen Termin, erklären Sie Ihre Verfügbarkeit, reagieren Sie auf den Spaziergang und beantworten Sie die Frage zu den Unterlagen. Etwa 80–100 Wörter.",
    writingModel: "Hallo Paul, danke für deine Nachricht. Morgen um sechs kann ich leider nicht, weil mein Deutschkurs um halb sieben beginnt. Am Freitag ab vier habe ich aber Zeit. Wir könnten uns um halb fünf vor dem Bahnhof treffen und zuerst spazieren gehen. Danach würde ich gern mit dir essen. Die Unterlagen habe ich schon ausgedruckt und bringe sie mit. Außerdem nehme ich meinen Kalender mit, damit wir die nächsten Schritte besprechen können. Passt dir dieser Vorschlag? Bitte sag mir noch, welches Restaurant du ausgesucht hast. Viele Grüße, Nina",
    speaking: "Beschreiben Sie eine typische Woche und eine Gewohnheit, die Sie ändern möchten. Erklären Sie den Grund und einen ersten Schritt.", speakingModel: "Vormittags arbeite ich und abends lerne ich Deutsch. Früher begann ich die Hausaufgaben zu spät. Seit einem Monat plane ich feste Lernzeiten. Bevor ich anfange, schalte ich mein Handy aus. So kann ich mich besser konzentrieren und habe am Wochenende mehr freie Zeit.", interaction: "Planen Sie eine gemeinsame Lernwoche. Eine Person arbeitet in Schichten, die andere hat Kinder. Vereinbaren Sie zwei Termine und einen Ersatztermin.", redemittel: [["Könnten wir den Termin auf … verschieben?", "Termin ändern"], ["Das passt mir, weil …", "Verfügbarkeit erklären"], ["Falls etwas dazwischenkommt, …", "Ersatz vereinbaren"]], everyday: "Bestätigen Sie nach einer Terminänderung Datum, Uhrzeit und Ort zusammen, um Missverständnisse zu vermeiden.", mission: "Lesen Sie Ihren Kalender, hören Sie Pauls Nachricht und senden Sie eine verbindliche Bestätigung. Begründen Sie anschließend mündlich Ihre Wahl.",
  },
  {
    title: "Wohnen, Nachbarn und Zusammenleben", domain: "public", outcome: "Wohnprobleme beschreiben, Regeln verstehen und höflich um Abhilfe bitten.", function: "describe a housing problem and request action",
    vocabulary: [["die Nebenkosten (Plural)", "additional housing costs", "Die Nebenkosten sind in der Anzeige angegeben."], ["die Hausordnung, -en", "house rules", "Die Hausordnung hängt im Eingang."], ["die Reparatur, -en", "repair", "Die Reparatur dauert zwei Tage."], ["der Mangel, Mängel", "defect", "Ich melde den Mangel schriftlich."], ["Rücksicht nehmen auf + Akkusativ", "to consider others", "Wir nehmen Rücksicht auf die Nachbarn."], ["die Besichtigung, -en", "viewing", "Die Besichtigung ist am Freitag."]],
    grammar: ["Relativsätze: Nominativ/Akkusativ/Dativ", "Wechselpräpositionen", "Genitiv erkennen"], grammarExplanation: "Das Relativpronomen richtet sich in Geschlecht und Zahl nach dem Bezugswort, im Fall nach seiner Rolle im Relativsatz: der Nachbar, der hilft; der Nachbar, den ich kenne; der Nachbar, dem ich helfe. Wo? + Dativ: auf dem Tisch. Wohin? + Akkusativ: auf den Tisch. Nicht jede Bewegung bedeutet Ortswechsel: Ich laufe im Park. Genitiv erkennt man etwa in die Regeln des Hauses.", grammarExample: "Die Lampe, die im Flur hängt, ist kaputt. Ich stelle die neue Lampe in den Flur; sie steht jetzt im Flur.",
    grammarCheck: { prompt: "Ergänzen Sie: Das ist der Nachbar, ___ ich beim Umzug geholfen habe.", answer: "dem", distractors: ["den", "der"], explanation: "Helfen verlangt Dativ; maskulines Relativpronomen im Dativ: dem." }, connectors: [["dass", "Inhalt einer Bitte"], ["außerdem", "weiteres Problem"], ["trotzdem", "Gegensatz im Hauptsatz"]],
    reading: "Liebe Bewohnerinnen und Bewohner, nächste Woche wird die Beleuchtung im Treppenhaus erneuert. Die Firma, die den Auftrag übernimmt, arbeitet von Montag bis Mittwoch zwischen acht und sechzehn Uhr. Bitte stellen Sie keine Fahrräder oder Kartons in den Flur, damit die Mitarbeiter sicher arbeiten können. Der Raum im Keller, den Sie bisher für Fahrräder genutzt haben, bleibt geöffnet. Während der Arbeiten kann es kurzzeitig laut werden. Die Regeln des Hauses gelten weiterhin: Nach zweiundzwanzig Uhr bitten wir um Ruhe. Falls in Ihrer Wohnung eine Lampe flackert, melden Sie das bitte gesondert per E-Mail. Die Arbeiten betreffen nur die gemeinsamen Räume. Bei Fragen können Sie am Donnerstag zwischen zehn und zwölf Uhr unsere Sprechstunde besuchen. Vielen Dank für Ihre Rücksichtnahme. Ihre Hausverwaltung.",
    readingCheck: { prompt: "Was sollen Bewohner bei einer flackernden Lampe in ihrer Wohnung tun?", answer: "Eine gesonderte E-Mail an die Hausverwaltung schreiben.", distractors: ["Die Lampe ungefragt ins Treppenhaus stellen.", "Bis Mittwoch warten, weil alle Wohnungen renoviert werden."], explanation: "Die angekündigten Arbeiten betreffen nur gemeinsame Räume; private Probleme müssen gesondert gemeldet werden." },
    listening: "Guten Tag, Frau Berger, hier spricht Herr Klein aus dem zweiten Stock. Seit gestern funktioniert die Heizung im Schlafzimmer nicht richtig. Im Wohnzimmer ist es warm, aber im Schlafzimmer bleibt sie kalt. Ich habe bereits geprüft, ob das Fenster offen ist; es ist geschlossen. Könnten Sie bitte eine Fachperson schicken? Morgen bin ich bis elf Uhr zu Hause. Danach kann meine Nachbarin die Tür öffnen, wenn Sie mir vorher die Uhrzeit mitteilen. Bitte rufen Sie mich heute zurück. Es geht übrigens nicht um die Lampe im Flur, die nächste Woche repariert wird. Ich möchte die beiden Probleme getrennt melden, damit es kein Missverständnis gibt.",
    listeningCheck: { prompt: "Welches Problem meldet Herr Klein?", answer: "Die Heizung im Schlafzimmer bleibt kalt.", distractors: ["Die Heizung im Wohnzimmer bleibt kalt.", "Das Fenster im Flur lässt sich nicht schließen."], explanation: "Er unterscheidet ausdrücklich die kalte Schlafzimmerheizung von der Flurlampe." }, writing: "Schreiben Sie der Hausverwaltung: Problem seit wann, Auswirkungen, konkrete Bitte und zwei mögliche Besuchszeiten. Etwa 90–120 Wörter; höfliches Sie-Register.",
    writingModel: "Sehr geehrte Frau Berger, seit gestern bleibt die Heizung in meinem Schlafzimmer kalt. Im Wohnzimmer funktioniert sie normal. Das Fenster ist geschlossen, trotzdem ist es im Schlafzimmer unangenehm kühl. Ich bitte Sie deshalb, eine Fachperson mit der Prüfung zu beauftragen. Morgen bin ich bis elf Uhr zu Hause. Am Freitag könnte ich zwischen vierzehn und sechzehn Uhr jemanden empfangen. Falls beide Termine nicht passen, kann meine Nachbarin nach Absprache die Tür öffnen. Bitte teilen Sie mir vorher die genaue Uhrzeit mit, damit wir den Besuch organisieren können. Vielen Dank für Ihre Hilfe. Mit freundlichen Grüßen, Daniel Klein",
    speaking: "Beschreiben Sie Ihre Wohnung und ein Problem. Erklären Sie, wo es ist, seit wann es besteht und welche Hilfe Sie benötigen.", speakingModel: "Ich wohne im zweiten Stock. Die Heizung, die im Schlafzimmer steht, bleibt seit gestern kalt. Im Wohnzimmer ist alles in Ordnung. Ich möchte deshalb einen Reparaturtermin vereinbaren. Morgen bin ich bis elf zu Hause. Könnten Sie mir sagen, wann jemand kommen kann?", interaction: "Ein Nachbar hört abends laut Musik. Sie brauchen Ruhe, er möchte seinen Geburtstag feiern. Vereinbaren Sie eine Uhrzeit und eine Lösung für weitere Treffen.", redemittel: [["Seit … funktioniert … nicht.", "Mangel beschreiben"], ["Ich bitte Sie darum, …", "Abhilfe erbitten"], ["Könnten wir uns darauf einigen, dass …?", "Kompromiss finden"]], everyday: "Eine Problemmeldung nennt Ort, Beginn und konkrete Beobachtung. Vermeiden Sie unklare Sätze wie Alles ist kaputt.", mission: "Nutzen Sie Hausordnung und Nachricht, um zwei Probleme getrennt zu melden. Vereinbaren Sie mündlich einen Termin und bestätigen Sie ihn schriftlich.",
  },
  {
    title: "Arbeit und beruflicher Alltag", domain: "occupational", outcome: "Aufgaben erklären, sich bewerben und beruflich höflich nachfragen.", function: "apply for work and clarify responsibilities",
    vocabulary: [["die Bewerbung, -en", "application", "Ich sende meine Bewerbung per E-Mail."], ["die Schicht, -en", "shift", "Meine Schicht beginnt um acht."], ["zuständig für + Akkusativ", "responsible for", "Ich bin für die Bestellungen zuständig."], ["die Voraussetzung, -en", "requirement", "Erfahrung ist eine Voraussetzung."], ["die Rückmeldung, -en", "response", "Vielen Dank für Ihre Rückmeldung."], ["sich bewerben um + Akkusativ", "to apply for", "Ich bewerbe mich um die Stelle."]],
    grammar: ["Modalverben im Präsens/Präteritum", "Konjunktiv II: könnte/würde", "indirekte Fragen: ob/W-Fragen"], grammarExplanation: "Müssen nennt eine Pflicht, dürfen eine Erlaubnis, können eine Fähigkeit. Vergangenheit: Ich musste früh anfangen. Höfliche Bitte: Könnten Sie …? Indirekte Ja/Nein-Frage mit ob, andere Fragen mit Fragewort; Verb am Ende: Können Sie mir sagen, ob die Stelle noch frei ist? Ich möchte wissen, wann die Schicht beginnt.", grammarExample: "Könnten Sie mir sagen, welche Aufgaben ich übernehmen müsste?", grammarCheck: { prompt: "Welche Frage passt in eine formelle Bewerbung?", answer: "Könnten Sie mir sagen, ob die Stelle noch frei ist?", distractors: ["Sag mir sofort, die Stelle frei?", "Könnten Sie sagen mir, ob ist die Stelle frei?"], explanation: "Sie-Form und könnten sind höflich; im ob-Satz steht ist am Ende." }, connectors: [["ob", "indirekte Ja/Nein-Frage"], ["weil", "Motivation"], ["außerdem", "weitere Fähigkeit"]],
    reading: "Das Café Linden sucht eine Mitarbeiterin oder einen Mitarbeiter für den Service. Die Arbeitszeit beträgt zwanzig Stunden pro Woche, meistens am Vormittag und an zwei Samstagen im Monat. Zu den Aufgaben gehören Bestellungen aufnehmen, Getränke vorbereiten und Gäste beraten. Erfahrung im Service ist hilfreich, aber keine feste Voraussetzung. Wichtig sind Zuverlässigkeit und die Bereitschaft, im Team zu arbeiten. Neue Mitarbeitende erhalten eine Einführung und begleiten zuerst eine erfahrene Person. Bewerbungen mit einem kurzen Lebenslauf können bis Freitag per E-Mail geschickt werden. Bitte nennen Sie auch, ab wann Sie anfangen könnten. Wer nur am Abend Zeit hat, passt leider nicht zu dieser Stelle. Fragen zur Arbeitszeit beantwortet Frau Yilmaz telefonisch zwischen neun und elf Uhr. Die genaue Verteilung der Schichten wird im Vorstellungsgespräch besprochen.",
    readingCheck: { prompt: "Welche Person passt zu der Stelle?", answer: "Eine zuverlässige Person, die vormittags und manchmal samstags Zeit hat.", distractors: ["Eine Person, die ausschließlich abends arbeiten kann.", "Nur eine Person mit zehn Jahren Serviceerfahrung."], explanation: "Vormittage und zwei Samstage sind nötig; Erfahrung ist keine feste Voraussetzung." },
    listening: "Guten Morgen, hier ist Frau Yilmaz vom Café Linden. Vielen Dank für Ihre Bewerbung. Wir würden Sie gern am Donnerstag um zehn Uhr zu einem Gespräch einladen. Bitte bringen Sie Ihren Lebenslauf mit. Das Gespräch dauert ungefähr eine halbe Stunde. Danach können Sie das Team kurz kennenlernen. Es handelt sich noch nicht um einen Probearbeitstag. Wir möchten zuerst über Ihre Erfahrungen und mögliche Arbeitszeiten sprechen. Falls Sie am Donnerstag nicht kommen können, nennen Sie uns bitte zwei alternative Termine. Die Stelle beginnt frühestens im nächsten Monat. Sie müssen also diese Woche noch keine Schicht übernehmen. Bitte bestätigen Sie den Termin bis morgen per E-Mail.",
    listeningCheck: { prompt: "Was ist für Donnerstag geplant?", answer: "Ein Gespräch und ein kurzes Kennenlernen des Teams.", distractors: ["Eine vollständige Arbeitsschicht.", "Ein verpflichtender Probearbeitstag bis abends."], explanation: "Frau Yilmaz sagt ausdrücklich, dass es kein Probearbeitstag ist." }, writing: "Bestätigen Sie die Einladung. Nennen Sie eine passende Erfahrung, Ihre möglichen Arbeitszeiten und eine Rückfrage. Etwa 90–120 Wörter.",
    writingModel: "Sehr geehrte Frau Yilmaz, vielen Dank für Ihre Einladung. Gern komme ich am Donnerstag um zehn Uhr zum Gespräch und bringe meinen Lebenslauf mit. In meiner Heimat habe ich ein Jahr in einem kleinen Café gearbeitet. Dort war ich für Bestellungen und Getränke zuständig. Ich arbeite gern im Team und könnte im nächsten Monat anfangen. Vormittags habe ich regelmäßig Zeit; auch zwei Samstage im Monat wären möglich. Könnten Sie mir bitte sagen, ob ich zum Gespräch noch weitere Unterlagen mitbringen soll? Ich freue mich darauf, Sie und Ihr Team kennenzulernen. Mit freundlichen Grüßen, Ana López",
    speaking: "Erklären Sie in einem Vorstellungsgespräch Ihre Erfahrung, zwei Stärken und Ihre Verfügbarkeit. Stellen Sie eine Frage zur Einführung.", speakingModel: "Ich habe ein Jahr im Service gearbeitet und war für Bestellungen zuständig. Ich bin zuverlässig und arbeite gern mit anderen zusammen. Vormittags habe ich Zeit. Könnten Sie mir erklären, wie die Einführung abläuft? Am Anfang möchte ich die wichtigsten Aufgaben gut kennenlernen.", interaction: "Verteilen Sie Aufgaben für eine volle Caféschicht. Eine Kollegin kann die Kasse noch nicht bedienen. Planen Sie Hilfe und eine kurze Einführung.", redemittel: [["Ich bin für … zuständig.", "Aufgabe erklären"], ["Ich habe Erfahrung mit …", "Kompetenz nennen"], ["Könnten Sie mir mitteilen, ob …?", "formell nachfragen"]], everyday: "Fragen Sie nach, wenn eine Arbeitsanweisung unklar ist, und wiederholen Sie die Aufgabe samt Frist: Ich soll also bis zwölf …, richtig?", mission: "Lesen Sie die Stellenanzeige, reagieren Sie auf die Einladung und führen Sie ein kurzes Bewerbungsgespräch mit einer Rückfrage.",
  },
  {
    title: "Bildung und Lernen", domain: "educational", outcome: "Lernangebote vergleichen und Ziele mit Gründen und Zwecken erklären.", function: "compare learning options and explain purpose",
    vocabulary: [["der Abschluss, Abschlüsse", "qualification", "Ich möchte einen Abschluss machen."], ["die Weiterbildung, -en", "further training", "Die Weiterbildung findet abends statt."], ["die Teilnahme, -n", "participation", "Die Teilnahme kostet fünfzig Euro."], ["sich anmelden für + Akkusativ", "to register for", "Ich melde mich für den Kurs an."], ["die Fähigkeit, -en", "skill", "Ich verbessere meine Fähigkeiten."], ["selbstständig", "independently", "Ich lerne auch selbstständig."]],
    grammar: ["um … zu", "damit", "Infinitiv mit zu", "weil/deswegen"], grammarExplanation: "Um … zu nennt einen Zweck bei gleichem Subjekt: Ich lerne, um die Prüfung zu bestehen. Damit erlaubt ein anderes Subjekt: Ich erkläre es, damit du es verstehst. Nach planen/versuchen steht häufig zu + Infinitiv; bei trennbaren Verben dazwischen: teilzunehmen. Nach Modalverben kein zu: Ich möchte lernen. Deswegen beginnt einen Hauptsatz mit Verb auf Position zwei.", grammarExample: "Ich besuche den Kurs, um einen Abschluss zu machen. Die Lehrerin gibt Beispiele, damit wir die Regeln verstehen.", grammarCheck: { prompt: "Die Lehrerin spricht langsam. Die Lernenden sollen alles verstehen. Welche Verbindung passt?", answer: "Die Lehrerin spricht langsam, damit die Lernenden alles verstehen.", distractors: ["Die Lehrerin spricht langsam, um die Lernenden alles zu verstehen.", "Die Lehrerin spricht langsam, damit verstehen die Lernenden alles."], explanation: "Die Subjekte sind verschieden; damit + Nebensatz ist passend." }, connectors: [["um … zu", "Ziel bei gleichem Subjekt"], ["damit", "Ziel; auch verschiedene Subjekte"], ["deswegen", "Folge"]],
    reading: "Die Volkshochschule bietet zwei Computerkurse an. Kurs A findet dienstags im Unterrichtsraum statt und richtet sich an Menschen mit wenig Erfahrung. Die Lehrerin zeigt jeden Schritt, danach üben die Teilnehmenden gemeinsam. Kurs B ist ein Onlinekurs für Personen, die schon mit E-Mail und Textprogrammen arbeiten können. Die Übungen sind jederzeit verfügbar, einmal pro Woche gibt es eine digitale Sprechstunde. Beide Kurse dauern acht Wochen und kosten gleich viel. Lara arbeitet in wechselnden Schichten. Deshalb interessiert sie sich für Kurs B. Allerdings ist sie unsicher, ob ihre Kenntnisse ausreichen. Die Beratung empfiehlt ihr einen kurzen Einstufungstest, bevor sie sich anmeldet. Lara möchte nicht einfach den bequemsten Kurs wählen. Sie sucht ein Angebot, in dem sie genug Hilfe bekommt und trotzdem selbstständig üben kann.",
    readingCheck: { prompt: "Was soll Lara vor der Anmeldung tun?", answer: "Mit einem Einstufungstest ihre Vorkenntnisse prüfen.", distractors: ["Beide Kurse sofort bezahlen.", "Eine neue Lehrerin für Kurs A suchen."], explanation: "Die Beratung empfiehlt den Test, weil Lara ihre Kenntnisse nicht sicher einschätzen kann." },
    listening: "Liebe Teilnehmerinnen und Teilnehmer, ab nächster Woche gibt es eine zusätzliche Lernsprechstunde. Sie findet mittwochs um achtzehn Uhr online statt und dauert fünfundvierzig Minuten. Die Teilnahme ist freiwillig und kostet nichts extra. Bitte schicken Sie Ihre Fragen bis Dienstagabend, damit ich passende Beispiele vorbereiten kann. In der Sprechstunde lösen wir nicht alle Hausaufgaben gemeinsam. Wir besprechen typische Schwierigkeiten und überlegen, wie Sie selbstständig weiterüben können. Wenn Sie mittwochs arbeiten, finden Sie danach eine kurze Zusammenfassung im Kursraum. Eine Videoaufnahme gibt es nicht. Für persönliche Fragen zur Kurswahl können Sie außerdem einen Termin bei der Beratung vereinbaren.",
    listeningCheck: { prompt: "Was gibt es für Personen, die mittwochs arbeiten?", answer: "Eine kurze Zusammenfassung im Kursraum.", distractors: ["Eine Videoaufnahme jeder Sprechstunde.", "Einen verpflichtenden kostenpflichtigen Ersatzkurs."], explanation: "Eine Zusammenfassung wird bereitgestellt, eine Aufnahme ausdrücklich nicht." }, writing: "Fragen Sie bei der Kursberatung nach: Ihr Ziel, Ihre Vorkenntnisse, verfügbare Zeiten und eine Frage zum passenden Angebot. Etwa 90–120 Wörter.",
    writingModel: "Sehr geehrte Damen und Herren, ich interessiere mich für Ihre Computerkurse, um meine Fähigkeiten für den Beruf zu verbessern. Ich kann E-Mails schreiben und einfache Dokumente erstellen, brauche aber bei neuen Programmen noch Hilfe. Da ich in wechselnden Schichten arbeite, wäre ein Onlinekurs praktisch. Ich bin allerdings nicht sicher, ob meine Kenntnisse für Kurs B ausreichen. Könnten Sie mir mitteilen, wann ich den Einstufungstest machen kann? Außerdem möchte ich wissen, ob ich bei Schwierigkeiten persönliche Unterstützung bekomme. So könnte ich selbstständig lernen und trotzdem Fragen stellen. Vielen Dank für Ihre Beratung. Mit freundlichen Grüßen, Lara Beck",
    speaking: "Vergleichen Sie Lernen zu Hause und Lernen im Kurs. Nennen Sie Ihr Ziel, einen Vorteil jeder Möglichkeit und Ihre Wahl.", speakingModel: "Zu Hause kann ich lernen, wann ich Zeit habe. Im Kurs bekomme ich schneller Hilfe und kann mit anderen sprechen. Für mich wäre eine Mischung gut, weil ich in Schichten arbeite. Ich möchte den Onlinekurs besuchen, um meine beruflichen Fähigkeiten zu verbessern.", interaction: "Wählen Sie gemeinsam einen Kurs. Eine Person braucht feste Termine, die andere Flexibilität. Fragen Sie nach Vorkenntnissen und einigen Sie sich auf einen Lernplan.", redemittel: [["Ich möchte …, um … zu …", "Zweck"], ["Für mich wäre … geeignet, weil …", "begründete Wahl"], ["Welche Vorkenntnisse brauche ich?", "Zugang klären"]], everyday: "Unterscheiden Sie Anmeldung, Einstufung und Beratung. Fragen Sie nach Kosten, Voraussetzungen und Unterstützung, bevor Sie einen Kurs wählen.", mission: "Vergleichen Sie die zwei Kurse und die Lernsprechstunde. Begründen Sie eine passende Wahl für Lara und schlagen Sie ihr zwei konkrete Lernschritte vor.",
  },
  {
    title: "Gesundheit, Wohlbefinden und Lebensstil", domain: "personal", outcome: "Beschwerden erklären, einen Termin vereinbaren und vorsichtig Rat geben.", function: "describe symptoms and give advice",
    vocabulary: [["die Beschwerden (Plural)", "symptoms", "Die Beschwerden dauern seit Montag an."], ["die Untersuchung, -en", "examination", "Die Untersuchung ist am Donnerstag."], ["sich ausruhen", "to rest", "Ich möchte mich ausruhen."], ["die Ernährung", "nutrition", "Ich achte auf meine Ernährung."], ["die Bewegung", "exercise", "Mehr Bewegung hilft mir im Alltag."], ["vereinbaren", "to arrange", "Ich vereinbare einen Termin."]],
    grammar: ["Konjunktiv II: sollte/könnte", "Infinitiv mit zu", "Verben mit Präpositionen", "weil/deshalb"], grammarExplanation: "Sollte gibt einen vorsichtigen Rat: Du solltest eine Pause machen. Könnte nennt eine Möglichkeit. Es ist wichtig, regelmäßig zu schlafen: zu-Infinitiv nach einer Bewertung. Achten auf + Akkusativ: Ich achte auf meinen Schlaf. Sich beschäftigen mit + Dativ. Bei Sachen: darauf/damit; bei Personen: auf ihn/mit ihr. Sprachübungen ersetzen keine individuelle ärztliche Beratung.", grammarExample: "Du solltest einen Termin vereinbaren, weil die Beschwerden schon länger dauern.", grammarCheck: { prompt: "Welche Formulierung gibt einen vorsichtigen Rat?", answer: "Du solltest mit einer Ärztin über die Beschwerden sprechen.", distractors: ["Du musst niemals zu einer Ärztin gehen.", "Du solltest sprechen mit einer Ärztin die Beschwerden über."], explanation: "Solltest + Infinitiv ist eine passende Ratform; über die Beschwerden steht vor dem Infinitiv." }, connectors: [["weil", "Ursache"], ["deshalb", "Folge"], ["wenn", "Bedingung"]],
    reading: "Im Gesundheitskurs erzählt Eva, dass sie abends oft müde ist und trotzdem lange am Handy bleibt. Morgens fällt es ihr schwer aufzustehen. Der Kursleiter bittet die Gruppe, zunächst den eigenen Alltag zu beobachten. Niemand soll sofort einen perfekten Wochenplan erstellen. Eva notiert eine Woche lang, wann sie ins Bett geht und wann sie sich konzentriert fühlt. Danach möchte sie eine kleine Gewohnheit ändern: Das Handy bleibt abends außerhalb des Schlafzimmers. Außerdem plant sie einen kurzen Spaziergang nach der Arbeit. Ein anderer Teilnehmer hat seit längerer Zeit Schmerzen. Ihm empfiehlt der Kursleiter, einen ärztlichen Termin zu vereinbaren. Allgemeine Alltagstipps können eine persönliche Untersuchung nicht ersetzen. Eva findet es hilfreich, zwischen einer neuen Gewohnheit und Beschwerden zu unterscheiden, die sie genauer klären lassen sollte.",
    readingCheck: { prompt: "Was möchte Eva zuerst verändern?", answer: "Abends das Handy außerhalb des Schlafzimmers lassen.", distractors: ["Ohne Untersuchung Medikamente wechseln.", "Sofort jede Stunde ihres Lebens planen."], explanation: "Eva entscheidet sich für eine kleine, konkrete Gewohnheitsänderung." },
    listening: "Guten Tag, Sie sind mit der Praxis am Markt verbunden. Ihr Termin zur Untersuchung ist am Donnerstag um neun Uhr dreißig. Bitte kommen Sie zehn Minuten früher und bringen Sie Ihre Versicherungskarte sowie eine Liste Ihrer aktuellen Medikamente mit. Falls Sie den Termin nicht wahrnehmen können, rufen Sie uns bitte vorher an. Unsere telefonische Sprechzeit beginnt um acht Uhr. Die Praxis zieht nächste Woche nicht um; nur der Eingang wird renoviert. Benutzen Sie deshalb bitte den Seiteneingang neben der Apotheke. Dort steht ein Schild. Wenn Sie weitere Fragen haben, melden Sie sich bei unserem Team. Die Untersuchung findet wie geplant im ersten Stock statt.",
    listeningCheck: { prompt: "Welchen Eingang sollen Patientinnen am Donnerstag benutzen?", answer: "Den Seiteneingang neben der Apotheke.", distractors: ["Den Eingang einer neuen Praxis am Bahnhof.", "Den geschlossenen Haupteingang."], explanation: "Wegen Renovierung soll der Seiteneingang benutzt werden; die Praxis zieht nicht um." }, writing: "Sie können den Untersuchungstermin nicht wahrnehmen. Schreiben Sie der Praxis: Termin, Grund, Bitte um Änderung und zwei mögliche Zeiten. Etwa 80–100 Wörter.",
    writingModel: "Guten Tag, ich habe am Donnerstag um neun Uhr dreißig einen Termin zur Untersuchung bei Ihnen. Leider muss ich an diesem Vormittag arbeiten, weil eine Kollegin kurzfristig ausfällt. Deshalb möchte ich den Termin verschieben. Am Freitag könnte ich ab vierzehn Uhr kommen. In der nächsten Woche habe ich dienstags den ganzen Vormittag Zeit. Wäre einer dieser Termine möglich? Bitte teilen Sie mir mit, ob ich die Versicherungskarte und die Medikamentenliste auch zum neuen Termin mitbringen soll. Vielen Dank für Ihre Hilfe und Ihre Rückmeldung. Mit freundlichen Grüßen, Eva Müller",
    speaking: "Erklären Sie beim Empfang seit wann Sie Beschwerden haben, was im Alltag schwierig ist und wann Sie für einen Termin verfügbar sind.", speakingModel: "Seit Montag habe ich Beschwerden und möchte sie untersuchen lassen. Bei der Arbeit kann ich mich schwer konzentrieren. Am Freitag habe ich ab zwei Uhr Zeit. Könnten Sie mir einen Termin geben und sagen, was ich mitbringen soll?", interaction: "Ein Freund möchte seinen Alltag ruhiger gestalten. Fragen Sie nach seinem Tagesablauf und schlagen Sie zwei kleine Veränderungen vor. Erklären Sie, dass persönliche Beschwerden ärztlich geklärt werden sollten.", redemittel: [["Seit … habe ich …", "Dauer nennen"], ["Du könntest versuchen, … zu …", "vorsichtige Möglichkeit"], ["Könnten Sie den Termin verschieben?", "Praxis kontaktieren"]], everyday: "Bereiten Sie für einen Termin eine kurze Liste vor: seit wann, welche Beobachtung, welche Frage. Fragen Sie nach, wenn Sie eine Anweisung nicht verstehen.", mission: "Hören Sie die Praxisnachricht, planen Sie Ankunft und Unterlagen und formulieren Sie eine Terminänderung. Erklären Sie Ihre Beschwerden in verständlichen Sätzen.",
  },
  {
    title: "Reisen, Verkehr und Erlebnisse", domain: "public", outcome: "Eine Reise organisieren, Störungen verstehen und Erlebnisse in Reihenfolge erzählen.", function: "handle travel disruption and narrate experiences",
    vocabulary: [["die Unterkunft, Unterkünfte", "accommodation", "Wir suchen eine günstige Unterkunft."], ["der Anschluss, Anschlüsse", "connection", "Ich habe den Anschluss verpasst."], ["die Verspätung, -en", "delay", "Der Zug hat Verspätung."], ["stornieren", "to cancel a booking", "Ich muss die Buchung stornieren."], ["die Erstattung, -en", "refund", "Ich frage nach einer Erstattung."], ["umsteigen", "to change trains", "Wir steigen in Hannover um."]],
    grammar: ["Plusquamperfekt", "nachdem/bevor", "Präteritum/Perfekt", "indirekte Fragen"], grammarExplanation: "Erzählen Sie Ereignisse in einer klaren Reihenfolge. Nachdem + Plusquamperfekt markiert die frühere Handlung: Nachdem wir das Ticket gekauft hatten, fuhren wir los. Bei bevor ergibt sich die Reihenfolge oft aus der Konjunktion: Bevor wir losfuhren, kauften wir das Ticket. Fragen an den Service: Wissen Sie, wo der Ersatzbus abfährt?", grammarExample: "Nachdem ich den Anschluss verpasst hatte, fragte ich, wann der nächste Zug fährt.", grammarCheck: { prompt: "Was war zuerst passiert? Nachdem wir gebucht hatten, packten wir die Koffer.", answer: "Wir hatten zuerst gebucht.", distractors: ["Wir hatten zuerst die Koffer gepackt.", "Beide Handlungen liegen zwingend in der Zukunft."], explanation: "Das Plusquamperfekt nach nachdem beschreibt die frühere Handlung." }, connectors: [["nachdem", "früheres Ereignis"], ["danach", "nächstes Ereignis"], ["schließlich", "Ende der Erzählung"]],
    reading: "Letzten Samstag wollten Amir und Lea ein Wochenende in Bremen verbringen. Nachdem sie die Unterkunft gebucht hatten, kauften sie günstige Zugtickets. Am Reisetag fiel jedoch der erste Zug aus. Am Informationsschalter erfuhren sie, dass sie eine Verbindung eine Stunde später nehmen konnten. Lea rief die Unterkunft an und erklärte, dass sie später ankommen würden. Das war wichtig, weil die Rezeption nur bis achtzehn Uhr geöffnet war. Die Mitarbeiterin hinterlegte einen Schlüssel und schickte genaue Informationen zum Eingang. Schließlich erreichten Amir und Lea Bremen am frühen Abend. Obwohl der Anfang stressig gewesen war, hatten sie ein schönes Wochenende. Für die Rückfahrt prüften sie die Verbindung am Morgen noch einmal. Amir sagt, dass er künftig nicht nur die Fahrzeit, sondern auch mögliche Umstiege und die Öffnungszeiten der Unterkunft beachten möchte.",
    readingCheck: { prompt: "Warum rief Lea die Unterkunft an?", answer: "Weil die Rezeption nur bis achtzehn Uhr geöffnet war und sie später ankamen.", distractors: ["Weil sie keine Unterkunft gebucht hatten.", "Weil sie die gesamte Reise ohne Grund absagen wollten."], explanation: "Sie organisierte die Schlüsselübergabe wegen ihrer verspäteten Ankunft." },
    listening: "Achtung, eine Information für Fahrgäste des Regionalzuges nach Bremen. Aufgrund einer Störung endet dieser Zug heute in Verden. Für die Weiterfahrt steht ein Ersatzbus vor dem Haupteingang bereit. Der Bus fährt in zwanzig Minuten ab und benötigt ungefähr fünfundvierzig Minuten bis Bremen. Ihre Fahrkarte gilt auch im Ersatzbus. Reisende mit einem Anschluss nach Bremerhaven wenden sich bitte an das Servicepersonal auf Gleis zwei. Dort erhalten Sie Informationen zu einer anderen Verbindung. Bitte steigen Sie nicht in den Bus Richtung Hannover; dieser gehört zu einer anderen Linie. Wir bitten um Entschuldigung für die Verspätung und danken Ihnen für Ihre Geduld.",
    listeningCheck: { prompt: "Was sollen Fahrgäste mit Anschluss nach Bremerhaven tun?", answer: "Das Servicepersonal auf Gleis zwei nach einer anderen Verbindung fragen.", distractors: ["Den Bus Richtung Hannover ohne Rückfrage nehmen.", "Im Zug bis Bremen sitzen bleiben."], explanation: "Für diesen Anschluss gibt es eine besondere Anweisung an das Servicepersonal." }, writing: "Schreiben Sie Ihrer Gastgeberin: Änderung der Ankunft, Grund, Frage zur Schlüsselübergabe und Bitte um Bestätigung. Etwa 90–120 Wörter.",
    writingModel: "Sehr geehrte Frau Peters, wir haben für heute ein Zimmer bei Ihnen gebucht. Leider ist unser erster Zug ausgefallen. Nachdem wir am Schalter nachgefragt hatten, konnten wir eine spätere Verbindung nehmen. Wir kommen deshalb voraussichtlich erst gegen neunzehn Uhr in Bremen an. In Ihrer Nachricht steht, dass die Rezeption um achtzehn Uhr schließt. Könnten Sie uns bitte erklären, wie wir später unseren Schlüssel bekommen können? Außerdem möchten wir wissen, welchen Eingang wir benutzen sollen. Bitte bestätigen Sie kurz, ob die späte Ankunft möglich ist. Vielen Dank für Ihre Unterstützung. Mit freundlichen Grüßen, Amir Khan",
    speaking: "Erzählen Sie von einer Reise mit einem unerwarteten Problem. Verwenden Sie zuerst, nachdem, danach und schließlich.", speakingModel: "Zuerst hatten wir ein Zimmer gebucht. Dann fiel unser Zug aus. Nachdem wir am Schalter nachgefragt hatten, nahmen wir eine andere Verbindung. Ich rief die Unterkunft an, weil wir später ankamen. Schließlich bekamen wir den Schlüssel an einem anderen Eingang. Trotzdem war das Wochenende schön.", interaction: "Planen Sie einen Wochenendausflug mit 150 Euro pro Person. Eine Person möchte früh losfahren, die andere arbeitet samstags. Einigen Sie sich auf Verkehrsmittel, Unterkunft und Plan bei Verspätung.", redemittel: [["Wissen Sie, wo … abfährt?", "indirekt nachfragen"], ["Wir kommen voraussichtlich um … an.", "Ankunft mitteilen"], ["Obwohl …, war …", "Erlebnis bewerten"]], everyday: "Wiederholen Sie bei Durchsagen Ziel, Gleis, Ersatzverkehr und Abfahrtszeit. Wenn zwei Busse genannt werden, prüfen Sie die Richtung.", mission: "Verbinden Sie Zugdurchsage und Öffnungszeiten: planen Sie die Weiterfahrt, informieren Sie die Unterkunft und berichten Sie danach von der Lösung.",
  },
  {
    title: "Einkaufen, Geld und Dienstleistungen", domain: "public", outcome: "Angebote vergleichen und eine sachliche Reklamation formulieren.", function: "compare offers and complain politely",
    vocabulary: [["der Kassenbon, -s", "receipt", "Ich habe den Kassenbon aufbewahrt."], ["umtauschen", "to exchange", "Ich möchte die Jacke umtauschen."], ["die Gebühr, -en", "fee", "Für die Lieferung fällt eine Gebühr an."], ["der Vertrag, Verträge", "contract", "Ich lese den Vertrag vor der Unterschrift."], ["kündigen", "to cancel a contract", "Ich möchte den Vertrag kündigen."], ["das Angebot, -e", "offer", "Ich vergleiche zwei Angebote."]],
    grammar: ["Adjektivdeklination", "Komparativ/Superlativ", "Genitiv: des Vertrags", "lassen + Infinitiv"], grammarExplanation: "Adjektive tragen Endungen: der neue Vertrag, ein neuer Vertrag, mit einem neuen Vertrag. Vergleiche: günstiger als; so günstig wie; am günstigsten. Der Genitiv bezeichnet Zugehörigkeit: die Laufzeit des Vertrags. Lassen + Infinitiv: Ich lasse das Gerät reparieren = eine andere Person repariert es. Nach lassen kein zu.", grammarExample: "Der günstigere Vertrag hat eine höhere Gebühr. Ich lasse mein altes Handy reparieren.", grammarCheck: { prompt: "Ergänzen Sie: Ich interessiere mich für einen ___ Vertrag.", answer: "günstigen", distractors: ["günstiger", "günstige"], explanation: "Für verlangt Akkusativ. Nach einen trägt das maskuline Adjektiv die Endung -en." }, connectors: [["als", "Vergleich mit Komparativ"], ["obwohl", "Einräumung"], ["daher", "Folgerung"]],
    reading: "Milan braucht einen neuen Handyvertrag. Angebot A kostet monatlich zwölf Euro und enthält wenig Datenvolumen. Für zusätzliches Datenvolumen fällt eine Gebühr an. Angebot B kostet achtzehn Euro und bietet mehr Daten, hat aber eine längere Laufzeit. Milan nutzt zu Hause meistens WLAN, unterwegs braucht er sein Handy jedoch für Karten und Nachrichten. Im Geschäft empfiehlt man ihm zuerst den teureren Vertrag. Milan fragt nach den Gesamtkosten und der Kündigungsfrist, statt sofort zu unterschreiben. Außerdem überlegt er, ob er wirklich ein neues Handy braucht. Sein altes Gerät funktioniert, nur der Akku hält nicht mehr lange. Er möchte den Akku reparieren lassen und zunächst seinen tatsächlichen Verbrauch prüfen. So kann er entscheiden, welches Angebot zu seinem Alltag passt, ohne nur auf den großen Werbepreis zu schauen.",
    readingCheck: { prompt: "Was möchte Milan vor seiner Entscheidung prüfen?", answer: "Seinen tatsächlichen Datenverbrauch und die Vertragsbedingungen.", distractors: ["Nur die Farbe eines neuen Handys.", "Ob Werbung immer den gesamten Preis erklärt."], explanation: "Er fragt nach Gesamtkosten und Kündigungsfrist und will den Verbrauch prüfen." },
    listening: "Guten Tag, hier ist der Kundenservice. Wir haben Ihre Nachricht zum beschädigten Rucksack erhalten. Bitte schicken Sie uns ein Foto des Mangels und die Bestellnummer. Den Rucksack müssen Sie vorerst nicht zurücksenden. Sobald wir die Bilder geprüft haben, informieren wir Sie über den nächsten Schritt. Wenn eine Rücksendung nötig ist, erhalten Sie ein Rücksendeetikett per E-Mail. Bitte verpacken Sie den Rucksack dann ohne die anderen Artikel Ihrer Bestellung. Es geht bei dieser Nachricht nur um den beschädigten Artikel. Teilen Sie uns außerdem mit, ob Sie einen Ersatz wünschen oder lieber nach einer Erstattung fragen möchten. Wir melden uns innerhalb von drei Werktagen.",
    listeningCheck: { prompt: "Was soll die Kundin zuerst schicken?", answer: "Ein Foto des Mangels und die Bestellnummer.", distractors: ["Sofort alle bestellten Artikel.", "Nur eine neue Bestellung ohne Foto."], explanation: "Der Service prüft zunächst Fotos und Bestellnummer; die Rücksendung ist noch nicht nötig." }, writing: "Reklamieren Sie einen beschädigten Rucksack: Bestellung, genauer Mangel, bisherige Schritte und gewünschte Lösung. Etwa 90–120 Wörter.",
    writingModel: "Sehr geehrte Damen und Herren, gestern habe ich den Rucksack aus meiner Bestellung Nummer 245 erhalten. Leider ist der Reißverschluss an der vorderen Tasche beschädigt, sodass ich sie nicht schließen kann. Der Karton war bei der Lieferung unbeschädigt. Ich habe den Rucksack noch nicht benutzt und ein Foto des Mangels beigefügt. Da ich ihn für eine Reise nächste Woche brauche, würde ich gern einen Ersatz erhalten. Könnten Sie mir mitteilen, ob dieser rechtzeitig geliefert werden kann? Falls das nicht möglich ist, möchte ich nach einer Erstattung fragen. Bitte erklären Sie mir auch die nächsten Schritte. Mit freundlichen Grüßen, Milan Novak",
    speaking: "Vergleichen Sie zwei Angebote: monatlicher Preis, Zusatzkosten und Nutzen. Begründen Sie, welches besser zu Ihnen passt.", speakingModel: "Angebot A ist günstiger als Angebot B, hat aber weniger Datenvolumen. Ich nutze meistens WLAN, deshalb könnte A reichen. Trotzdem möchte ich erst die Zusatzgebühren prüfen. Das günstigste Angebot ist für mich nur sinnvoll, wenn die Gesamtkosten niedrig bleiben.", interaction: "Sie kaufen gemeinsam einen gebrauchten Computer. Vergleichen Sie Preis, Zustand und Reparaturmöglichkeiten und einigen Sie sich auf Fragen an den Verkäufer.", redemittel: [["Ich möchte einen Mangel melden.", "Reklamation beginnen"], ["Könnten Sie mir einen Ersatz anbieten?", "Lösung erfragen"], ["Im Vergleich zu … ist …", "Angebote vergleichen"]], everyday: "Unterscheiden Sie Werbung und Vertragsbedingungen. Notieren Sie Laufzeit, Preis und Zusatzgebühren. Übungsfälle stellen keine Rechtsberatung dar.", mission: "Lesen Sie zwei Angebote, hören Sie die Servicenachricht und verfassen Sie eine Reklamation mit einer konkreten Bitte. Begründen Sie Ihre gewünschte Lösung mündlich.",
  },
  {
    title: "Medien, Technik und Kommunikation", domain: "public", outcome: "Digitale Gewohnheiten beschreiben und Vor- und Nachteile begründen.", function: "express advantages and disadvantages",
    vocabulary: [["die Nachricht, -en", "message/news", "Ich prüfe die Nachricht vor dem Teilen."], ["die Quelle, -n", "source", "Die Quelle wird im Artikel genannt."], ["die Bildschirmzeit", "screen time", "Ich möchte meine Bildschirmzeit begrenzen."], ["der Datenschutz", "data protection", "Datenschutz ist mir wichtig."], ["herunterladen", "to download", "Ich lade die Datei herunter."], ["in Kontakt bleiben", "to stay in touch", "Wir bleiben über Nachrichten in Kontakt."]],
    grammar: ["obwohl/trotzdem", "dass/ob", "Verben mit Präpositionen", "Pronominaladverbien"], grammarExplanation: "Obwohl + Verb am Ende nennt einen Gegensatz; trotzdem beginnt einen Hauptsatz: Obwohl die App praktisch ist, nutze ich sie selten. Die App ist praktisch. Trotzdem nutze ich sie selten. Dass gibt einen Inhalt wieder, ob eine offene Ja/Nein-Frage. Über etwas sprechen → darüber sprechen; mit einer Person sprechen → mit ihr sprechen.", grammarExample: "Obwohl soziale Medien praktisch sind, mache ich Pausen. Ich bin nicht sicher, ob die Quelle zuverlässig ist.", grammarCheck: { prompt: "Verbinden Sie mit trotzdem: Die App ist praktisch. Ich benutze sie selten.", answer: "Die App ist praktisch. Trotzdem benutze ich sie selten.", distractors: ["Die App ist praktisch. Trotzdem ich sie selten benutze.", "Trotzdem die App praktisch ist, benutze selten ich sie."], explanation: "Nach trotzdem steht das finite Verb auf Position zwei." }, connectors: [["obwohl", "Gegensatz mit Nebensatz"], ["trotzdem", "Gegensatz mit Hauptsatz"], ["einerseits … andererseits", "zwei Perspektiven"]],
    reading: "In einem Kursforum diskutieren drei Personen über Smartphones. Lara findet ihr Handy praktisch, weil sie mit ihrer Familie im Ausland in Kontakt bleiben kann. Trotzdem legt sie es beim Essen weg. Ben nutzt viele Lernapps, ist aber unsicher, welche persönlichen Daten gespeichert werden. Er liest deshalb die Einstellungen und fragt nach, bevor er eine neue App verwendet. Sofia bekommt Nachrichten aus mehreren Gruppen und fühlt sich manchmal gestresst. Sie hat die Mitteilungen nachts ausgeschaltet. Alle drei möchten das Handy weiter nutzen, aber bewusster entscheiden. Im Forum schlagen sie vor, eine Woche lang die eigene Nutzung zu beobachten. Danach soll jede Person eine hilfreiche und eine störende Gewohnheit nennen. Es geht nicht darum, dass alle dieselbe Bildschirmzeit erreichen. Entscheidend ist, ob die Nutzung zum Alltag und zu den persönlichen Zielen passt.",
    readingCheck: { prompt: "Was ist das gemeinsame Ziel der drei Personen?", answer: "Das Handy bewusster nutzen und eigene Gewohnheiten prüfen.", distractors: ["Alle Smartphones dauerhaft abschaffen.", "Alle exakt dieselbe Bildschirmzeit erreichen."], explanation: "Sie wollen weiter nutzen, aber bewusst entscheiden; gleiche Zeiten sind ausdrücklich kein Ziel." },
    listening: "Willkommen beim Medienabend unserer Bibliothek. Heute zeigen wir, wie Sie Informationen im Internet prüfen können. Schauen Sie zuerst auf das Datum und darauf, wer einen Beitrag veröffentlicht hat. Suchen Sie danach eine zweite Quelle. Ein Foto allein beweist noch nicht, dass eine Behauptung stimmt. Im zweiten Teil sprechen wir über sichere Einstellungen am Smartphone. Bringen Sie Ihr Gerät mit, wenn Sie möchten; die Teilnahme ist auch ohne eigenes Handy möglich. Wir installieren keine neue App und fragen nicht nach Ihren Passwörtern. Der Abend beginnt um achtzehn Uhr und ist kostenlos. Eine Anmeldung ist nötig, weil der Raum nur zwanzig Plätze hat.",
    listeningCheck: { prompt: "Warum ist eine Anmeldung nötig?", answer: "Weil der Raum nur zwanzig Plätze hat.", distractors: ["Weil alle eine neue App kaufen müssen.", "Weil die Bibliothek Passwörter sammeln möchte."], explanation: "Die Teilnehmerzahl ist durch den Raum begrenzt." }, writing: "Schreiben Sie einen Forumbeitrag: Sind Smartphones im Unterricht hilfreich? Meinung, Grund, Beispiel, Nachteil und Schluss. Etwa 80–100 Wörter.",
    writingModel: "Meiner Meinung nach können Smartphones im Unterricht hilfreich sein, wenn es klare Regeln gibt. Mit einer Lernapp kann man neue Wörter wiederholen oder Informationen suchen. In meinem Kurs haben wir zum Beispiel gemeinsam eine Fahrplanauskunft gelesen. Das war praktisch und passte zum Alltag. Andererseits lenken Nachrichten schnell ab, und nicht jede Quelle ist zuverlässig. Deshalb sollten wir Mitteilungen ausschalten und Ergebnisse überprüfen. Ich finde also, dass ein vollständiges Verbot nicht nötig ist. Die Lehrkraft sollte aber erklären, wann wir das Handy benutzen dürfen und wann wir es weglegen sollen.",
    speaking: "Sprechen Sie ein bis zwei Minuten über Ihre Handynutzung: Erfahrung, Vorteil, Nachteil und eine Regel, die Sie sinnvoll finden.", speakingModel: "Ich nutze mein Handy zum Lernen und für meine Familie. Das ist praktisch, weil wir weit auseinander wohnen. Allerdings lese ich manchmal zu viele Nachrichten. Deshalb schalte ich abends die Mitteilungen aus. Im Unterricht finde ich Handys hilfreich, wenn die Aufgabe klar ist und wir die Quellen prüfen.", interaction: "Vereinbaren Sie Regeln für eine gemeinsame digitale Lerngruppe: Zeiten, Nachrichten, Quellenprüfung und Hilfe für Personen mit wenig Technikkenntnissen.", redemittel: [["Einerseits …, andererseits …", "abwägen"], ["Ein Vorteil ist, dass …", "Vorteil erklären"], ["Ich bin nicht sicher, ob …", "Unsicherheit ausdrücken"]], everyday: "Prüfen Sie Datum und Quelle vor dem Weitergeben einer Nachricht. Fragen Sie bei einer unklaren Behauptung: Woher stammt diese Information?", mission: "Vergleichen Sie die drei Forumpositionen mit den Tipps aus der Bibliothek und erstellen Sie eine eigene begründete Medienregel.",
  },
  {
    title: "Umwelt und nachhaltiger Alltag", domain: "public", outcome: "Alltagsmaßnahmen vergleichen und Bedingungen sowie Folgen erklären.", function: "propose sustainable everyday choices",
    vocabulary: [["der Müll", "waste", "Wir trennen den Müll."], ["vermeiden", "to avoid", "Ich vermeide unnötige Verpackungen."], ["die Verpackung, -en", "packaging", "Diese Verpackung kann man wiederverwenden."], ["Energie sparen", "to save energy", "Wir möchten Energie sparen."], ["die Maßnahme, -n", "measure", "Die Maßnahme ist leicht umzusetzen."], ["wiederverwenden", "to reuse", "Ich verwende die Tasche wieder."]],
    grammar: ["wenn/falls", "Passiv Präsens", "werden + Infinitiv", "deshalb"], grammarExplanation: "Wenn/falls + Nebensatz nennt eine Bedingung. Passiv: werden + Partizip II beschreibt eine Handlung ohne Fokus auf den Handelnden: Der Müll wird getrennt. Zukunft: werden + Infinitiv: Wir werden die Ergebnisse vergleichen. Oft genügt Präsens + Zeitangabe: Nächste Woche sammeln wir Ideen. Vergleichen Sie wird repariert (Passiv) und wird reparieren (Zukunft).", grammarExample: "Wenn alle mitmachen, wird weniger Müll produziert. Nächsten Monat werden wir die Ergebnisse vergleichen.", grammarCheck: { prompt: "Welche Aussage steht im Passiv?", answer: "Die alten Geräte werden repariert.", distractors: ["Wir werden die Geräte reparieren.", "Wir reparieren die alten Geräte."], explanation: "Werden + Partizip II (repariert) bildet das Vorgangspassiv." }, connectors: [["falls", "mögliche Bedingung"], ["deshalb", "Folge"], ["wenn", "Bedingung"]],
    reading: "Die Hausgemeinschaft am Park möchte weniger Abfall produzieren. Bei einem Treffen werden drei Ideen vorgestellt: ein Tauschregal, gemeinsame Stofftaschen und eine kleine Reparaturgruppe. Das Tauschregal kann sofort im Gemeinschaftsraum stehen. Es muss aber regelmäßig geprüft werden, damit keine kaputten Gegenstände dort liegen bleiben. Die Taschen sind leicht zu benutzen, doch einige Bewohner besitzen schon genügend eigene Taschen. Für die Reparaturgruppe gibt es zwei Freiwillige; ein fester Termin fehlt noch. Die Gruppe entscheidet sich zunächst für das Regal und einen monatlichen Reparaturabend. Nach drei Monaten möchte sie prüfen, ob die Angebote tatsächlich genutzt werden. Wenn kaum jemand teilnimmt, sollen die Zeiten geändert werden. Die Bewohner wollen keine großen Versprechen machen, sondern kleine Maßnahmen testen, die im Alltag funktionieren und von mehreren Personen betreut werden können.",
    readingCheck: { prompt: "Was passiert nach drei Monaten?", answer: "Die Hausgemeinschaft prüft, ob die Angebote genutzt werden.", distractors: ["Alle müssen neue Stofftaschen kaufen.", "Das Haus wird ohne Prüfung verkauft."], explanation: "Die Gruppe plant eine Auswertung und gegebenenfalls andere Zeiten." },
    listening: "Am Samstag findet unser erster Reparaturabend im Gemeinschaftsraum statt. Wir beginnen um sechzehn Uhr und helfen bei einfachen Reparaturen an Kleidung und Fahrrädern. Elektrische Geräte nehmen wir diesmal nicht an, weil dafür eine geeignete Fachperson fehlt. Bitte melden Sie vorher, was Sie mitbringen möchten. Werkzeug ist vorhanden; besondere Ersatzteile müssen Sie selbst besorgen. Falls Sie nichts reparieren lassen möchten, können Sie trotzdem beim Sortieren oder beim Kaffee helfen. Für das Tauschregal suchen wir außerdem eine Person, die einmal pro Woche nach dem Rechten sieht. Der Abend ist kostenlos. Eine Spende für das gemeinsame Werkzeug ist freiwillig.",
    listeningCheck: { prompt: "Warum werden elektrische Geräte diesmal nicht angenommen?", answer: "Weil eine geeignete Fachperson fehlt.", distractors: ["Weil jede Reparatur kostenpflichtig ist.", "Weil alle Geräte schon repariert sind."], explanation: "Die Ansage begrenzt das Angebot auf Kleidung und Fahrräder." }, writing: "Schlagen Sie der Hausgemeinschaft zwei Maßnahmen vor. Begründen Sie Nutzen, notwendige Hilfe und einen Termin zur Auswertung. Etwa 100–120 Wörter.",
    writingModel: "Liebe Nachbarinnen und Nachbarn, ich finde ein Tauschregal und einen Reparaturabend sinnvoll. Im Regal können wir Dinge weitergeben, die noch gut funktionieren. So müssen wir nicht alles neu kaufen. Allerdings sollte jede Woche jemand prüfen, ob die Gegenstände sauber und brauchbar sind. Ich könnte diese Aufgabe im ersten Monat übernehmen. Außerdem würde ich einen Reparaturabend am Samstag vorschlagen, weil viele dann Zeit haben. Für elektrische Geräte brauchen wir vorher eine Fachperson. Nach drei Monaten sollten wir gemeinsam prüfen, wie viele Menschen teilgenommen haben. Falls die Angebote kaum genutzt werden, könnten wir andere Zeiten ausprobieren. Viele Grüße, Sara",
    speaking: "Erklären Sie eine umweltfreundliche Gewohnheit: Was tun Sie, warum, was ist schwierig und welche Alternative haben Sie?", speakingModel: "Ich fahre oft mit dem Fahrrad, weil mein Weg kurz ist. Wenn es stark regnet, nehme ich den Bus. Das ist nicht immer bequem, aber ich spare Geld. In unserer Hausgemeinschaft möchte ich außerdem Dinge tauschen, statt alles neu zu kaufen. Dafür brauchen wir klare Regeln und Menschen, die sich kümmern.", interaction: "Wählen Sie zwei Maßnahmen für eine Hausgemeinschaft mit kleinem Budget. Verteilen Sie Aufgaben und vereinbaren Sie, wie Sie den Erfolg prüfen.", redemittel: [["Falls …, könnten wir …", "Alternative"], ["Dadurch können wir …", "Folge"], ["Ich würde vorschlagen, dass …", "Vorschlag"]], everyday: "Lesen Sie lokale Hinweise zur Mülltrennung. Regeln können sich je nach Ort unterscheiden; fragen Sie bei unbekannten Symbolen nach.", mission: "Lesen Sie den Hausbericht und hören Sie die Einladung. Melden Sie eine passende Sache an und schlagen Sie einen Plan für Betreuung und Auswertung vor.",
  },
  {
    title: "Gesellschaft und Zusammenleben", domain: "public", outcome: "Über Gemeinschaft sprechen, Perspektiven verstehen und höflich widersprechen.", function: "discuss community life and mediate perspectives",
    vocabulary: [["das Ehrenamt, Ehrenämter", "voluntary role", "Sie übernimmt ein Ehrenamt."], ["die Unterstützung, -en", "support", "Die Gruppe bietet Unterstützung."], ["die Gemeinschaft, -en", "community", "Unsere Gemeinschaft trifft sich regelmäßig."], ["teilnehmen an + Dativ", "to take part in", "Ich nehme an einem Treffen teil."], ["die Regel, -n", "rule", "Wir besprechen die Regeln gemeinsam."], ["die Rücksicht", "consideration", "Gegenseitige Rücksicht ist wichtig."]],
    grammar: ["Relativsätze mit Präposition", "nicht nur … sondern auch", "weil/obwohl", "Nomen-Verb-Verbindungen"], grammarExplanation: "Präposition und Relativpronomen gehören zusammen: die Gruppe, mit der ich arbeite; das Treffen, an dem ich teilnehme. Nicht nur … sondern auch verbindet zusätzliche Aspekte. Feste Verbindungen: Hilfe anbieten, Verantwortung übernehmen, eine Entscheidung treffen. Beschreiben Sie konkrete Situationen und vermeiden Sie pauschale Aussagen über ganze Gruppen.", grammarExample: "Die Gruppe, in der ich mitarbeite, bietet nicht nur Sprachhilfe, sondern auch gemeinsame Ausflüge an.", grammarCheck: { prompt: "Ergänzen Sie: Das ist die Gruppe, mit ___ ich zusammenarbeite.", answer: "der", distractors: ["die", "den"], explanation: "Mit verlangt Dativ; die Gruppe ist feminin: mit der." }, connectors: [["nicht nur … sondern auch", "ergänzen"], ["obwohl", "Einräumung"], ["außerdem", "zusätzlicher Punkt"]],
    reading: "Das Nachbarschaftszentrum bietet einen offenen Treff am Mittwoch an. Neue und langjährige Bewohner können dort Fragen zum Alltag stellen oder eigene Ideen vorstellen. Einige Freiwillige helfen beim Lesen von Formularen, andere organisieren gemeinsame Spaziergänge. Das Zentrum möchte keine persönliche Beratung ersetzen, sondern Kontakte ermöglichen und auf passende Stellen hinweisen. Bei einem Treffen entsteht eine Diskussion über die Öffnungszeiten. Berufstätige wünschen sich einen Abendtermin, während ältere Teilnehmende lieber am Nachmittag kommen. Die Leiterin bittet beide Gruppen, ihre Gründe zu erklären. Schließlich wird für zwei Monate ein zusätzlicher Abend ausprobiert. Danach soll geprüft werden, wer ihn nutzt. Alle sind eingeladen mitzuhelfen, aber niemand muss jede Woche teilnehmen. Wichtig ist, Aufgaben so zu verteilen, dass einzelne Freiwillige nicht dauerhaft überlastet werden.",
    readingCheck: { prompt: "Wie wird der Konflikt um die Öffnungszeiten gelöst?", answer: "Ein zusätzlicher Abendtermin wird zwei Monate lang getestet.", distractors: ["Der Nachmittagstreff wird sofort endgültig geschlossen.", "Alle Freiwilligen müssen täglich arbeiten."], explanation: "Die Gruppe wählt eine befristete zusätzliche Öffnung und anschließende Prüfung." },
    listening: "Hallo, ich bin Karim und arbeite ehrenamtlich im Nachbarschaftszentrum. Am Anfang half ich jeden Mittwoch bei Formularen. Das wurde neben meiner Arbeit bald zu viel. Deshalb habe ich mit der Leiterin gesprochen. Jetzt komme ich nur zweimal im Monat und teile die Aufgabe mit einer anderen Person. Ich finde es wichtig, dass wir unsere Grenzen offen nennen. Wer neu mitmachen möchte, muss nicht sofort alles können. Man kann zuerst bei einem Treffen zuschauen und danach eine kleine Aufgabe übernehmen. Besonders gefällt mir, dass ich Menschen aus verschiedenen Lebenssituationen kennenlerne. Wir sind nicht immer einer Meinung, aber wir versuchen zuzuhören und konkrete Lösungen zu finden.",
    listeningCheck: { prompt: "Warum kommt Karim jetzt nur zweimal im Monat?", answer: "Weil die wöchentliche Aufgabe neben seiner Arbeit zu viel wurde.", distractors: ["Weil das Zentrum keine Freiwilligen mehr braucht.", "Weil neue Personen nicht zuschauen dürfen."], explanation: "Er hat seine Grenzen angesprochen und teilt die Aufgabe jetzt." }, writing: "Schreiben Sie dem Zentrum: Interesse, mögliche Aufgabe, Ihre verfügbare Zeit und eine Frage zum Einstieg. Etwa 100–120 Wörter.",
    writingModel: "Guten Tag, ich habe von Ihrem offenen Nachbarschaftstreff gehört und würde gern mithelfen. Ich kann gut organisieren und könnte bei gemeinsamen Spaziergängen oder beim Vorbereiten des Raums unterstützen. Da ich berufstätig bin, habe ich allerdings nur an zwei Mittwochen im Monat Zeit. Ich möchte zuverlässig helfen, ohne Aufgaben zu übernehmen, die ich später nicht schaffen kann. Wäre es möglich, zuerst bei einem Treffen zuzuschauen? Außerdem würde ich gern wissen, mit wem ich die Aufgaben besprechen kann. Ich freue mich darauf, neue Menschen kennenzulernen und etwas für die Nachbarschaft zu tun. Vielen Dank für Ihre Rückmeldung. Freundliche Grüße, Mira Weber",
    speaking: "Erklären Sie, ob Sie ehrenamtlich mitarbeiten möchten. Nennen Sie ein Beispiel, einen Vorteil und eine persönliche Grenze.", speakingModel: "Ich würde gern im Nachbarschaftszentrum helfen, weil ich neue Menschen kennenlernen möchte. Ich könnte Spaziergänge organisieren. Allerdings arbeite ich viel und hätte nur zweimal im Monat Zeit. Deshalb finde ich es wichtig, Aufgaben zu teilen. So können wir zuverlässig helfen, ohne uns zu überlasten.", interaction: "Planen Sie einen offenen Treff für Personen mit unterschiedlichen Arbeitszeiten. Hören Sie beide Wünsche an und schlagen Sie eine Testphase vor.", redemittel: [["Ich verstehe Ihren Punkt, aber …", "höflich widersprechen"], ["Da stimme ich Ihnen zu.", "zustimmen"], ["Wir könnten zunächst … ausprobieren.", "gemeinsame Lösung"]], everyday: "Fragen Sie bei Formularen nach Zweck und zuständiger Stelle. Erklären Sie Ihre eigene Situation, statt Informationen über andere zu vermuten.", mission: "Fassen Sie die zwei Wünsche zu den Öffnungszeiten fair zusammen. Schreiben Sie einen Vorschlag und teilen Sie Aufgaben für eine zweimonatige Testphase zu.",
  },
  {
    title: "Kultur, Unterhaltung und Freizeit", domain: "personal", outcome: "Ein Angebot beschreiben, bewerten und passend empfehlen.", function: "review and recommend a cultural activity",
    vocabulary: [["die Veranstaltung, -en", "event", "Die Veranstaltung beginnt um sieben."], ["die Ausstellung, -en", "exhibition", "Die Ausstellung zeigt alte Stadtfotos."], ["empfehlen", "to recommend", "Ich empfehle dir den Film."], ["enttäuscht", "disappointed", "Vom Ende war ich enttäuscht."], ["beeindruckend", "impressive", "Die Bilder waren beeindruckend."], ["die Ermäßigung, -en", "discount", "Studierende bekommen eine Ermäßigung."]],
    grammar: ["Adjektivdeklination wiederholen", "Relativsätze", "Komparativ/Superlativ", "während"], grammarExplanation: "Beschreiben Sie mit passenden Adjektivendungen: eine interessante Ausstellung, die alten Bilder. Trennen Sie Beschreibung und Bewertung: Der Film dauert neunzig Minuten (Information); ich fand ihn spannend (Meinung). Relativsätze ergänzen Details. Während kann Gleichzeitigkeit oder einen Gegensatz ausdrücken: Während ich Bilder mag, interessiert sich Ben für Musik.", grammarExample: "Die Ausstellung, die ich besucht habe, war interessanter als erwartet. Besonders beeindruckend fand ich die alten Fotos.", grammarCheck: { prompt: "Ergänzen Sie: Wir haben eine ___ Ausstellung besucht.", answer: "interessante", distractors: ["interessanten", "interessanter"], explanation: "Eine + femininer Akkusativ: eine interessante Ausstellung." }, connectors: [["besonders", "Schwerpunkt"], ["allerdings", "Einschränkung"], ["während", "Vergleich oder Gleichzeitigkeit"]],
    reading: "Die Ausstellung Stadtgeschichten zeigt Fotos und kurze Interviews aus den letzten fünfzig Jahren. Besuchende erfahren, wie sich Geschäfte, Verkehr und Freizeit verändert haben. Lea fand besonders die persönlichen Erinnerungen interessant. Sie konnte an einem Bildschirm auswählen, welche Geschichte sie hören wollte. Einige Texte waren jedoch klein gedruckt und schwer zu lesen. Ihr Freund Ben interessierte sich mehr für die alten Straßenkarten. Beide empfehlen die Ausstellung, wenn man etwas über den Alltag früherer Bewohner erfahren möchte. Für kleine Kinder gibt es eine Suchaufgabe, aber nicht alle Räume sind dafür geeignet. Der Eintritt kostet sechs Euro, Studierende zahlen vier Euro. Am Sonntag um elf Uhr findet eine Führung statt, für die man sich zusätzlich anmelden muss. Lea möchte beim nächsten Besuch ihre Nachbarin mitnehmen, die schon lange in der Stadt lebt.",
    readingCheck: { prompt: "Welche Einschränkung nennt Lea?", answer: "Einige Texte waren klein gedruckt und schwer lesbar.", distractors: ["Es gab überhaupt keine persönlichen Geschichten.", "Studierende zahlen mehr als alle anderen."], explanation: "Ihre positive Empfehlung enthält eine konkrete Einschränkung zur Lesbarkeit." },
    listening: "Guten Abend und willkommen im Kulturhaus. Das Konzert beginnt heute wegen einer technischen Verzögerung erst um neunzehn Uhr dreißig. Die Türen zum Saal werden um neunzehn Uhr geöffnet. Ihre reservierten Plätze bleiben erhalten. Wer nicht warten kann, wendet sich bitte an die Kasse; dort erklären wir die möglichen nächsten Schritte. Im Foyer gibt es bis zum Beginn kostenlose Getränke. Die Lesung im kleinen Saal findet dagegen wie geplant um achtzehn Uhr dreißig statt. Bitte achten Sie also darauf, für welche Veranstaltung Sie ein Ticket haben. Nach dem Konzert können Sie an einem kurzen Gespräch mit den Musikerinnen teilnehmen. Dafür brauchen Sie keine zusätzliche Anmeldung.",
    listeningCheck: { prompt: "Welche Veranstaltung beginnt später?", answer: "Das Konzert beginnt erst um neunzehn Uhr dreißig.", distractors: ["Die Lesung beginnt erst um zwanzig Uhr.", "Alle Veranstaltungen wurden abgesagt."], explanation: "Die Verzögerung betrifft nur das Konzert; die Lesung findet planmäßig statt." }, writing: "Empfehlen Sie einer Freundin eine Ausstellung oder einen Film: Beschreibung, persönliche Erfahrung, positiver Punkt, Einschränkung und Empfehlung. Etwa 100–120 Wörter.",
    writingModel: "Hallo Nora, gestern habe ich die Ausstellung Stadtgeschichten besucht und möchte sie dir empfehlen. Sie zeigt alte Fotos und Interviews mit Menschen aus unserer Stadt. Besonders interessant fand ich die Erinnerungen an frühere Geschäfte, weil ich viele Straßen heute ganz anders kenne. Man kann selbst auswählen, welche Geschichten man hören möchte. Allerdings waren einige Texte sehr klein gedruckt. Nimm deshalb genug Zeit mit und frage bei Bedarf nach Hilfe. Für Studierende kostet der Eintritt vier Euro. Am Sonntag gibt es außerdem eine Führung, für die man sich anmelden muss. Vielleicht könnten wir gemeinsam hingehen und danach über unsere Eindrücke sprechen. Liebe Grüße, Lea",
    speaking: "Empfehlen Sie eine Veranstaltung. Nennen Sie Zielgruppe, Beschreibung, Ihre Erfahrung, einen Vorteil und eine Einschränkung.", speakingModel: "Ich empfehle die Ausstellung Stadtgeschichten. Dort sieht man alte Fotos und hört persönliche Erinnerungen. Mir hat gefallen, dass ich die Geschichten selbst auswählen konnte. Allerdings waren einige Texte schwer zu lesen. Für Menschen, die unsere Stadt besser kennenlernen möchten, ist die Ausstellung trotzdem interessant.", interaction: "Wählen Sie für drei Freunde eine Veranstaltung. Eine Person hat wenig Geld, eine mag Musik, eine interessiert sich für Geschichte. Vergleichen Sie zwei Ideen.", redemittel: [["Besonders gefallen hat mir …", "bewerten"], ["Ich würde … empfehlen, weil …", "empfehlen"], ["Allerdings sollte man beachten, dass …", "einschränken"]], everyday: "Prüfen Sie bei Veranstaltungen Beginn, Einlass, Ermäßigungen und zusätzliche Anmeldung. Diese Informationen können unterschiedlich sein.", mission: "Kombinieren Sie Ausstellungsinformation und Veranstaltungsansage zu einem passenden Freizeitplan mit einer Alternative bei Verzögerung.",
  },
  {
    title: "Probleme, Entscheidungen und Lösungen", domain: "personal", outcome: "Einen Konflikt erklären, Optionen vergleichen und einen Kompromiss finden.", function: "negotiate a solution and give hypothetical advice",
    vocabulary: [["der Kompromiss, -e", "compromise", "Wir suchen einen Kompromiss."], ["der Vorschlag, Vorschläge", "suggestion", "Ich mache einen Vorschlag."], ["sich entscheiden für + Akkusativ", "to choose", "Wir entscheiden uns für einen Test."], ["der Konflikt, -e", "conflict", "Wir sprechen über den Konflikt."], ["die Lösung, -en", "solution", "Die Lösung passt für beide."], ["vereinbaren", "to agree", "Wir vereinbaren neue Regeln."]],
    grammar: ["Konjunktiv II: würde/hätte/wäre/könnte/sollte", "wenn: hypothetisch", "lassen", "indirekte Fragen"], grammarExplanation: "Konjunktiv II beschreibt Wünsche, Möglichkeiten und gedachte Situationen: Wenn ich mehr Zeit hätte, würde ich öfter kochen. Häufige Formen: wäre, hätte, könnte, sollte. Würde + Infinitiv ist oft einfacher. Realität und gedachte Alternative unterscheiden. Lassen: Wir lassen die Regel zunächst unverändert; ich lasse das Gerät reparieren.", grammarExample: "Wenn wir einen Wochenplan hätten, könnten wir die Aufgaben gerechter teilen.", grammarCheck: { prompt: "Welche Aussage beschreibt eine gedachte Möglichkeit?", answer: "Wenn ich mehr Zeit hätte, würde ich öfter kochen.", distractors: ["Wenn ich mehr Zeit hatte, würde kochen ich öfter.", "Wenn ich mehr Zeit hätte, ich würde öfter kochen."], explanation: "Hätte steht am Nebensatzende; im folgenden Hauptsatz steht würde vor dem Subjekt." }, connectors: [["wenn", "gedachte Bedingung"], ["einerseits … andererseits", "Optionen abwägen"], ["stattdessen", "Alternative"]],
    reading: "In einer Wohngemeinschaft gibt es Streit über den gemeinsamen Haushalt. Tom möchte einen festen Putzplan, weil die Küche oft schmutzig bleibt. Jana arbeitet in wechselnden Schichten und findet feste Tage schwierig. Bei einem Gespräch erklären beide zuerst, was sie stört. Tom ärgert sich nicht über eine einzelne Tasse, sondern darüber, dass er regelmäßig die ganze Küche aufräumt. Jana möchte helfen, braucht aber flexible Zeiten. Sie schlagen vor, Aufgaben statt einzelner Tage zu verteilen. Jede Person erledigt ihre Aufgabe bis Sonntagabend und sagt frühzeitig Bescheid, wenn es nicht klappt. Nach vier Wochen wollen sie den Plan gemeinsam prüfen. Beide wissen, dass eine Regel allein den Konflikt nicht löst. Sie müssen auch regelmäßig darüber sprechen und anerkennen, wenn die andere Person sich bemüht. So wird aus einer Beschwerde ein überprüfbarer gemeinsamer Versuch.",
    readingCheck: { prompt: "Welchen Kompromiss wählen Tom und Jana?", answer: "Aufgaben mit einer Wochenfrist statt festen Putztagen verteilen.", distractors: ["Tom soll dauerhaft alles allein machen.", "Jana muss unabhängig von ihren Schichten täglich morgens putzen."], explanation: "Die Aufgaben werden bis Sonntag erledigt und nach vier Wochen überprüft." },
    listening: "Hallo zusammen, ich möchte noch einmal über unseren Gruppenraum sprechen. Wir können ihn am Freitag ab achtzehn Uhr nutzen, müssen ihn aber bis einundzwanzig Uhr aufräumen. Einige möchten dort einen Filmabend machen, andere würden lieber gemeinsam kochen. Für beides am selben Abend reicht die Zeit nicht. Mein Vorschlag wäre, diese Woche den Film zu sehen und nächste Woche zu kochen. Wenn wir früher anfangen könnten, wäre auch mehr Zeit zum Reden da, aber der Raum ist vorher belegt. Bitte schreibt bis morgen, ob ihr mit der Reihenfolge einverstanden seid. Falls jemand eine andere Idee hat, sollte er auch erklären, wie sie innerhalb der verfügbaren Zeit funktionieren würde.",
    listeningCheck: { prompt: "Warum können Kochen und Film nicht am selben Abend stattfinden?", answer: "Die verfügbare Zeit reicht für beides nicht.", distractors: ["Der Raum ist überhaupt nicht verfügbar.", "Alle Teilnehmenden dürfen nur morgens kommen."], explanation: "Der Raum ist erst ab achtzehn Uhr verfügbar und muss bis einundzwanzig Uhr aufgeräumt sein." }, writing: "Schreiben Sie der Wohngemeinschaft einen Lösungsvorschlag: Problem ohne Vorwurf, zwei Optionen, Ihre Wahl mit Grund und Zeitpunkt zur Überprüfung. Etwa 100–120 Wörter.",
    writingModel: "Liebe Mitbewohnerinnen und Mitbewohner, in letzter Zeit bleibt die Küche oft unaufgeräumt. Ich wünsche mir eine Lösung, mit der wir alle zufrieden sind. Wir könnten feste Putztage vereinbaren oder die Aufgaben für jede Woche verteilen. Da Jana in Schichten arbeitet, wäre die zweite Möglichkeit flexibler. Jede Person könnte ihre Aufgabe bis Sonntagabend erledigen. Wenn jemand keine Zeit hat, sollte er früh Bescheid sagen und um einen Tausch bitten. Ich würde diesen Plan gern vier Wochen ausprobieren. Danach könnten wir gemeinsam besprechen, ob die Aufgaben gerecht verteilt sind und was wir ändern sollten. Was denkt ihr darüber? Viele Grüße, Tom",
    speaking: "Beschreiben Sie einen Konflikt ohne Vorwurf. Stellen Sie zwei Möglichkeiten vor und begründen Sie einen Kompromiss.", speakingModel: "Unsere Küche bleibt oft schmutzig. Ich möchte nicht einer Person die Schuld geben. Wir könnten feste Tage wählen, aber das wäre bei Schichtarbeit schwierig. Deshalb schlage ich Aufgaben mit einer Wochenfrist vor. Wenn jemand Hilfe braucht, kann er früh fragen. Nach vier Wochen sollten wir prüfen, ob der Plan funktioniert.", interaction: "Entscheiden Sie gemeinsam zwischen Filmabend und Kochen bei begrenzter Raumzeit. Reagieren Sie auf einen Einwand und halten Sie das Ergebnis fest.", redemittel: [["Wie wäre es, wenn wir …?", "Vorschlag"], ["Ich verstehe, dass …", "Perspektive anerkennen"], ["Darauf könnten wir uns einigen.", "Ergebnis bestätigen"]], everyday: "Benennen Sie Beobachtung, Auswirkung und Wunsch: Die Küche ist oft unaufgeräumt; ich brauche morgens Platz; könnten wir …?", mission: "Vermitteln Sie zwischen Tom und Jana. Nehmen Sie ihre Gründe auf, schlagen Sie eine Testregel vor und schreiben Sie eine klare Vereinbarung.",
  },
  {
    title: "Meinungen, Diskussionen und Präsentationen", domain: "public", outcome: "Eine kurze Präsentation gliedern, eine Position begründen und auf Fragen reagieren.", function: "present a familiar topic and defend an opinion",
    vocabulary: [["die Meinung, -en", "opinion", "Ich erkläre meine Meinung."], ["der Vorteil, -e", "advantage", "Ein Vorteil ist die flexible Zeit."], ["der Nachteil, -e", "disadvantage", "Ein Nachteil sind die Kosten."], ["das Beispiel, -e", "example", "Ich nenne ein Beispiel aus meinem Alltag."], ["begründen", "to justify", "Ich begründe meinen Vorschlag."], ["zustimmen", "to agree", "In diesem Punkt stimme ich dir zu."]],
    grammar: ["meiner Meinung nach + Verbzweitstellung", "dass", "Konnektoren im Haupt-/Nebensatz", "mehrteilige Satzverbindungen"], grammarExplanation: "Meiner Meinung nach zählt als erstes Satzglied: Meiner Meinung nach sind Bücher wichtig. Ich bin der Meinung, dass … verlangt Verb am Ende. Eine Präsentation verbindet Einleitung, Erfahrung, Situation im Herkunftsland, Vor-/Nachteile und Meinung. Nutzen Sie einfache, richtige Verbindungen statt möglichst lange Sätze. Einerseits/andererseits beginnen jeweils Hauptsätze mit Verb auf Position zwei.", grammarExample: "Meiner Meinung nach sollten Bibliotheken länger öffnen. Obwohl das mehr Personal braucht, hätten Berufstätige mehr Zeit zum Lernen.", grammarCheck: { prompt: "Welche Aussage hat die richtige Wortstellung?", answer: "Meiner Meinung nach sollten Bibliotheken länger öffnen.", distractors: ["Meiner Meinung nach Bibliotheken sollten länger öffnen.", "Ich denke, dass sollten Bibliotheken länger öffnen."], explanation: "Nach dem ersten Satzglied folgt das finite Verb sollten; nach dass stünde es am Ende." }, connectors: [["meiner Meinung nach", "Position"], ["zum Beispiel", "Beleg"], ["schließlich", "Schluss"]],
    reading: "Im Stadtforum wird diskutiert, ob die Bibliothek sonntags öffnen sollte. Nora findet die Idee gut, weil sie unter der Woche lange arbeitet. In einer ruhigen Bibliothek könnte sie lesen und lernen, ohne zu Hause abgelenkt zu werden. Ben stimmt ihr teilweise zu, weist aber auf das Personal hin. Eine längere Öffnung braucht Geld und Menschen, die dann arbeiten. Er schlägt eine monatliche Testöffnung statt jeden Sonntag vor. Aylin möchte außerdem wissen, ob überhaupt genug Besucher kommen würden. Die Gruppe entscheidet sich, zuerst eine Umfrage zu machen und danach einen befristeten Versuch zu planen. Nora bereitet eine kurze Präsentation für das nächste Treffen vor. Sie möchte nicht nur ihre eigene Meinung nennen, sondern auch Bens Einwand fair darstellen und erklären, wie ein kleiner Versuch die offenen Fragen klären könnte.",
    readingCheck: { prompt: "Warum schlägt Ben eine monatliche Testöffnung vor?", answer: "Er unterstützt die Idee teilweise, berücksichtigt aber Personal und Kosten.", distractors: ["Er möchte jede Bibliothek dauerhaft schließen.", "Er weiß schon sicher, dass niemand kommen würde."], explanation: "Ben wägt Nutzen gegen Aufwand ab; der Test soll offene Fragen klären." },
    listening: "Bei Ihrer Präsentation müssen Sie nicht alles auswendig lernen. Beginnen Sie mit dem Thema und sagen Sie kurz, welche Punkte folgen. Erzählen Sie dann von einer eigenen Erfahrung und vergleichen Sie sie mit einer Situation, die Sie aus Ihrem Herkunftsland kennen. Nennen Sie anschließend einen Vorteil und einen Nachteil. Zum Schluss erklären Sie Ihre Meinung und bedanken sich für das Zuhören. Schreiben Sie nur Stichpunkte auf, damit Sie frei sprechen können. Nach der Präsentation hören Sie eine Frage. Wenn sie unklar ist, dürfen Sie um Wiederholung bitten. Antworten Sie mit einem konkreten Beispiel. Auch beim Zuhören haben Sie eine Aufgabe: Geben Sie eine kurze Rückmeldung und stellen Sie eine passende Frage zum Inhalt.",
    listeningCheck: { prompt: "Warum soll man nur Stichpunkte vorbereiten?", answer: "Damit man während der Präsentation frei sprechen kann.", distractors: ["Damit man keine eigene Meinung nennt.", "Damit man nachher keine Fragen beantworten muss."], explanation: "Die Hinweise raten zu Stichpunkten statt auswendig gelerntem Text." }, writing: "Schreiben Sie im Stadtforum: Soll die Bibliothek sonntags öffnen? Meinung, eigene Erfahrung, Grund, Gegenargument und Lösungsvorschlag. Etwa 80–100 Wörter.",
    writingModel: "Meiner Meinung nach sollte unsere Bibliothek einen Sonntag im Monat öffnen. Ich arbeite unter der Woche lange und habe dann wenig Zeit zum Lernen. Eine Sonntagsöffnung wäre deshalb hilfreich. In der Bibliothek kann ich mich besser konzentrieren als zu Hause. Allerdings verstehe ich den Einwand, dass zusätzliches Personal und Geld nötig sind. Deshalb würde ich zunächst einen Versuch von drei Monaten vorschlagen. Danach könnten wir Besucherzahlen und Kosten vergleichen. Wenn das Angebot kaum genutzt wird, sollten wir es ändern. So berücksichtigen wir sowohl die Wünsche der Besucher als auch die Möglichkeiten des Teams.",
    speaking: "Präsentieren Sie Sollten Bibliotheken sonntags öffnen? Gliedern Sie: Thema, eigene Erfahrung, Situation in Ihrem Herkunftsland, Vor-/Nachteile und Meinung. Stellen Sie sich anschließend zwei Rückfragen.", speakingModel: "Ich spreche über Sonntagsöffnungen. Zuerst erzähle ich von meiner Erfahrung. Unter der Woche arbeite ich lange und finde selten Ruhe zum Lernen. In meiner Heimat sind viele Bibliotheken sonntags geschlossen. Ein Vorteil längerer Öffnungen wäre mehr Zeit für Berufstätige. Ein Nachteil sind zusätzliche Kosten. Meiner Meinung nach wäre ein monatlicher Versuch sinnvoll. Danach könnten wir prüfen, ob genug Menschen kommen. Vielen Dank fürs Zuhören.", interaction: "Hören Sie einer Partnerin zu. Geben Sie eine konkrete positive Rückmeldung, stellen Sie eine Frage zum Inhalt und beantworten Sie danach ihre Frage zu Ihrer eigenen Position.", redemittel: [["Zuerst möchte ich über … sprechen.", "Präsentation eröffnen"], ["In meinem Herkunftsland …", "Vergleich"], ["Vielen Dank für die Frage. Ich denke, dass …", "auf Rückfrage reagieren"]], everyday: "Trennen Sie persönliche Erfahrung, Meinung und überprüfbare Information. Wenn Sie etwas nicht wissen, sagen Sie es offen und bleiben Sie beim Thema.", mission: "Halten Sie eine dreiminütige Präsentation. Lassen Sie eine Person eine Rückfrage stellen, reagieren Sie spontan und verbessern Sie danach eine unklare Stelle Ihrer Aufnahme.",
  },
  {
    title: "B1-Mastery · Selbstständig kommunizieren", domain: "public", outcome: "Informationen aus mehreren Quellen verbinden, handeln und eigene Schwächen gezielt bearbeiten.", function: "integrate skills and assess readiness",
    vocabulary: [["die Vorbereitung, -en", "preparation", "Unsere Vorbereitung beginnt heute."], ["die Verantwortung, -en", "responsibility", "Wir teilen die Verantwortung."], ["die Rückfrage, -n", "follow-up question", "Ich stelle eine Rückfrage zum Budget."], ["der Ersatz, -e", "replacement", "Wir planen einen Ersatz bei Regen."], ["überprüfen", "to check", "Wir überprüfen die Ergebnisse."], ["sich einigen auf + Akkusativ", "to agree on", "Wir einigen uns auf einen Termin."]],
    grammar: ["Zeitformen konsolidieren", "Relativsätze", "Konjunktiv II", "Passiv", "Konnektoren konsolidieren"], grammarExplanation: "Prüfen Sie zuerst die Kommunikationsabsicht, dann Register und Satzbau. Für Gründe weil/denn; für Folgen deshalb; für Gegensätze obwohl/trotzdem; für Bedingungen wenn/falls; für Ziele damit/um … zu. Vergangenes mit Perfekt und häufigem Präteritum, Vorvergangenheit bei Bedarf mit Plusquamperfekt. Wiederholen Sie die Kapitel zu Strukturen, die in Ihrer eigenen Produktion unsicher bleiben.", grammarExample: "Obwohl der Park günstig wäre, wählen wir den Raum, der bei Regen genutzt werden kann. Die Aufgaben werden morgen verteilt.", grammarCheck: { prompt: "Welche Aussage verbindet Gegensatz und Folge korrekt?", answer: "Obwohl der Park schön ist, wählen wir wegen des Regens den Saal. Deshalb brauchen wir eine Reservierung.", distractors: ["Obwohl der Park ist schön, deshalb wir wählen den Saal.", "Trotzdem es regnet, wir den Saal wählen."], explanation: "Obwohl stellt ist ans Nebensatzende; deshalb verlangt im Hauptsatz Verbzweitstellung." }, connectors: [["obwohl", "Gegensatz"], ["damit", "Ziel"], ["falls", "Ersatzplan"]],
    reading: "Der Deutschkurs möchte einen Begegnungsnachmittag für neue Teilnehmende organisieren. Zur Wahl stehen der Stadtpark und ein Raum im Nachbarschaftszentrum. Im Park fallen keine Raumkosten an, aber es gibt keinen zuverlässigen Schutz vor Regen. Der Raum kostet vierzig Euro und bietet Platz für zwanzig Personen. Die Gruppe hat ein Budget von sechzig Euro. Getränke und ein kleiner Imbiss müssen davon ebenfalls bezahlt werden. Amina schlägt vor, den Raum zu reservieren und jede Person um einen freiwilligen Beitrag zum Essen zu bitten. Leo möchte zuerst wissen, ob die geplante Uhrzeit passt. Deshalb wird eine kurze Nachricht an alle geschickt. Die Gruppe braucht außerdem zwei Personen für den Aufbau und eine Person, die neue Gäste begrüßt. Bis Donnerstag soll ein endgültiger Plan stehen, damit rechtzeitig eine Einladung verschickt werden kann.",
    readingCheck: { prompt: "Wie viel bleibt vom Budget nach der Raummiete?", answer: "Zwanzig Euro für Getränke und Imbiss.", distractors: ["Vierzig Euro zusätzlich zur Miete.", "Sechzig Euro, weil der Raum kostenlos ist."], explanation: "Budget 60 Euro minus 40 Euro Raummiete ergibt 20 Euro." },
    listening: "Hallo zusammen, ich habe beim Nachbarschaftszentrum nachgefragt. Der Raum ist am Samstag frei, aber erst ab fünfzehn Uhr. Wir können ihn bis achtzehn Uhr nutzen und müssen danach noch aufräumen. Eine Küche steht diesmal nicht zur Verfügung. Bringt deshalb bitte Speisen mit, die wir nicht aufwärmen müssen. Tische und Stühle sind vorhanden. Die Gebühr beträgt wie angekündigt vierzig Euro und wird am Freitag bezahlt. Amina kann den Schlüssel um vierzehn Uhr dreißig abholen, braucht aber Hilfe beim Aufbau. Leo kommt erst um sechzehn Uhr und kann dafür am Ende aufräumen. Bitte bestätigt eure Aufgabe bis Donnerstagabend. Danach schreibe ich die endgültige Einladung mit Zeit und Adresse.",
    listeningCheck: { prompt: "Welche neue Einschränkung muss die Gruppe berücksichtigen?", answer: "Es gibt keine Küche; Speisen dürfen kein Aufwärmen brauchen.", distractors: ["Der Raum kostet plötzlich sechzig Euro.", "Es gibt keine Tische und Stühle."], explanation: "Die Ansage bestätigt Preis und Möbel, nennt aber die fehlende Küche." }, writing: "Schreiben Sie die endgültige Einladung: Anlass, Samstag 15–18 Uhr im Nachbarschaftszentrum, Essen ohne Aufwärmen, Aufgaben und Bitte um Rückmeldung. Etwa 100–120 Wörter.",
    writingModel: "Liebe Kursteilnehmerinnen und Kursteilnehmer, am Samstag möchten wir unsere neuen Mitglieder bei einem Begegnungsnachmittag begrüßen. Wir treffen uns von fünfzehn bis achtzehn Uhr im Nachbarschaftszentrum. Der Raum bietet Platz für zwanzig Personen. Da wir keine Küche nutzen können, bringt bitte einen kleinen Imbiss mit, den man kalt essen kann. Die Beiträge zum Essen sind freiwillig. Amina holt den Schlüssel und braucht noch eine Person für den Aufbau. Leo hilft am Ende beim Aufräumen. Wer könnte die neuen Gäste begrüßen? Bitte bestätigt eure Teilnahme und eine mögliche Aufgabe bis Donnerstagabend. Die genaue Adresse schicke ich euch mit der Bestätigung. Wir freuen uns auf einen schönen Nachmittag! Viele Grüße, Sara",
    speaking: "Empfehlen Sie Park oder Innenraum: Budget, Wetter, Zeit und Aufgaben. Geben Sie Gründe, nehmen Sie einen Einwand auf und schlagen Sie einen Ersatzplan vor.", speakingModel: "Ich empfehle den Raum, obwohl er vierzig Euro kostet. Im Park wäre es günstiger, aber bei Regen hätten wir ein Problem. Für Getränke bleiben zwanzig Euro. Wir könnten kalte Speisen freiwillig mitbringen. Amina braucht Hilfe beim Aufbau; Leo kann aufräumen. Falls zu viele Personen kommen möchten, sollten wir vorher nach einer zweiten Veranstaltung fragen.", interaction: "Planen Sie den Nachmittag gemeinsam. Eine Person achtet auf Geld, die andere auf Gäste und Wetter. Klären Sie alle offenen Punkte und bestätigen Sie die Aufgaben.", redemittel: [["Wenn ich Sie richtig verstanden habe, …", "Information prüfen"], ["Wir haben uns darauf geeinigt, dass …", "Ergebnis sichern"], ["Als nächsten Schritt werden wir …", "Plan abschließen"]], everyday: "Erstellen Sie nach einer Besprechung eine kurze Bestätigung mit wer, was und bis wann. Benennen Sie offene Punkte ausdrücklich.", mission: "Lesen, hören, planen, schreiben und präsentieren Sie den Begegnungsnachmittag. Vergleichen Sie Ihre neue Aufnahme mit Kapitel 1. Prüfen Sie die fünf Fertigkeiten erneut und wählen Sie vor dem Prüfungsweg zwei gezielte Wiederholungen.",
  },
];

export const germanB1Sources = [
  { title: "Goethe B1 · Format und Zeiten", url: "https://www.goethe.de/ins/de/en/prf/prf/gzb1/inf.html" },
  { title: "Goethe B1 · offizielle Übungsmaterialien", url: "https://www.goethe.de/ins/de/de/prf/prf/gzb1/ueb.html" },
  { title: "Goethe B1 · Sprechen", url: "https://bfu.goethe.de/b1_mod/sprechen.php" },
  { title: "telc Deutsch B1 · Format und offizieller Übungstest", url: "https://www.telc.net/en/language-examinations/certificate-exams/german/certificate-german-telc-german-b1/" },
];
