/** Fresh, original situations for the shared A1 knowledge check. Keep each
 * transcript beside its question so the recording and answer cannot drift. */
export const germanA1FinalListening = [
  {
    chapter: 1,
    audioUrl: "/audio/german-a1/a1-final-hoeren-01.m4a",
    transcript: "Telefonnotiz: Guten Tag. Mein Name ist Mara Klein. Ich buchstabiere den Nachnamen: K, L, E, I, N.",
    prompt: "Welchen Nachnamen buchstabiert die Anruferin?",
    answers: ["Klein", "Klee", "Kling"], correctIndex: 0,
    explanation: "Die Anruferin buchstabiert K, L, E, I, N: Klein.",
  },
  {
    chapter: 3,
    audioUrl: "/audio/german-a1/a1-final-hoeren-02.m4a",
    transcript: "Eddy: Mein Bruder Tim ist achtundzwanzig Jahre alt. Er arbeitet an der Rezeption in einem Hotel.",
    prompt: "Wo arbeitet Eddys Bruder Tim?",
    answers: ["In einer Schule", "In einem Hotel", "In einer Apotheke"], correctIndex: 1,
    explanation: "Im Hörtext arbeitet Tim an der Rezeption in einem Hotel.",
  },
  {
    chapter: 4,
    audioUrl: "/audio/german-a1/a1-final-hoeren-03.m4a",
    transcript: "Telefonnotiz: Guten Tag. Ihr Deutschkurs beginnt heute ausnahmsweise um achtzehn Uhr fünfzehn, nicht um achtzehn Uhr.",
    prompt: "Wann beginnt der Deutschkurs heute?",
    answers: ["Um 18:00 Uhr", "Um 18:50 Uhr", "Um 18:15 Uhr"], correctIndex: 2,
    explanation: "Heute beginnt der Kurs um achtzehn Uhr fünfzehn.",
  },
  {
    chapter: 6,
    audioUrl: "/audio/german-a1/a1-final-hoeren-04.m4a",
    transcript: "Gespräch: Das Käsebrot kostet vier Euro und das Wasser zwei Euro. Zusammen sind das sechs Euro.",
    prompt: "Was kosten Käsebrot und Wasser zusammen?",
    answers: ["6 Euro", "4 Euro", "2 Euro"], correctIndex: 0,
    explanation: "Vier Euro für das Brot und zwei Euro für Wasser ergeben sechs Euro.",
  },
  {
    chapter: 8,
    audioUrl: "/audio/german-a1/a1-final-hoeren-05.m4a",
    transcript: "Anna: Entschuldigung, wo ist die Post? Eddy: Gehen Sie geradeaus. Die Post ist neben der Bank, gegenüber der Apotheke.",
    prompt: "Wo ist die Post?",
    answers: ["Im Bahnhof", "Neben der Bank", "Hinter der Schule"], correctIndex: 1,
    explanation: "Eddy sagt: Die Post ist neben der Bank.",
  },
  {
    chapter: 9,
    audioUrl: "/audio/german-a1/a1-final-hoeren-06.m4a",
    transcript: "Ansage eins: Der Regionalzug nach Bonn fährt heute um vierzehn Uhr fünfunddreißig von Gleis sechs ab.",
    prompt: "Von welchem Gleis fährt der Zug nach Bonn?",
    answers: ["Gleis vier", "Gleis fünf", "Gleis sechs"], correctIndex: 2,
    explanation: "Die Durchsage nennt Gleis sechs.",
  },
  {
    chapter: 10,
    audioUrl: "/audio/german-a1/a1-final-hoeren-07.m4a",
    transcript: "Telefonnotiz: Unser Deutschkurs am Abend findet montags und mittwochs um achtzehn Uhr dreißig statt.",
    prompt: "An welchen Tagen ist der Abendkurs?",
    answers: ["Montag und Mittwoch", "Dienstag und Donnerstag", "Samstag und Sonntag"], correctIndex: 0,
    explanation: "Die Sprachschule nennt Montag und Mittwoch.",
  },
  {
    chapter: 11,
    audioUrl: "/audio/german-a1/a1-final-hoeren-08.m4a",
    transcript: "Anna: Wir treffen uns am Samstag um sechzehn Uhr im Park. Bei Regen treffen wir uns um siebzehn Uhr im Café.",
    prompt: "Es regnet am Samstag. Wo treffen sich die Freunde?",
    answers: ["Im Park", "Im Café", "In der Schule"], correctIndex: 1,
    explanation: "Bei Regen nennt Anna das Café als Treffpunkt.",
  },
  {
    chapter: 12,
    audioUrl: "/audio/german-a1/a1-final-hoeren-09.m4a",
    transcript: "Telefonnotiz: Ihr Termin in der Praxis ist morgen um neun Uhr. Bitte bringen Sie Ihre Versicherungskarte mit.",
    prompt: "Was soll die Person zum Termin mitbringen?",
    answers: ["Das Kursbuch", "Die Fahrkarte", "Die Versicherungskarte"], correctIndex: 2,
    explanation: "Die Praxis bittet um die Versicherungskarte.",
  },
  {
    chapter: 14,
    audioUrl: "/audio/german-a1/a1-final-hoeren-10.m4a",
    transcript: "Telefonnotiz: Ihr Termin am Dienstag um elf Uhr findet jetzt am Donnerstag um zehn Uhr statt. Bitte antworten Sie bis Mittwoch.",
    prompt: "Wann ist der neue Termin?",
    answers: ["Donnerstag um 10 Uhr", "Dienstag um 11 Uhr", "Mittwoch um 10 Uhr"], correctIndex: 0,
    explanation: "Der Termin wurde auf Donnerstag um zehn Uhr verschoben.",
  },
] as const;
