import type { B1Question } from "./german-b1-curriculum.ts";

const q = (prompt: string, answer: string, wrong1: string, wrong2: string, explanation: string): B1Question => ({ prompt, answer, distractors: [wrong1, wrong2], explanation });
export const b1FreshReading = {
  blog: "Am Samstag wollte ich zum ersten Mal beim Gemeinschaftsgarten mithelfen. In der Einladung stand, dass wir eigene Handschuhe mitbringen sollten. Ich hatte keine und wollte deshalb schon absagen. Die Organisatorin schrieb mir jedoch, dass sie für neue Teilnehmende einige Paare ausleihen könne. Als ich ankam, regnete es leicht. Trotzdem arbeiteten wir draußen weiter, weil die jungen Pflanzen dringend in die Erde mussten. Zuerst sollte ich mit Paul ein Beet vorbereiten. Dann bemerkten wir, dass der Wasserhahn nicht funktionierte. Paul ging zum Hausmeister und ich holte Wasser aus einem Behälter. Nach einer Stunde hörte der Regen auf. Wir machten eine kurze Pause und besprachen, wer in der kommenden Woche gießen könnte. Ich kann nur am Mittwochabend kommen. Das passte gut, denn für diesen Tag fehlte noch jemand. Zum Abschied bot mir die Organisatorin Gemüse an, aber ich nahm nichts mit: Die erste Ernte wird erst im nächsten Monat verteilt. Mir gefiel vor allem, dass wir Probleme gemeinsam lösten. Für das nächste Treffen möchte ich eigene Handschuhe kaufen. Außerdem werde ich meine Nachbarin fragen, ob sie mitkommen möchte. Sie sucht schon lange eine Tätigkeit im Freien, bei der sie neue Menschen kennenlernen kann.",
  article: "Die Stadt Lindenau testet eine Werkzeugausleihe in drei Wohngebieten. Einwohner können für eine kleine Jahresgebühr Bohrmaschinen und andere Geräte ausleihen, die sie nur selten brauchen. Die Geräte müssen vorab im Internet reserviert werden. Wer keinen Internetzugang hat, erhält dienstags im Stadtbüro Unterstützung bei der Buchung. Die Ausleihe ist samstags geöffnet; eine Abholung an anderen Tagen ist nicht vorgesehen. Alle Teilnehmenden erhalten beim ersten Besuch eine kurze Einweisung. Defekte Geräte dürfen nicht selbst repariert werden, sondern müssen sofort gemeldet werden. Das Projekt soll Platz und Geld sparen. Ob tatsächlich weniger neue Geräte gekauft werden, wird nach sechs Monaten untersucht. Dafür fragt die Stadt nicht nur nach der Zahl der Buchungen, sondern auch nach den Erfahrungen der Nutzer. Eine dauerhafte Fortsetzung ist noch nicht beschlossen. Die Stadt möchte zunächst wissen, ob das Angebot in allen drei Wohngebieten gebraucht wird und wie viel die Wartung kostet.",
  ads: "A · Gartenrunde: Mittwochs 18–20 Uhr gemeinsam im Freien arbeiten. Keine Gebühr; Erfahrung ist nicht erforderlich.\nB · Online-Fotokurs: Aufgaben jederzeit bearbeiten, monatlich 25 Euro. Rückmeldung ausschließlich per E-Mail.\nC · Fahrradwerkstatt: Samstags 10–13 Uhr Reparaturen unter Anleitung. Eigene Fahrräder mitbringen; Ersatzteile werden bezahlt.\nD · Schreibtreff: Dienstags 15–17 Uhr persönliche Rückmeldung zu Bewerbungen. Kostenlos, Anmeldung erforderlich.\nE · Stadtspaziergang: Sonntags 11 Uhr Geschichte entdecken. Acht Euro, Anmeldung vor Ort.",
  opinions: "Nora: Ich finde die Werkzeugausleihe sinnvoll. Für kleine Reparaturen muss ich dann kein teures Gerät kaufen.\nEmil: Ich bin dagegen. Wenn ein Gerät kaputtgeht, kostet die Verwaltung zu viel Zeit und Geld.\nSofia: Ich befürworte das Angebot, sofern auch Menschen ohne Computer buchen können. Sonst werden einige ausgeschlossen.\nDavid: Ich habe noch keine Meinung. Zuerst möchte ich wissen, wie zuverlässig die Geräte sind.",
  rules: "Gartenhaus: Schlüssel werden nur an registrierte Mitglieder ausgegeben. Gäste dürfen gemeinsam mit einem Mitglied hineingehen, aber keine Geräte allein ausleihen. Nach der Nutzung werden Werkzeuge gereinigt und in die markierten Fächer gelegt. Beschädigungen müssen vor dem Verlassen gemeldet werden. Der Garten ist bis 20 Uhr zugänglich; im Gartenhaus endet die Nutzung bereits um 19:30 Uhr, damit genug Zeit zum Aufräumen bleibt. Auf dem gesamten Gelände sind offene Feuer verboten. Kleine kalte Mahlzeiten sind erlaubt. Wer einen Gruppentermin absagt, informiert die Koordination spätestens am Vortag. Eine Nachricht in der privaten Gruppe ersetzt diese Mitteilung nicht.",
};
export const b1FreshGoetheReading: { part: keyof typeof b1FreshReading; questions: B1Question[] }[] = [
  { part: "blog", questions: [q("Die Erzählerin musste wegen fehlender Handschuhe absagen. Richtig oder falsch?", "Falsch", "Richtig", "Der Text enthält keine Information zu Handschuhen.", "Die Organisatorin bot Leihhandschuhe an; deshalb konnte die Erzählerin teilnehmen."), q("Warum wurde trotz des Regens weitergearbeitet?", "Die jungen Pflanzen mussten dringend eingesetzt werden.", "Der Hausmeister erlaubte keine Pause.", "Die erste Ernte musste sofort verteilt werden.", "Der Text nennt den dringenden Bedarf der Pflanzen als Grund."), q("Für welchen Termin übernimmt die Erzählerin eine Aufgabe?", "Mittwochabend", "Samstagmorgen", "Sonntagmittag", "Sie kann am Mittwochabend gießen; für diesen Tag fehlte jemand.")] },
  { part: "article", questions: [q("Was ist das Hauptziel des Projekts?", "Selten benötigte Werkzeuge gemeinsam nutzen.", "Alle Geräte kostenlos an Einwohner verschenken.", "Werkzeughersteller bei Reparaturen ersetzen.", "Ausleihen statt selbst kaufen soll Geld und Platz sparen."), q("Eine Person ohne Internet möchte ein Gerät buchen. Was kann sie tun?", "Dienstags im Stadtbüro Hilfe erhalten.", "An jedem Abend direkt Geräte abholen.", "Eine defekte Maschine selbst reparieren.", "Die Buchungshilfe ist dienstags; Abholung bleibt samstags."), q("Was ist zur Fortsetzung bereits entschieden?", "Noch nichts Endgültiges; zuerst wird der Versuch ausgewertet.", "Das Angebot endet sicher nach einer Woche.", "Es wird ab sofort in allen Städten dauerhaft angeboten.", "Eine dauerhafte Fortsetzung ist ausdrücklich noch nicht beschlossen.")] },
  { part: "ads", questions: [q("Rami kann nur abends und sucht kostenlos eine praktische Tätigkeit ohne Vorkenntnisse. Was passt?", "A · Gartenrunde", "C · Fahrradwerkstatt", "D · Schreibtreff", "Nur A erfüllt Abendzeit, kostenlose Teilnahme und keine nötige Erfahrung."), q("Lena möchte eine persönliche Betreuung in einem kostenlosen Fotokurs am Sonntag. Was passt?", "Keine Anzeige passt.", "B · Online-Fotokurs", "E · Stadtspaziergang", "B ist kostenpflichtig und nur per E-Mail; E ist kein Fotokurs. Alle Bedingungen müssen erfüllt sein.")] },
  { part: "opinions", questions: [q("Wer befürwortet die Ausleihe unter einer bestimmten Bedingung?", "Sofia", "Emil", "David", "Sofia ist dafür, sofern Buchung ohne Computer möglich ist; David ist unentschieden."), q("Wer lehnt das Angebot ausdrücklich ab?", "Emil", "Nora", "Sofia", "Emil sagt, dass er dagegen ist, und begründet das mit Verwaltungskosten.")] },
  { part: "rules", questions: [q("Was darf ein Gast im Gartenhaus tun?", "Mit einem registrierten Mitglied hineingehen.", "Allein einen Schlüssel erhalten.", "Ohne Begleitung Geräte ausleihen.", "Gäste dürfen nur mit einem Mitglied hinein; allein ausleihen ist verboten."), q("Wann muss die Nutzung des Gartenhauses enden?", "Um 19:30 Uhr.", "Um 20 Uhr beginnt erst das Aufräumen.", "Um 19 Uhr endet die gesamte Gartennutzung.", "Gartenhaus bis 19:30; das Gelände bis 20 Uhr. Die Zeiten gelten für verschiedene Orte.")] },
];

export const b1FreshTelcReading = [
  { heading: "Global lesen · Überschrift", text: b1FreshReading.article, questions: [q("Welche Überschrift beschreibt den gesamten Artikel?", "Werkzeuge teilen: Stadt erprobt ein neues Ausleihangebot", "Stadt verschenkt Geräte an alle Bewohner", "Onlinekurse ersetzen städtische Werkstätten", "Das Projekt ist ein begrenzter Ausleihversuch; weder Geschenk noch Onlineunterricht.")] },
  { heading: "Details lesen · Projektbedingungen", text: b1FreshReading.article, questions: [q("Wann können reservierte Geräte abgeholt werden?", "Samstags", "Dienstags bei der Buchungshilfe", "Jeden Abend", "Dienstag betrifft Buchungshilfe, Samstag die Ausleihe."), q("Was sollen Nutzer bei einem Defekt machen?", "Den Defekt sofort melden.", "Das Gerät selbst reparieren.", "Bis zum Ende der Testphase warten.", "Selbst reparieren ist ausdrücklich nicht erlaubt; Defekte müssen sofort gemeldet werden.")] },
  { heading: "Selektiv lesen · alle Anforderungen", text: b1FreshReading.ads, questions: [q("Petra braucht persönliche Hilfe bei einer Bewerbung und kann dienstags nachmittags. Was passt?", "D · Schreibtreff", "B · Online-Fotokurs", "A · Gartenrunde", "D ist persönlich, dienstags nachmittags und für Bewerbungen geeignet."), q("Omar möchte am Wochenende sein eigenes Fahrrad unter Anleitung reparieren. Was passt?", "C · Fahrradwerkstatt", "E · Stadtspaziergang", "D · Schreibtreff", "C ist samstags und bietet Anleitung am eigenen Fahrrad.")] },
];
export const b1FreshLetter = "Liebe Samira, ich freue mich [1] deine Einladung zur Gartenaktion. Leider kann ich erst später kommen, [2] ich am Vormittag arbeite. Könntest du [3] bitte sagen, welche Aufgabe noch frei ist? Ich würde gern helfen, die Beete [4] vorzubereiten. Ich bringe [5] Handschuhe mit, dann können wir zu zweit arbeiten. Falls es stark regnet, [6] wir die Pflanzen im Gartenhaus sortieren. Viele Grüße, Milo";
export const b1FreshLanguage: B1Question[] = [
  q("Lücke 1", "über", "für", "mit", "Die bereits erhaltene Einladung: sich freuen über + Akkusativ."),
  q("Lücke 2", "weil", "deshalb", "trotzdem", "Begründung mit finite Verbform am Ende: weil ich arbeite."),
  q("Lücke 3", "mir", "mich", "mein", "Jemandem etwas sagen: Empfänger im Dativ, mir."),
  q("Lücke 4", "gemeinsam", "Gemeinschaft", "gemeinsamen", "Das Adverb gemeinsam beschreibt die Tätigkeit vorbereiten."),
  q("Lücke 5", "zusätzliche", "zusätzlichen", "zusätzlicher", "Ohne Artikel im Akkusativ Plural: zusätzliche Handschuhe."),
  q("Lücke 6", "können", "könnten haben", "gekonnt", "Nach dem vorangestellten falls-Satz beginnt der Hauptsatz mit dem finiten Modalverb können."),
];

export const b1FreshListening = [
  { id: "b1-fresh-message", title: "Kurze Nachricht · Arbeitsaufteilung", repeats: 2, segments: [{ speaker: "Anna", text: "Hallo Samira, hier ist Milo. Ich komme morgen eine halbe Stunde später zur Gartenaktion. Meine Schicht endet erst um zehn, deshalb bin ich gegen halb elf da. Bitte fangt ohne mich an. Die Handschuhe bringe ich trotzdem mit. Die Schaufeln müssen wir nicht kaufen: Unser Nachbar leiht uns zwei. Allerdings kann er sie erst am Nachmittag vorbeibringen. Bis dahin können wir die kleinen Pflanzen vorbereiten. Die Wettervorhersage nennt Regen erst für den Abend. Wir müssen die Aktion also nicht absagen. Wenn sich etwas ändert, ruf mich bitte an; während der Arbeit kann ich keine Nachrichten lesen. Bis morgen!" }], questions: [q("Wann kommt Milo?", "Gegen 10:30 Uhr.", "Um 10 Uhr beginnt seine Arbeit.", "Er kommt erst am Abend.", "Seine Schicht endet um zehn; er kommt gegen halb elf."), q("Was wird erst am Nachmittag verfügbar sein?", "Die geliehenen Schaufeln.", "Die Handschuhe, die Milo mitbringt.", "Die Wettervorhersage für den nächsten Monat.", "Der Nachbar bringt die Schaufeln erst nachmittags; sie müssen nicht gekauft werden.")] },
  { id: "b1-fresh-announcement", title: "Information · neue Werkzeugausleihe", repeats: 1, segments: [{ speaker: "Eddy (German (Germany))", text: "Guten Tag und willkommen bei unserer neuen Werkzeugausleihe. Bitte legen Sie bei der Anmeldung einen Ausweis vor und füllen Sie das Formular aus. Die Jahresgebühr beträgt zwölf Euro. Die Benutzung einzelner Geräte kostet nichts zusätzlich. Ersatzteile müssen Sie jedoch selbst besorgen. Am ersten Tag erklären wir Ihnen die Bedienung. Für die große Bohrmaschine ist diese Einführung verpflichtend, auch wenn Sie schon Erfahrung haben. Ein Gerät können Sie höchstens drei Tage behalten. Wenn Sie es länger brauchen, fragen Sie vor dem Rückgabetermin nach einer Verlängerung. Eine automatische Verlängerung gibt es nicht. Bitte geben Sie Geräte sauber zurück und melden Sie jeden Schaden. Wenn das Büro geschlossen ist, nutzen Sie unsere Telefonnummer auf dem Ausleihschein. Legen Sie defekte Geräte nicht einfach vor die Tür." }], questions: [q("Was kostet zusätzlich zur Jahresgebühr Geld?", "Benötigte Ersatzteile.", "Jede einzelne Gerätebenutzung.", "Die verpflichtende Einführung.", "Benutzung kostet nichts zusätzlich; Ersatzteile werden selbst bezahlt."), q("Wie erhält man eine längere Ausleihzeit?", "Vor dem Rückgabetermin um Verlängerung bitten.", "Das Gerät ohne Nachricht behalten.", "Nach drei Tagen automatisch verlängern lassen.", "Verlängerungen müssen vorher angefragt werden; sie sind nicht automatisch.")] },
  { id: "b1-fresh-dialogue", title: "Gespräch · einen Treffpunkt wählen", repeats: 1, segments: [
    { speaker: "Anna", text: "Für unser Planungsgespräch würde ich das Café am Markt nehmen. Dort kann man lange sitzen." },
    { speaker: "Eddy (German (Germany))", text: "Es ist gemütlich, aber am Samstag oft laut. Ich möchte die Aufgaben in Ruhe besprechen. Der Gruppenraum in der Bibliothek wäre besser." },
    { speaker: "Anna", text: "Dort dürfen wir keine Getränke mitnehmen. Nach der Gartenarbeit möchte ich aber etwas trinken." },
    { speaker: "Eddy (German (Germany))", text: "Wir könnten zuerst eine halbe Stunde in der Bibliothek planen und danach ins Café gehen. Den Raum muss man allerdings reservieren." },
    { speaker: "Anna", text: "Gut, ich reserviere ihn. Könntest du die Aufgabenliste vorbereiten? Dann verlieren wir beim Gespräch weniger Zeit." },
    { speaker: "Eddy (German (Germany))", text: "Mache ich. Wenn der Raum schon belegt ist, treffen wir uns draußen im Gartenhaus. Gib mir bis Freitagabend Bescheid." },
  ], questions: [q("Warum bevorzugt der zweite Sprecher die Bibliothek?", "Er möchte in Ruhe planen.", "Im Café sind Getränke verboten.", "Er darf samstags nicht ins Café.", "Er nennt die Lautstärke am Samstag als Problem."), q("Wer kümmert sich um die Reservierung?", "Die erste Sprecherin.", "Der zweite Sprecher.", "Niemand; Reservierung ist nicht nötig.", "Die Sprecherin sagt: Ich reserviere ihn; der andere erstellt die Aufgabenliste.")] },
  { id: "b1-fresh-discussion", title: "Diskussion · gemeinsame Geräte", repeats: 2, segments: [
    { speaker: "Eddy (German (Germany))", text: "Wir diskutieren die Werkzeugausleihe. Frau Reimann, würden Sie das Angebot nutzen?" },
    { speaker: "Anna", text: "Ja, denn ich brauche selten eine Bohrmaschine. Ich finde allerdings die Abholung nur am Samstag schwierig. Für Menschen mit Wochenendarbeit müsste es eine zusätzliche Möglichkeit geben." },
    { speaker: "Eddy (German (Germany))", text: "Längere Öffnungszeiten kosten Geld. Mir wäre zunächst wichtig, dass alle Geräte regelmäßig geprüft werden. Sicherheit geht vor. Wenn das gut funktioniert, könnte man die Zeiten später erweitern." },
    { speaker: "Anna", text: "Natürlich. Vielleicht kann man einen zweiten Termin nur nach Vereinbarung anbieten. Dann muss das Büro nicht jeden Abend geöffnet sein." },
    { speaker: "Eddy (German (Germany))", text: "Das könnte ein Kompromiss sein. Ich würde nach drei Monaten die Rückmeldungen sammeln und erst dann entscheiden. Eine sofortige Öffnung an allen Tagen unterstütze ich nicht." },
  ], questions: [q("Wer wünscht eine zusätzliche Abholmöglichkeit?", "Frau Reimann, die Sprecherin.", "Nur der zweite Sprecher.", "Niemand aus dem Gespräch.", "Die Sprecherin verweist auf Menschen mit Wochenendarbeit."), q("Was hat für den zweiten Sprecher Vorrang?", "Regelmäßige Prüfung und Sicherheit der Geräte.", "Sofortige Öffnung an allen Tagen.", "Die Abschaffung der Rückmeldungen.", "Er nennt Sicherheit ausdrücklich zuerst und will später auswerten.")] },
];

export const b1FreshWriting = {
  goethe: [
    { title: "Neue persönliche E-Mail", prompt: "Sie haben eine neue Freizeitgruppe ausprobiert. Schreiben Sie einer Freundin: Beschreiben Sie das erste Treffen, erklären Sie, was Sie überrascht hat, und laden Sie sie zum nächsten Treffen ein. Etwa 80 Wörter; 20 Minuten.", model: "Hallo Lina, gestern habe ich zum ersten Mal die Gartenrunde besucht. Wir haben zusammen ein Beet vorbereitet und danach unsere Aufgaben verteilt. Besonders überrascht hat mich, dass auch Anfänger sofort mitmachen konnten. Eine Teilnehmerin erklärte mir alles in Ruhe und lieh mir sogar Handschuhe. Deshalb möchte ich nächste Woche wieder hingehen. Hättest du am Mittwochabend Zeit, mitzukommen? Wir könnten uns um halb sechs an der Haltestelle treffen und gemeinsam zum Garten laufen. Sag mir bitte bis Dienstag Bescheid. Liebe Grüße, Milo", min: 60, max: 120 },
    { title: "Neuer Meinungsbeitrag", prompt: "Im Forum steht: Dinge ausleihen ist umständlicher als alles selbst zu kaufen. Äußern Sie Ihre Meinung, begründen Sie sie mit einem Beispiel und nennen Sie eine Schwierigkeit. Etwa 80 Wörter; 25 Minuten.", model: "Ich finde, dass man selten benötigte Gegenstände gut ausleihen kann. Für eine kleine Reparatur habe ich zum Beispiel eine Bohrmaschine von meiner Nachbarin benutzt. Dadurch sparte ich Geld und brauchte keinen zusätzlichen Platz in meiner Wohnung. Allerdings muss man die Rückgabe zuverlässig organisieren. Wenn viele Personen gleichzeitig dasselbe Gerät brauchen, ist eine Reservierung sinnvoll. Meiner Meinung nach passt Ausleihen deshalb besonders für Dinge, die man nur gelegentlich verwendet. Gegenstände, die ich jeden Tag brauche, würde ich lieber selbst besitzen und regelmäßig pflegen.", min: 60, max: 120 },
    { title: "Neue formelle Nachricht", prompt: "Sie haben ein Gerät ausgeliehen und können es wegen eines geänderten Dienstplans nicht rechtzeitig zurückbringen. Schreiben Sie Frau Braun: Entschuldigen Sie sich, erklären Sie das Problem und bitten Sie um eine Lösung. Etwa 40 Wörter; 15 Minuten.", model: "Sehr geehrte Frau Braun, leider kann ich die Bohrmaschine morgen nicht zurückbringen, weil mein Dienstplan kurzfristig geändert wurde. Dafür möchte ich mich entschuldigen. Könnte ich das Gerät am folgenden Samstag abgeben? Bitte teilen Sie mir mit, ob das möglich ist. Mit freundlichen Grüßen, Milo Berger", min: 30, max: 70 },
  ],
  telc: [{ title: "Neuer Leitpunktbrief", prompt: "Samira schreibt: Ich organisiere eine Gartenaktion. Wann kannst du kommen? Welche Aufgabe möchtest du übernehmen? Was kannst du mitbringen? Was sollen wir bei Regen machen? Antworten Sie auf alle vier Punkte in sinnvoller Reihenfolge mit Anrede und Schluss. 30 Minuten; Kursziel 100–130 Wörter, keine zusätzliche offizielle Wortregel.", model: "Liebe Samira, vielen Dank für deine Nachricht. Ich helfe gern bei der Gartenaktion. Am Vormittag muss ich arbeiten, deshalb kann ich erst gegen halb elf kommen. Bitte beginnt schon ohne mich. Am liebsten würde ich die kleinen Pflanzen vorbereiten, weil ich dabei schon etwas Erfahrung habe. Für schwere Arbeiten könnte ich später ebenfalls helfen. Ich bringe Handschuhe und zwei große Wasserflaschen mit. Wenn es regnet, sollten wir zuerst im Gartenhaus arbeiten. Dort könnten wir die Pflanzen sortieren und Schilder für die Beete schreiben. Vielleicht können wir danach draußen weitermachen. Falls das Wetter zu schlecht wird, wäre ein neuer Termin sinnvoll. Schreib mir bitte, ob dieser Plan für dich passt. Liebe Grüße, Milo", min: 80, max: 160 }],
};

export const b1FreshSpeaking = {
  goethe: [
    { heading: "Neue Partnerplanung", prompt: "Organisieren Sie einen Reparaturnachmittag: Raum und Zeit, Geräte, Einladung, Aufgabenverteilung. Person A hat nur vormittags Zeit und wenig Geld; Person B kann erst ab 13 Uhr kommen und kennt eine geeignete Werkstatt. Machen Sie Vorschläge, reagieren Sie und halten Sie einen gemeinsamen Plan fest.", model: "A: Ich würde gern am Samstag anfangen, aber nur am Vormittag habe ich Zeit. B: Bei mir geht es erst ab eins. Könntest du vorher die Einladung und das Material vorbereiten? A: Ja. Können wir die Werkstatt kostenlos nutzen? B: Ich frage nach. Dann übernehme ich am Nachmittag den Empfang. A: Gut, ich schicke dir die Aufgabenliste bis Freitag.", target: 180 },
    { heading: "Neue Präsentation", prompt: "Thema: Sollte man Alltagsgegenstände häufiger teilen? Sprechen Sie frei mit Stichworten: Einführung, eigene Erfahrung, Situation in einem Ihnen bekannten Land oder Umfeld, Vorteile und Nachteile, Meinung und Schluss. Etwa drei Minuten. Erfinden Sie keine Erfahrung; Sie dürfen sagen, dass Sie dazu bisher keine persönliche Erfahrung haben.", model: "Ich möchte über das Teilen von Gegenständen sprechen. In meiner Nachbarschaft leihen wir manchmal Werkzeuge aus. Das spart Geld und Platz. In meinem früheren Wohnort war das Angebot weniger organisiert. Ein Vorteil ist der persönliche Kontakt. Schwierig wird es, wenn etwas beschädigt wird. Deshalb finde ich klare Regeln wichtig. Ich würde selten benötigte Dinge teilen, Alltagsgeräte aber selbst behalten. Vielen Dank fürs Zuhören.", target: 180 },
    { heading: "Neue Rückfrage und Antwort", prompt: "Hören Sie die Präsentation Ihrer Partnerperson. Geben Sie eine konkrete Rückmeldung und stellen Sie eine offene Frage, die sich auf einen genannten Punkt bezieht. Die präsentierende Person antwortet mit einem Grund oder Beispiel. Rollen wechseln. Allein: erst eine Frage aufnehmen, dann mit einer anderen Rolle darauf antworten.", model: "Ihre Erklärung zu den Regeln fand ich klar. Sie haben Schäden erwähnt: Wer sollte Ihrer Meinung nach eine Reparatur bezahlen? Ich würde zuerst prüfen, ob der Schaden durch normale Nutzung entstanden ist. Bei falscher Bedienung sollte die Person einen Teil der Kosten übernehmen. Eine schriftliche Vereinbarung könnte dabei helfen.", target: 120 },
  ],
  telc: [
    { heading: "Neuer Kontakt", prompt: "Lernen Sie eine Partnerperson kennen: aktueller Alltag, Interessen, bisheriges Deutschlernen und ein nächstes Lernziel. Stellen Sie Rückfragen und reagieren Sie auf Antworten. Verwenden Sie keine auswendig gelernte Vorstellung ohne Bezug zum Gespräch.", model: "Ich arbeite zurzeit in einem Café und lerne abends Deutsch. In meiner Freizeit gehe ich gern in den Garten. Und was machst du nach der Arbeit? Interessant, du reparierst Fahrräder. Wie hast du das gelernt? Beim Deutschlernen möchte ich sicherer telefonieren. Vielleicht könnten wir zusammen kurze Gespräche üben.", target: 180 },
    { heading: "Neuer Austausch über ein Thema", prompt: "Kurzimpuls A: Eine Person leiht selten benötigte Werkzeuge, um Geld zu sparen. Kurzimpuls B: Eine Person kauft eigene Werkzeuge, weil sie spontan arbeiten möchte. Geben Sie den Impuls mit eigenen Worten wieder. Tauschen Sie Erfahrungen aus, fragen Sie nach und vergleichen Sie beide Möglichkeiten.", model: "In meinem Impuls leiht eine Person Werkzeuge aus, weil sie sie selten braucht. Ich finde das verständlich. Hast du selbst schon etwas ausgeliehen? Bei mir war die Rückgabe einmal schwierig. Eigene Geräte sind spontaner verfügbar, kosten aber mehr. Welche Lösung würdest du für eine kleine Wohnung wählen?", target: 240 },
    { heading: "Neue gemeinsame Aufgabe", prompt: "Planen Sie einen Besuch bei einem neuen Gesprächstreff: Termin, Anfahrt, Anmeldung, Vorbereitung und Kosten. Person A möchte mit dem Rad fahren, kann aber nur abends; Person B hat kein Rad und kann am Dienstag nicht. Klären Sie Bedingungen und einigen Sie sich auf konkrete nächste Schritte.", model: "A: Wie wäre es mit Dienstagabend? B: Da habe ich schon einen Termin. Am Donnerstag könnte ich. A: Das passt. Ich fahre mit dem Rad. Wie kommst du hin? B: Mit dem Bus. Treffen wir uns vor dem Eingang? A: Ja. Ich frage nach der Anmeldung und du prüfst die Kosten. B: Gut, wir geben uns morgen Bescheid.", target: 300 },
  ],
};
