// Original teaching notes, following DW's A1 grammar overview (units 0–18).
// Practice sentences below are newly authored, not quotations from the film.
export type NicosGrammarRule = readonly [title: string, english: string, sinhala: string, example: string, meaning: string];
export type NicosGrammarUnit = {
  title: string;
  rules: readonly NicosGrammarRule[];
  table: readonly (readonly string[])[];
  checks: readonly (readonly [prompt: string, correct: string, distractor: string, english: string, sinhala: string])[];
};
export const nicosWegA1Grammar: readonly NicosGrammarUnit[] = [
 {title:"Begrüßen · Formal and informal German", rules:[
 ["du or Sie?","Use du with a child, friend or someone who has agreed to informal address. Use Sie with unfamiliar adults in a formal situation. Formal Sie and Ihnen always have a capital letter, including in the middle of a sentence.","මිතුරන් හා දරුවන් සමඟ du යොදන්න. විධිමත් අවස්ථාවල නොහඳුනන වැඩිහිටියන් සඳහා Sie යොදන්න. ගෞරවනීය Sie සහ Ihnen වාක්‍යයේ මැද වුවත් ලොකු අකුරකින් ලියන්න.","Wie geht es Ihnen?","How are you? (formal)"],
 ["Learn greetings as chunks","Guten Morgen, Guten Tag and Guten Abend are fixed greeting expressions. Hallo works in many informal situations. At the end of a conversation, use Tschüss informally or Auf Wiedersehen more formally.","ආචාර කිරීමේ යෙදුම් සම්පූර්ණයෙන් ඉගෙන ගන්න. උදේ Guten Morgen, දහවල් Guten Tag, සවස Guten Abend. සමුගැනීමට Tschüss හෝ වඩා විධිමත්ව Auf Wiedersehen යොදන්න.","Guten Morgen, Frau Silva.","Good morning, Ms Silva."],
 ["Ask for clarification","Bitte makes a request polite. Wie bitte? asks someone to repeat. Buchstabieren means to spell; formal requests use the infinitive-shaped verb followed by Sie. Practise listening for individual letters before repeating a whole name.","Bitte ඉල්ලීමක් ආචාරශීලී කරයි. Wie bitte? යනු නැවත කියන්න ඉල්ලීමකි. නමක අකුරු කියන්න කියන විට Buchstabieren Sie ... යොදන්න.","Buchstabieren Sie bitte Ihren Namen.","Please spell your name."]],table:[["Informal","Wie heißt du?","What is your name?"],["Formal","Wie heißen Sie?","What is your name?"],["Informal","Wie geht es dir?","How are you?"],["Formal","Wie geht es Ihnen?","How are you?"]], checks:[["Choose the formal greeting.","Wie geht es Ihnen?","Wie geht es dir?","Ihnen is the formal dative form of Sie.","Ihnen යනු ගෞරවනීය Sie හි Dativ රූපයයි."],["Complete a formal request: Buchstabieren ___ bitte.","Sie","du","Formal Sie uses buchstabieren, not buchstabierst.","Sie සමඟ buchstabieren යෙදේ; buchstabierst නොවේ."]]},
 {title:"Personen · Pronouns and present tense",rules:[
 ["Match the verb to the subject","Find the person doing the action first. Remove -en from a regular infinitive and add the present ending: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en. A name such as Nico takes the er ending.","මුලින් ක්‍රියාව කරන පුද්ගලයා හඳුනාගන්න. සාමාන්‍ය ක්‍රියාවක -en ඉවත් කර පුද්ගලයාට ගැළපෙන අවසානය එක් කරන්න. Nico වැනි නමක් සමඟ er රූපය යෙදේ.","Nico lernt Deutsch. Wir lernen auch.","Nico learns German. We learn too."],
 ["sein and haben are irregular","Learn these forms separately. sein identifies a person or state; haben expresses possession and many everyday states. Do not form ich sein or du haben by leaving the infinitive unchanged.","sein සහ haben සාමාන්‍ය ක්‍රියා වගේ වෙනස් නොවේ. ඒවායේ පුද්ගල රූප වෙන වෙනම මතක තබාගන්න. හඳුන්වාදීමට sein, යමක් තිබෙන බවට haben යොදන්න.","Ich bin Student. Du hast eine Tasche.","I am a student. You have a bag."],
 ["Verb position 2","In a statement, the conjugated verb occupies the second sentence unit. Usually the subject comes first. A phrase can contain several words while still counting as one unit. A yes/no question starts with the conjugated verb.","ප්‍රකාශ වාක්‍යයක වෙනස් කළ ක්‍රියාව දෙවන කොටසේ තිබේ. කොටසක් වචන කිහිපයකින් සෑදිය හැක. ඔව්/නැහැ ප්‍රශ්නයක ක්‍රියාව මුලට එයි.","Du hast Zeit. Hast du Zeit?","You have time. Do you have time?"]],table:[["ich","bin / habe","I"],["du","bist / hast","you"],["er/sie/es","ist / hat","he/she/it"],["wir / sie / Sie","sind / haben","we / they / formal you"],["ihr","seid / habt","you (plural informal)"]],checks:[["Complete: Nico ___ Deutsch.","lernt","lernen","Nico is one person: use the er/sie/es ending -t.","Nico එක් පුද්ගලයෙකි. -t අවසානය යොදන්න."],["Complete: Du ___ eine Tasche.","hast","haben","The du form of haben is hast.","haben හි du රූපය hast වේ."]]},
 {title:"Kontaktdaten · Questions, numbers and addresses",rules:[
 ["W-questions","Use wer for a person, was for a thing, wo for a location, woher for origin and wie for a manner or identifying detail. Put the question word first, the conjugated verb second and the subject next.","පුද්ගලයාට wer, දේකට was, ස්ථානයට wo, පැමිණි තැනට woher යොදන්න. ප්‍රශ්න පදය, ක්‍රියාව, කර්තෘ යන පිළිවෙළ තබන්න.","Woher kommst du? Wo wohnst du?","Where are you from? Where do you live?"],
 ["Numbers from units to hundreds","In 21–99 say the unit before the tens, joined with und: einundzwanzig. Note zwölf, sechzehn, siebzehn and dreißig. For phone numbers, say individual digits or agreed small groups; null is zero.","21–99 අතර ඒකකය මුලින්ද දහය පසුවද කියා und යොදන්න. 21 = einundzwanzig. දුරකථන අංකවල තනි ඉලක්කම් කියන්න; බිංදුව null වේ.","Meine Hausnummer ist einunddreißig.","My house number is thirty-one."],
 ["Origin and location","aus answers woher and takes dative: aus Deutschland, aus der Schweiz. For residence use in: in Berlin, in der Schweiz. Countries without an article keep their bare name. Formal personal questions use Sie + plural verb form.","පැමිණි රට කියන්න aus, පදිංචිය කියන්න in යොදන්න. Artikel ඇති රටකට Dativ රූපය අවශ්‍යයි: aus der Schweiz. විධිමත් ප්‍රශ්නවල Sie යොදන්න.","Ich komme aus Sri Lanka und wohne in Berlin.","I am from Sri Lanka and live in Berlin."]],table:[["11 / 12","elf / zwölf","eleven / twelve"],["16 / 17","sechzehn / siebzehn","sixteen / seventeen"],["21 / 38","einundzwanzig / achtunddreißig","unit + und + tens"],["100 / 1000","(ein)hundert / (ein)tausend","hundred / thousand"]],checks:[["Choose the correct question order.","Wo wohnen Sie?","Wo Sie wohnen?","In a direct W-question, the verb follows the question word.","සෘජු W-ප්‍රශ්නයක ප්‍රශ්න පදයට පසුව ක්‍රියාව එයි."],["What is 31?","einunddreißig","dreißigundeins","German says the unit first: ein + und + dreißig.","ජර්මන් භාෂාවේ ඒකකය මුලින්: ein + und + dreißig."]]},
 {title:"Gesellschaft · Gender and changing verb stems",rules:[
 ["Learn every noun with its article","German noun gender is grammatical, not a reliable description of a person or object. Learn der, die or das together with the noun and its plural. Capitalize nouns: der Tisch, die Tasche, das Getränk.","නාමපදයේ ලිංගය අර්ථයෙන් සෑමවිටම සොයාගත නොහැක. der/die/das සහ බහු වචනය සමඟ නාමපදය ඉගෙන ගන්න. නාමපද ලොකු අකුරෙන් ලියන්න.","Das Getränk ist kalt. Die Tasche ist schön.","The drink is cold. The bag is beautiful."],
 ["Some verbs change e to i or ie","essen and nehmen change their stem in du and er/sie/es: du isst, er nimmt. lesen changes to ie: du liest. The wir and Sie forms return to the normal stem. Memorize a small verb family rather than applying the change to every verb.","සමහර ක්‍රියා du හා er/sie/es සමඟ e→i හෝ e→ie ලෙස වෙනස් වෙයි. essen→isst, nehmen→nimmt, lesen→liest. සියලු ක්‍රියාවලට මේ වෙනස නොකරන්න.","Ich esse Pizza. Du isst Salat.","I eat pizza. You eat salad."],
 ["Order politely with möchten","möchten means would like. For a noun request, use the appropriate accusative article. For an action, keep möchten in position 2 and put the infinitive at the end. Bitte can appear at the end of a short order.","möchten ආචාරශීලී කැමැත්තක් දක්වයි. නාමපදයක් ඉල්ලන විට Akkusativ යොදන්න. ක්‍රියාවක් තිබේ නම් එහි Infinitiv අවසානයට යයි.","Ich möchte einen Tee trinken.","I would like to drink a tea."]],table:[["essen","du isst / er isst","eat"],["nehmen","du nimmst / er nimmt","take"],["lesen","du liest / er liest","read"],["möchten","ich möchte / du möchtest","would like"]],checks:[["Complete: Du ___ eine Pizza.","isst","essen","essen changes its stem in the du form: isst.","essen හි du රූපය isst වේ."],["Complete: Ich möchte einen Tee ___.","trinken","trinke","After möchten, the second verb remains an infinitive at the end.","möchten ට පසුව දෙවන ක්‍රියාව Infinitiv ලෙස අවසානයේ තිබේ."]]},
 {title:"Welt · Past sein, travel and man",rules:[
 ["Past with war and waren","For earlier locations and states, use the simple past of sein. ich/er/sie/es war; du warst; wir/sie/Sie waren; ihr wart. This is common in conversation even when other past actions use the perfect tense.","පෙර තිබූ තත්ත්වයක් හෝ ස්ථානයක් කියන්න sein හි අතීතය යොදන්න. ich war, du warst, wir waren. දෛනික කතාවේ මේ රූප සාමාන්‍යයි.","Gestern war ich in Berlin.","Yesterday I was in Berlin."],
 ["in or nach?","For travel to a city or country without an article, use nach: nach Berlin, nach Spanien. For being there use in. With an article, a destination uses in + accusative: in die Schweiz; a location uses in + dative: in der Schweiz.","Artikel නැති රටකට හෝ නගරයකට යන විට nach යොදන්න. එහි සිටින විට in යොදන්න. Artikel ඇති රටකට ගමනාන්තය in + Akkusativ, ස්ථානය in + Dativ වේ.","Wir fahren nach Spanien. Wir sind in Spanien.","We travel to Spain. We are in Spain."],
 ["man and sentence order","man means people in general, not the male noun Mann. It takes the er/sie/es verb form: man spricht. If a place or time goes first, the conjugated verb stays second and the subject follows it.","man යනු පොදුවේ මිනිසුන්ය; Mann නාමපදය නොවේ. එයට er/sie/es ක්‍රියා රූපය යොදන්න. ස්ථානය මුලට ගෙන ආවත් ක්‍රියාව දෙවන තැන තබන්න.","In Deutschland spricht man Deutsch.","In Germany people speak German."]],table:[["ich / er","war","was"],["du","warst","were"],["wir / sie / Sie","waren","were"],["ihr","wart","were"]],checks:[["Complete: Gestern ___ wir in Berlin.","waren","sind","Gestern locates this statement in the past; wir takes waren.","Gestern අතීතය දක්වයි; wir සමඟ waren යෙදේ."],["Complete: Man ___ Deutsch.","spricht","sprechen","man uses a singular third-person verb.","man සමඟ තෙවන පුද්ගල ඒක වචන ක්‍රියාව යෙදේ."]]},
 {title:"Dinge · Articles, plural and accusative",rules:[
 ["Definite and indefinite articles","Use ein/eine to introduce one unspecified item and der/die/das when identifying a known item. There is no plural equivalent of ein: ein Buch → Bücher. Plurals vary, so learn each with the noun.","එක් නොදන්නා දෙයක් හඳුන්වාදීමට ein/eine, හඳුනාගත් දෙයක් සඳහා der/die/das යොදන්න. ein සඳහා බහු වචන Artikel නැත. පොත් = Bücher.","Das ist ein Buch. Das Buch ist neu.","That is a book. The book is new."],
 ["Subject versus direct object","The subject is nominative. A direct object after verbs such as haben, suchen or kaufen is accusative. Masculine der/ein become den/einen; feminine, neuter and plural articles look unchanged. Case depends on the job in the sentence, not word order alone.","කර්තෘ Nominativ වේ. haben/suchen/kaufen වැනි ක්‍රියාවල සෘජු කර්මය Akkusativ වේ. පුරුෂ der/ein → den/einen. වාක්‍යයේ කාර්යය අනුව විභක්තිය තෝරන්න.","Der Mann sucht einen Stift.","The man is looking for a pen."],
 ["kein and predicative adjectives","Negate an indefinite noun with kein: Ich habe kein Auto. Its endings follow ein, including keinen in masculine accusative. An adjective after sein has no ending: Das Auto ist rot, not rotes.","අනිශ්චිත නාමපදයක් ප්‍රතික්ෂේප කිරීමට kein යොදන්න. එහි අවසාන ein වගේ වෙනස් වේ. sein ට පසුව විශේෂණයට අවසානයක් එක් නොකරන්න: ist rot.","Ich habe keinen Stift. Das Buch ist klein.","I have no pen. The book is small."]],table:[["Masculine","der / ein → den / einen","der Stift"],["Feminine","die / eine → die / eine","die Tasche"],["Neuter","das / ein → das / ein","das Buch"],["Plural","die → die; no ein","die Bücher"]],checks:[["Complete: Ich suche ___ Stift.","einen","ein","Stift is masculine and the direct object of suchen.","Stift පුරුෂ නාමපදයකි; suchen හි කර්මයට einen යොදන්න."],["Complete: Das Auto ist ___.","rot","rotes","After sein, a predicative adjective has no ending.","sein ට පසුව විශේෂණයට අවසානයක් අවශ්‍ය නැත."]]},
 {title:"Wohnen · Possession, negation and compounds",rules:[
 ["Possessive determiners","Choose the stem by the owner: mein, dein, sein, ihr, unser, euer, ihr, Ihr. Choose its ending by the possessed noun's gender and case: mein Zimmer but meine Wohnung. For euer, common inflected forms are eure and euren.","අයිතිකරු අනුව mein/dein/sein/ihr තෝරන්න. අවසානය අයිති දේ නාමපදයේ ලිංගය හා විභක්තිය අනුව වෙනස් වේ: mein Zimmer, meine Wohnung.","Das ist meine Wohnung und unser Garten.","That is my flat and our garden."],
 ["nicht, kein and zu","Use kein for a noun with an indefinite article or no article. Use nicht to negate a quality, action or definite item. Place nicht before an adjective: nicht teuer. zu before an adjective means excessively: zu teuer, too expensive.","ein හෝ Artikel නැති නාමපද ප්‍රතික්ෂේපයට kein යොදන්න. ගුණයක් හෝ ක්‍රියාවක් සඳහා nicht යොදන්න. zu teuer යනු මිල වැඩියි; nicht teuer යනු මිල අධික නැහැ.","Das Zimmer ist nicht dunkel, aber es ist zu klein.","The room is not dark, but it is too small."],
 ["Compound nouns and es gibt","A compound takes the gender and main meaning of its last noun: das Schlafzimmer comes from das Zimmer. es gibt introduces what exists and takes an accusative object. Do not translate it word for word as a person giving something.","සංයුක්ත නාමපදයක ලිංගය අවසාන නාමපදයෙන් ලැබේ: das Schlafzimmer. තිබෙන දේ හඳුන්වාදීමට es gibt + Akkusativ යොදන්න.","Es gibt einen Balkon und ein Schlafzimmer.","There is a balcony and a bedroom."]],table:[["ich / du","mein / dein","my / your"],["er / sie","sein / ihr","his / her"],["wir / ihr","unser / euer","our / your"],["sie / Sie","ihr / Ihr","their / your (formal)"]],checks:[["Complete: Das ist ___ Wohnung. (my)","meine","mein","Wohnung is feminine nominative, so mein becomes meine.","Wohnung ස්ත්‍රී Nominativ නිසා meine යොදන්න."],["Complete: Es gibt ___ Balkon.","einen","ein","es gibt takes accusative; Balkon is masculine.","es gibt සමඟ Akkusativ අවශ්‍යයි; Balkon පුරුෂ වේ."]]},
 {title:"Tagesablauf · Time and separable verbs",rules:[
 ["Clock time and time prepositions","Use um for a clock time, am for a weekday and von … bis … for a time range. In informal time, halb neun is 8:30, half an hour before nine; Viertel nach acht is 8:15 and Viertel vor neun is 8:45.","ඔරලෝසු වේලාවට um, සතියේ දිනයට am, කාල පරාසයට von ... bis යොදන්න. halb neun = 8:30; එය නවයට පැය භාගයකට පෙර වේ.","Am Montag arbeite ich von acht bis zwölf.","On Monday I work from eight until twelve."],
 ["Separable verbs make a bracket","In a present-tense main clause, conjugate the stem in position 2 and put the prefix at the end: aufstehen → steht … auf. With a modal, the whole infinitive stays together at the end: muss aufstehen.","වෙන්වන ක්‍රියාවක ප්‍රධාන කොටස දෙවන තැනත් උපසර්ගය අවසානයේත් තබන්න: steht ... auf. Modal සමඟ සම්පූර්ණ Infinitiv අවසානයට යයි.","Emma steht früh auf. Sie muss früh aufstehen.","Emma gets up early. She has to get up early."],
 ["Frequency, sequence and vowel changes","Use immer, oft, manchmal and nie to say how often. dann and danach sequence actions; if they start a clause, the subject follows the verb. schlafen and fahren change a to ä with du/er: du schläfst, er fährt.","වාර ගණනට immer/oft/manchmal/nie යොදන්න. ඊළඟ ක්‍රියාවට dann/ danach යොදන්න. ඒවා මුලට ආ විට ක්‍රියාව දෙවන තැන තබන්න. schlafen→schläfst, fahren→fährt.","Danach fährt Emma nach Hause.","After that Emma travels home."]],table:[["08:00","acht Uhr","eight o'clock"],["08:15","Viertel nach acht","quarter past eight"],["08:30","halb neun","half past eight"],["08:45","Viertel vor neun","quarter to nine"]],checks:[["What does halb neun mean?","08:30","09:30","halb names the next full hour, so halb neun is 8:30.","halb සමඟ ඊළඟ පැය කියවේ; halb neun = 8:30."],["Choose the correct statement.","Ich rufe dich an.","Ich anrufe dich.","anrufen separates in a present main clause: rufe … an.","වර්තමාන ප්‍රධාන වාක්‍යයේ anrufen වෙන් වේ: rufe ... an."]]},
 {title:"Termine · Dates, können and past haben",rules:[
 ["24-hour clock and dates","Official schedules often use 24-hour time: zwanzig Uhr dreißig. Ordinals identify dates: der erste, der zweite, der dritte, der zwanzigste. After am, add -n: am ersten Mai. Memorize irregular erste and dritte.","නිල කාලසටහන්වල පැය 24 ක්‍රමය යොදයි. දිනයට පිළිවෙළ සංඛ්‍යා යොදන්න: der erste. am ට පසුව -n: am ersten Mai.","Der Termin ist am dritten Mai um zwanzig Uhr.","The appointment is on the third of May at 20:00."],
 ["können for ability or availability","können can mean being able or being available. Put kann/kannst/können in the finite verb slot, and any action infinitive at the end. In a question, the modal goes first. A short reply can omit an already understood action.","können හැකියාව හෝ වේලාව තිබීම කියයි. Modal ක්‍රියාව සාමාන්‍ය ක්‍රියා තැනටත් දෙවන Infinitiv අවසානයටත් යයි. ප්‍රශ්නයක Modal මුලට එයි.","Kannst du morgen kommen? Morgen kann ich nicht.","Can you come tomorrow? I cannot tomorrow."],
 ["This week, next week and had","diese Woche and nächste Woche can express time without a preposition. haben has common past forms hatte, hattest, hatten, hattet. Use these for past possession or states, while completed actions often use the perfect tense.","diese Woche/nächste Woche කාලය කියන විට Präposition නැතිව යෙදිය හැක. haben හි අතීත රූප hatte/hattest/hatten/hattet වේ.","Letzte Woche hatte ich keine Zeit.","Last week I had no time."]],table:[["ich / er","kann / hatte","can / had"],["du","kannst / hattest","can / had"],["wir / sie / Sie","können / hatten","can / had"],["ihr","könnt / hattet","can / had"]],checks:[["Complete: Der Termin ist am ___ Mai.","dritten","dritte","After am, the ordinal date ending is -en: am dritten.","am ට පසුව පිළිවෙළ සංඛ්‍යාව dritten වේ."],["Complete: Gestern ___ ich keine Zeit.","hatte","habe","Gestern puts this past state in the past: hatte.","Gestern අතීතය දක්වයි: hatte යොදන්න."]]},
 {title:"Berufe · Modal verbs and dative",rules:[
 ["Jobs and word formation","After sein, a simple profession normally has no article: Ich bin Lehrer. Use als for the job someone works in: als Lehrerin. Many job pairs use -in for a female form, but some are irregular: Kaufmann/Kauffrau.","sein සමඟ වෘත්තිය පමණක් කියන විට බොහෝවිට Artikel නැත. රැකියාවක් ලෙස වැඩ කිරීම සඳහා als යොදන්න. බොහෝ ස්ත්‍රී රූප -in ගනී; සියල්ල එසේ නොවේ.","Ich bin Lehrer. Anna arbeitet als Ärztin.","I am a teacher. Anna works as a doctor."],
 ["wollen and the verb bracket","wollen expresses intention or desire more directly than möchten. ich will, du willst, er will, wir wollen, ihr wollt. Keep the action in the infinitive at the end. Compare a wish with a necessity rather than treating all modals as interchangeable.","wollen සෘජු කැමැත්තක් හෝ අරමුණක් දක්වයි. ich will, du willst, wir wollen. දෙවන ක්‍රියාව Infinitiv ලෙස අවසානයේ තබන්න. möchten වඩා ආචාරශීලීය.","Ich will einen Beruf lernen.","I want to learn a profession."],
 ["Dative: recipient and location","Dative often identifies a recipient: Ich gebe dem Mann das Buch. Masculine/neuter articles become dem/einem, feminine der/einer, plural den. Dative plural nouns usually add -n if they do not already end in -n or -s. Location with in uses dative.","යමක් ලබන පුද්ගලයා බොහෝවිට Dativ වේ. der/das→dem, die→der, බහු die→den. බහු නාමපදයට සාමාන්‍යයෙන් -n එක් වේ; දැනටමත් -n/-s තිබේ නම් නැත.","Ich arbeite in einem Büro.","I work in an office."]],table:[["Masculine","dem / einem","dem Mann"],["Neuter","dem / einem","dem Kind"],["Feminine","der / einer","der Frau"],["Plural","den","den Kindern / den Autos"]],checks:[["Complete: Ich arbeite als ___.","Lehrer","einen Lehrer","A plain profession after als does not need an indefinite article.","als ට පසුව වෘත්තිය පමණක් කියන විට ein අවශ්‍ය නැත."],["Complete: Ich gebe ___ Mann das Buch.","dem","den","The recipient is dative: dem Mann.","ලබන පුද්ගලයා Dativ වේ: dem Mann."]]},
 {title:"Orientierung · Directions and two-way prepositions",rules:[
 ["Wo? or Wohin?","Two-way prepositions an, auf, hinter, in, neben, über, unter, vor and zwischen take dative for a location and accusative for a destination. Movement alone does not decide: walking around in a park is still location; entering the park is a destination.","Wo? ස්ථානයට Dativ, Wohin? ගමනාන්තයට Akkusativ යොදන්න. චලනය තිබීම පමණක් ප්‍රමාණවත් නැත: උද්‍යානය තුළ ඇවිදීම ස්ථානයකි; එයට ඇතුළු වීම ගමනාන්තයකි.","Ich bin im Laden. Ich gehe in den Laden.","I am in the shop. I go into the shop."],
 ["Fixed dative prepositions","aus, bei, mit, nach, von and zu take dative. Use mit for transport, zu for many destinations and bei for someone's place. Learn contractions: in dem → im, an dem → am, zu dem → zum, zu der → zur, bei dem → beim.","aus/bei/mit/nach/von/zu සමඟ Dativ අවශ්‍යයි. ප්‍රවාහනයට mit, බොහෝ ගමනාන්ත සඳහා zu යොදන්න. zum = zu dem, zur = zu der.","Ich fahre mit dem Bus zum Bahnhof.","I travel by bus to the station."],
 ["Formal instructions","A formal imperative uses the verb first and Sie after it: Gehen Sie. Use bitte to soften it. Separable prefixes still go at the end: Steigen Sie hier aus. Direction words such as links and geradeaus do not acquire article endings.","විධිමත් අණක ක්‍රියාව මුලින්ද Sie ඊළඟටද යොදන්න. Bitte ආචාරශීලී කරයි. වෙන්වන උපසර්ගය අවසානයේම තබන්න: Steigen Sie ... aus.","Gehen Sie geradeaus und steigen Sie dort aus.","Go straight ahead and get off there."]],table:[["Wo?","in dem Laden → im Laden","location: dative"],["Wohin?","in den Laden","destination: accusative"],["Transport","mit dem Bus","always dative"],["Destination with zu","zum Bahnhof / zur Schule","always dative"]],checks:[["Complete: Ich gehe in ___ Laden.","den","dem","The destination with in takes accusative: in den Laden.","in සමඟ ගමනාන්තයට Akkusativ: in den Laden."],["Complete: Ich fahre mit ___ Bus.","dem","den","mit always takes dative, so dem Bus.","mit සෑමවිටම Dativ ගනී: dem Bus."]]},
 {title:"Essen und Freizeit · Preferences and comparisons",rules:[
 ["mögen, gern and lieber","mögen takes something you like as an object: Ich mag Tee. gern goes with an activity: Ich trinke gern Tee. lieber marks a preference between alternatives. möchten expresses a request or wish and is not the same as mögen.","කැමති දේකට mögen, කැමැත්තෙන් කරන ක්‍රියාවකට gern යොදන්න. විකල්ප අතර වඩා කැමති එකට lieber යොදන්න. möchten ඉල්ලීමක් හෝ කැමැත්තකි.","Ich mag Tee, aber ich trinke lieber Wasser.","I like tea, but I prefer drinking water."],
 ["Comparative and equal comparison","For many adjectives add -er to compare: klein → kleiner. Use als after an unequal comparison, and so/genauso … wie for equality. Some forms are irregular: gut → besser, viel → mehr, gern → lieber.","වඩා වැඩි/අඩු බවට බොහෝ විශේෂණවලට -er එක් කරන්න. වෙනස් මට්ටම් සඳහා als, සමාන මට්ටමට genauso ... wie. gut→besser වැනි අසාමාන්‍ය රූප ඉගෙන ගන්න.","Tee ist billiger als Saft. Wasser ist genauso kalt wie Tee.","Tea is cheaper than juice. Water is as cold as tea."],
 ["Activities, frequency and questions","gehen can combine with an infinitive for an activity: schwimmen gehen. Say einmal, zweimal or dreimal plus a period for frequency. welch- means which and takes article-like endings: welcher Saft, welches Getränk, welche Suppe.","ක්‍රියාකාරකමකට gehen + Infinitiv යෙදිය හැක: schwimmen gehen. වාර ගණනට einmal/zweimal යොදන්න. welch- නාමපදයේ ලිංගය අනුව වෙනස් වේ.","Wir gehen zweimal pro Woche schwimmen.","We go swimming twice a week."]],table:[["gut","besser","better"],["viel","mehr","more"],["gern","lieber","preferably"],["Equal / different","genauso … wie / -er … als","as … as / more … than"]],checks:[["Complete: Ich trinke ___ Tee. (enjoy)","gern","mögen","gern describes enjoying an activity with a conjugated verb.","gern ක්‍රියාවක් කැමැත්තෙන් කරන බව දක්වයි."],["Complete: Tee ist billiger ___ Saft.","als","wie","An unequal comparative uses als.","වෙනස් මට්ටම් සංසන්දනයට als යොදන්න."]]},
 {title:"Einkaufen · Quantities and instructions",rules:[
 ["How much or how many?","wie viel asks about an amount, price or uncountable quantity: Wie viel Mehl? wie viele asks about countable plural things: Wie viele Eier? With measured amounts, learn useful chunks such as ein Kilo Äpfel or 250 Gramm Mehl.","ප්‍රමාණයක් හෝ මිලක් අහන්න wie viel, ගණන් කළ හැකි බහු දේවලට wie viele යොදන්න. ein Kilo Äpfel වැනි මිනුම් යෙදුම් ඉගෙන ගන්න.","Wie viel Mehl und wie viele Eier brauchen wir?","How much flour and how many eggs do we need?"],
 ["Prices and polite shopping","Euro and Cent normally stay singular after an exact number: drei Euro, zwanzig Cent. A decimal comma separates euros and cents. Ich hätte gern(e) + accusative is a useful polite shopping formula; learn it as a chunk before studying its advanced tense label.","නිශ්චිත ගණනකට පසුව Euro/Cent සාමාන්‍යයෙන් ඒක වචනයේම පවතී. 3,20 යනු යුරෝ තුනයි සෙන්ට් විස්සයි. ආචාරශීලී ඉල්ලීමට Ich hätte gern(e) යොදන්න.","Ich hätte gern ein Brot. Das kostet drei Euro zwanzig.","I would like a loaf of bread. It costs €3.20."],
 ["Recipe instructions","Recipes often use an infinitive without a subject: Zwiebeln schneiden. Direct instructions use an imperative: Schneiden Sie … / Schneide … . Putting something into a bowl or onto a plate is a destination, so in/auf take accusative there.","වට්ටෝරුවක කර්තෘ නැති Infinitiv උපදෙස් යෙදිය හැක. සෘජු අණට Schneiden Sie හෝ Schneide යොදන්න. බඳුනකට දමන විට ගමනාන්තය නිසා Akkusativ යොදන්න.","Geben Sie das Mehl in die Schüssel.","Put the flour into the bowl."]],table:[["Uncountable","Wie viel Wasser?","how much water"],["Countable plural","Wie viele Äpfel?","how many apples"],["3,20 €","drei Euro (und) zwanzig Cent","three euros twenty"],["Recipe","Zwiebeln schneiden","cut onions"]],checks:[["Complete: Wie ___ Eier brauchen wir?","viele","viel","Eier is a countable plural, so use wie viele.","Eier ගණන් කළ හැකි බහු වචනයකි; wie viele යොදන්න."],["Complete: Geben Sie das Mehl in ___ Schüssel.","die","der","Putting flour into the bowl expresses a destination: accusative.","බඳුනට දමන ගමනාන්තය Akkusativ වේ."]]},
 {title:"Urlaub und Wetter · The perfect tense",rules:[
 ["Build the perfect tense","Use a conjugated auxiliary haben or sein in position 2 and the past participle at the end. Many regular participles use ge- + stem + -t: machen → gemacht. Verbs ending -ieren have no ge-: telefoniert. Inseparable prefixes such as be- and ver- also block ge-.","Perfekt සඳහා haben/sein දෙවන තැනත් Partizip අවසානයේත් යොදන්න. සාමාන්‍යයෙන් ge + මුල + t. -ieren සහ be-/ver- වැනි වෙන් නොවන උපසර්ගවල ge නැත.","Ich habe Deutsch gelernt und telefoniert.","I studied German and made a phone call."],
 ["haben or sein?","Most verbs use haben. Many intransitive verbs of change of place or state use sein: gefahren, gekommen, aufgewacht. bleiben and sein also use sein. Learn the auxiliary with the participle; a transitive use can change the usual choice.","බොහෝ ක්‍රියා haben ගනී. ස්ථානය/තත්ත්වය වෙනස් කරන බොහෝ කර්ම රහිත ක්‍රියා sein ගනී. පැමිණීම ist gekommen, රැඳීම ist geblieben. Partizip සමඟ සහායකයත් මතක තබන්න.","Wir sind nach Berlin gefahren. Wir haben Pizza gegessen.","We travelled to Berlin. We ate pizza."],
 ["Irregular participles and weather es","Strong participles often end -en: gesehen, gegessen, gefunden. A separable prefix puts ge inside: eingekauft, aufgestanden. For weather use impersonal es: Es regnet; Es ist kalt. Seasonal expressions often use im: im Sommer.","අසාමාන්‍ය Partizip බොහෝවිට -en ගනී. වෙන්වන ක්‍රියාවල ge මැදට යයි: eingekauft. කාලගුණයට es යොදන්න; සෘතුවට im Sommer.","Im Winter ist es kalt. Gestern hat es geregnet.","It is cold in winter. It rained yesterday."]],table:[["machen / lernen","hat gemacht / hat gelernt","regular"],["essen / finden","hat gegessen / hat gefunden","irregular"],["fahren / kommen","ist gefahren / ist gekommen","change of place"],["aufstehen / einkaufen","ist aufgestanden / hat eingekauft","separable prefix"]],checks:[["Complete: Wir ___ nach Berlin gefahren.","sind","haben","Intransitive travel to a destination uses sein here.","ගමනාන්තයකට ගමන් කිරීම මෙහි sein ගනී."],["Complete: Ich habe Deutsch ___.","gelernt","gelernen","lernen is regular: ge- + lern + -t.","lernen සාමාන්‍ය ක්‍රියාවකි: ge + lern + t."]]},
 {title:"Kleidung · Adjectives and dative preferences",rules:[
 ["An adjective before a noun needs an ending","Compare Der Pullover ist neu with der neue Pullover. After a definite article, nominative singular usually uses -e; accusative masculine uses -en. After ein, the adjective must show missing gender information: ein neuer Pullover, ein neues Hemd.","නාමපදයට පෙර විශේෂණයට අවසානයක් අවශ්‍යයි. der neue Pullover, ein neuer Pullover. නාමපදයට පසු sein සමඟ neu පමණයි. Akkusativ පුරුෂයේ -en යෙදේ.","Ich kaufe einen neuen Pullover.","I buy a new jumper."],
 ["welcher and dieser follow article patterns","welcher asks which and dieser identifies this. Their endings follow gender and case: dieser Pullover, dieses Hemd, diese Jacke; accusative diesen Pullover. The adjective after them follows the definite-article pattern.","welcher යනු කුමනද; dieser යනු මේ ය. ලිංගය හා විභක්තිය අනුව අවසානය වෙනස් වේ: dieses Hemd, diesen Pullover. ඉන් පසුව විශේෂණය definite Artikel රටාව ගනී.","Welchen Pullover möchtest du? Diesen blauen Pullover.","Which jumper would you like? This blue jumper."],
 ["gefallen, passen and stehen","The item is the subject; the person experiencing the effect is dative: Der Pullover gefällt mir. Use passt mir for fit and steht mir for looking good on someone. In Das Hemd ist mir zu eng, mir names the person affected and zu means too.","ඇඳුම කර්තෘ වේ; කැමති හෝ ගැළපෙන පුද්ගලයා Dativ: gefällt mir. passt mir යනු ප්‍රමාණය ගැළපේ; steht mir යනු ඇඳීමෙන් ලස්සනයි.","Die Jacke gefällt mir, aber sie ist mir zu eng.","I like the jacket, but it is too tight for me."]],table:[["Nominative masculine","der neue / ein neuer Pullover","new jumper"],["Accusative masculine","den neuen / einen neuen Pullover","object"],["Nominative neuter","das neue / ein neues Hemd","new shirt"],["Nominative feminine","die neue / eine neue Jacke","new jacket"]],checks:[["Complete: Ich kaufe einen ___ Pullover.","neuen","neuer","After einen, a masculine accusative adjective ends -en.","einen ට පසුව පුරුෂ Akkusativ විශේෂණයට -en යෙදේ."],["Complete: Die Jacke gefällt ___. (to me)","mir","mich","gefallen uses dative for the person: mir.","gefallen සමඟ පුද්ගලයා Dativ: mir."]]},
 {title:"Familie · Object pronouns, für and sollen",rules:[
 ["Accusative pronouns","Replace an already known direct object with mich, dich, ihn, sie, es, uns, euch, sie or Sie. Choose the form by grammatical gender and person. The formal object Sie stays capitalized.","දන්නා සෘජු කර්මයක් වෙනුවට mich/dich/ihn/sie/es යොදන්න. නාමපදයේ ලිංගය හා පුද්ගලයා අනුව තෝරන්න. ගෞරවනීය කර්මය Sie ලොකු අකුරින් පවතී.","Ich sehe meinen Bruder. Ich sehe ihn.","I see my brother. I see him."],
 ["für always takes accusative","für expresses for or intended for. It is not a two-way preposition: use accusative even when no movement is involved. Compare für meinen Bruder with mit meinem Bruder. Possessive endings change with case just like ein endings.","für සෑමවිටම Akkusativ ගනී. චලනයක් තිබේද යන්න වැදගත් නැත. für meinen Bruder, නමුත් mit meinem Bruder. අයිති පදවල අවසානද විභක්තියට අනුව වෙනස් වේ.","Das Geschenk ist für meine Schwester.","The present is for my sister."],
 ["sollen relays an instruction","sollen often conveys what someone else says should be done. müssen conveys necessity, while wollen conveys your own intention. Keep the second verb in the infinitive at the end: soll … gießen. Learn ich soll, du sollst, er soll, wir sollen, ihr sollt.","sollen බොහෝවිට වෙනත් කෙනෙකුගේ උපදෙස කියයි. müssen අවශ්‍යතාවය, wollen තම කැමැත්තයි. දෙවන ක්‍රියාව Infinitiv ලෙස අවසානයේ තබන්න.","Meine Tante sagt, ich soll die Blumen gießen.","My aunt says I should water the flowers."]],table:[["ich / du","mich / dich","me / you"],["er / sie / es","ihn / sie / es","him / her / it"],["wir / ihr","uns / euch","us / you"],["sie / Sie","sie / Sie","them / formal you"]],checks:[["Complete: Das Geschenk ist für ___ Bruder. (my)","meinen","meinem","für always takes accusative: meinen Bruder.","für සෑමවිටම Akkusativ: meinen Bruder."],["Complete: Ich sehe meinen Bruder. Ich sehe ___.","ihn","ihm","The direct object becomes the accusative pronoun ihn.","සෘජු කර්මයට Akkusativ සර්වනාමය ihn යෙදේ."]]},
 {title:"Sport · Superlatives and informal instructions",rules:[
 ["Compare performance","A comparative describes a higher degree: schneller, höher, besser. A predicative superlative uses am … -sten/-esten: am schnellsten, am besten. Many short adjectives also change their vowel. Do not add -er to an already irregular comparative such as besser.","සංසන්දනයට schneller/höher/besser යොදන්න. ඉහළම මට්ටමට am ... -sten/-esten: am besten. besser වැනි රූපයට නැවත -er එක් නොකරන්න.","Nico läuft schnell. Max läuft schneller. Anna läuft am schnellsten.","Nico runs fast. Max runs faster. Anna runs fastest."],
 ["du, ihr and Sie imperatives","For du, usually use the verb stem without du: Komm! For ihr, use the normal ihr verb without ihr: Kommt! For formal Sie, keep Sie: Kommen Sie! Some strong verbs change: essen → Iss!, nehmen → Nimm!, lesen → Lies!.","du අණක බොහෝවිට මුල පමණයි: Komm! ihr අණක සාමාන්‍ය රූපය: Kommt! Sie අණක Sie තබන්න. essen→Iss වැනි අසාමාන්‍ය රූප මතක තබන්න.","Iss mehr Obst! Trainiert zusammen!","Eat more fruit! Train together!"],
 ["When, how often, how long?","wann asks when; wie oft asks frequency; wie lange asks duration. Answer a duration with a time amount, and frequency with a number plus a period. These questions ask different things even when the same activity is discussed.","wann කවදාද, wie oft වාර කීයක්ද, wie lange කොපමණ කාලයක්ද අහයි. කාල දිග හා වාර ගණන වෙන වෙනම පිළිතුරු දෙන්න.","Ich trainiere zweimal pro Woche, jeweils eine Stunde.","I train twice a week, for an hour each time."]],table:[["schnell","schneller / am schnellsten","fast"],["hoch","höher / am höchsten","high"],["gut","besser / am besten","good"],["viel","mehr / am meisten","much"]],checks:[["Choose the du instruction for essen.","Iss!","Esst!","Iss is singular informal; Esst addresses several people informally.","Iss එක් හිතවත් පුද්ගලයෙකුටය; Esst කිහිප දෙනෙකුටය."],["Complete: Anna läuft am ___.","schnellsten","schneller","am takes the superlative form, not the comparative.","am සමඟ ඉහළම මට්ටමේ රූපය යොදන්න."]]},
 {title:"Gesundheit · Necessity, permission and time",rules:[
 ["müssen, sollen and dürfen","müssen expresses necessity; sollen often expresses advice or an instruction from another person; dürfen expresses permission. Crucially, nicht müssen means do not have to, while nicht dürfen means must not. Do not confuse lack of necessity with a prohibition.","müssen අනිවාර්ය අවශ්‍යතාවය, sollen උපදෙස්, dürfen අවසරයයි. nicht müssen = අවශ්‍ය නැහැ; nicht dürfen = කරන්න තහනම්. මේ දෙක වෙන් කරගන්න.","Du musst nicht warten. Du darfst nicht laufen.","You do not have to wait. You must not run."],
 ["Symptoms and dative person","A body part can be the subject of wehtun: Mein Fuß tut weh; Meine Füße tun weh. Add a dative person if useful: Mein Fuß tut mir weh. haben takes accusative in symptom phrases: Ich habe einen Husten.","රිදෙන ශරීර කොටස කර්තෘ වේ: Fuß tut, Füße tun. රිදෙන පුද්ගලයා Dativ mir ලෙස එක් කළ හැක. haben සමඟ රෝග ලක්ෂණයට Akkusativ යොදන්න.","Meine Beine tun mir weh.","My legs hurt."],
 ["Before, after and noun forms","For time, vor and nach take dative: vor dem Essen, nach der Behandlung. A verb used as a noun is capitalized and neuter: das Essen, beim Gehen. Revisit the perfect for an accident: ist passiert but hat wehgetan.","කාලය කියන vor/nach සමඟ Dativ යොදන්න. ක්‍රියාව නාමපදයක් වූ විට ලොකු අකුරින් හා das සමඟ ලියන්න: das Essen. සිදුවීම ist passiert ලෙස ඉගෙන ගන්න.","Nach dem Essen nehme ich die Tablette.","After eating I take the tablet."]],table:[["Necessity","Du musst warten.","You have to wait."],["No necessity","Du musst nicht warten.","You do not have to wait."],["Permission","Du darfst laufen.","You are allowed to walk/run."],["Prohibition","Du darfst nicht laufen.","You must not walk/run."]],checks:[["Which sentence means you must not run?","Du darfst nicht laufen.","Du musst nicht laufen.","nicht dürfen is a prohibition; nicht müssen means no obligation.","nicht dürfen තහනමකි; nicht müssen අවශ්‍යතාවයක් නැති බවයි."],["Complete: Nach ___ Essen nehme ich die Tablette.","dem","das","Temporal nach always takes dative.","කාලය කියන nach සමඟ Dativ යොදන්න."]]},
 {title:"Heimat · Dative pronouns and wishes",rules:[
 ["Dative pronouns","Use mir, dir, ihm, ihr, ihm, uns, euch, ihnen and Ihnen for dative people. Verbs such as helfen, gefallen and fehlen select dative. In Du fehlst mir, du is the subject and mir is the person who misses you; the English wording reverses the perspective.","Dativ පුද්ගල රූප mir/dir/ihm/ihr/uns/euch/ihnen/Ihnen වේ. helfen/gefallen/fehlen ඒවා ගනී. Du fehlst mir යනු මට ඔයා නැති අඩුව දැනෙනවා යන්නයි.","Meine Familie fehlt mir. Kannst du mir helfen?","I miss my family. Can you help me?"],
 ["Describe home and maintain article endings","A description before a noun still needs adjective endings: in einem großen Haus. After a dative article or ein-word, the adjective takes -en. With plural dative, check both article and noun: mit den guten Freunden.","නාමපදයට පෙර විස්තරයට අවසාන අවශ්‍යයි: in einem großen Haus. Dativ Artikel පසුව විශේෂණයට -en. බහු Dativ නාමපදයේ -n ද පරීක්ෂා කරන්න.","Wir wohnen in einem kleinen Dorf.","We live in a small village."],
 ["Useful wishes: hätte, wäre and würde","For A1, learn practical wish patterns: Ich hätte gern + noun; Ich wäre gern + state or profession; Ich würde gern + infinitive at the end. These are polite or imagined wishes, not ordinary past statements. von in träumen von always takes dative.","A1 සඳහා ප්‍රයෝජනවත් කැමැත්තේ රටා ඉගෙන ගන්න: hätte gern + නාමපදය, wäre gern + තත්ත්වය, würde gern + අවසාන Infinitiv. träumen von හි von සමඟ Dativ යොදන්න.","Ich würde gern Deutsch sprechen. Ich träume von einem Laden.","I would like to speak German. I dream of a shop."]],table:[["ich / du","mir / dir","to me / to you"],["er / sie / es","ihm / ihr / ihm","to him / her / it"],["wir / ihr","uns / euch","to us / to you"],["sie / Sie","ihnen / Ihnen","to them / to formal you"]],checks:[["Complete: Kannst du ___ helfen? (me)","mir","mich","helfen takes a dative person: mir.","helfen සමඟ පුද්ගලයා Dativ: mir."],["Complete: Ich würde gern Deutsch ___.","sprechen","spreche","würde forms a bracket with the infinitive at the end.","würde සමඟ දෙවන ක්‍රියාව Infinitiv ලෙස අවසානයට යයි."]]},
];
